#' @title diff.analyses.proDA
#'
#' @description
#' Allows for the computation of differential analyses using
#' \href{https://bioconductor.org/packages/release/bioc/html/proDA.html}{\code{proDA}}
#' (Ahlmann-Eltze & Anders, 2020), a dropout-aware model that treats the missing values as
#' left-censored observations instead of replacing them. Includes means, Fold Changes, and p-values.
#'
#' @param DEprot.object An object of class \code{DEprot}.
#' @param contrast.list List of 3-elements vectors indicating (in order): metadata_column, variable_1, variable_2.
#' @param include.rep.model Logical value indicating whether the model should include the replicate information (added as a blocking fixed effect). Requires a 'replicate.column'. Default: \code{FALSE}.
#' @param replicate.column String indicating the name of a column from the metadata table in which are stored the replicate IDs. This column is used only if \code{include.rep.model = TRUE}. Default: \code{NULL}.
#' @param linear.FC.th Number indicating the (absolute) fold change threshold (linear scale) to use to define differential proteins. Default: \code{2}.
#' @param linear.FC.unresp.range A numeric 2-elements vector indicating the range (linear scale) used to define the unresponsive fold changes. Default: \code{c(1/1.1, 1.1)}.
#' @param padj.th Numeric value indicating the p.adjusted threshold to apply to the differential analyses. Default: \code{0.05}.
#' @param padj.method String indicating the method to use to correct the p-values. One among: "holm", "hochberg", "hommel", "bonferroni", "BH", "BY", "fdr", "none", "fdrtool". Default: \code{BH}.
#' @param moderate.location Logical value indicating whether the protein means should be moderated towards a common location prior. Default: \code{TRUE}.
#' @param moderate.variance Logical value indicating whether the protein variances should be moderated towards a common variance prior (empirical Bayes, as in \code{limma}). Default: \code{TRUE}.
#' @param min.detected Integer indicating the minimum number of observed (non-missing) values that a protein must have, over all the samples included in the model, to be fitted. Proteins below this threshold, as well as the proteins never quantified in any of the samples of a specific contrast, are kept in the results table with \code{NA} statistics. Default: \code{1}.
#' @param n.subsample Integer indicating the number of proteins to use to estimate the hyper-parameters (dropout curves, location and variance priors). When \code{NULL} all the proteins are used. Rows are shuffled before the subsampling. Default: \code{NULL}.
#' @param max.iter Integer indicating the maximum number of iterations of the hyper-parameter estimation loop. Default: \code{20}.
#' @param max.attempts Integer indicating the number of times a new subsample of proteins is drawn when the estimation of the hyper-parameters fails. Used only when \code{n.subsample} is not \code{NULL}; the last attempt is always performed on all the proteins available for the contrast. Default: \code{3}.
#' @param missingness.object An object generated by \link{missingness.diagnostic} used to check the censoring assumption. When \code{NULL} (default) the diagnostic is computed internally if \code{check.missingness = TRUE}. Default: \code{NULL}.
#' @param check.missingness Logical value indicating whether the missingness pattern should be checked before fitting the model. Default: \code{TRUE}.
#' @param up.color String indicating the color to use for up-regulated proteins in the plots. Default: \code{"indianred"}.
#' @param down.color String indicating the color to use for up-regulated proteins in the plots. Default: \code{"steelblue"}.
#' @param unresponsive.color String indicating the color to use for unresponsive proteins in the plots. Default: \code{"purple"}.
#' @param null.color String indicating the color to use for null proteins in the plots. Default: \code{"gray"}.
#' @param which.data String indicating which type of counts should be used. One among: 'raw', 'normalized', 'norm', 'randomized', 'random', 'imputed', 'imp'. Default: \code{"normalized"}.
#' @param seed Numeric value to use as seed when \code{n.subsample} is defined. Default: \code{NULL} (random seed).
#' @param verbose Logical value indicating whether the messages of the model fitting should be printed. Default: \code{FALSE}.
#' @param overwrite.analyses Logical value to indicate whether overwrite analyses already generated. Default: \code{FALSE}.
#'
#' @details
#' Differently from the other differential functions of the package, this one must be applied to counts that
#' still contain the missing values (normalized, not imputed): a missing value is not replaced but read as
#' the statement "this protein was below the detection limit in this sample", exactly as a left-censored
#' observation in a survival model. The probability of observing a value at a given intensity is described by
#' a sigmoidal dropout curve estimated separately for each sample, and the group means are inferred on the
#' mixture of measured and censored observations. The uncertainty on the censored values is therefore kept
#' inside the model and propagated to \code{lfcSE}, so that a protein detected in one replicate out of three
#' receives a wide standard error instead of the artificially small variance produced by the imputation of
#' values drawn from the bottom of the distribution.
#'
#' The model is fitted on all the samples sharing the metadata column of the contrast (design
#' \code{~ 0 + <metadata.column>}, plus the replicate when \code{include.rep.model = TRUE}), and the contrast
#' is tested afterwards with a Wald test: the behaviour is the same as \link{diff.analyses.limma}, and it
#' means that the samples of the other groups of the same column contribute to the estimation of the
#' hyper-parameters and to the residual degrees of freedom. Contrasts defined on the same metadata column
#' share a single fit whenever they are computed on the same set of proteins.
#'
#' The proteins used for the fit are defined contrast by contrast: a protein that has not been quantified in
#' any of the samples of the two groups compared carries no information on that specific contrast, the
#' censored likelihood becomes flat and the optimizer fails. These proteins, together with the ones below
#' \code{min.detected}, are excluded from the fit and re-introduced in the results table with \code{NA} fold
#' change, p-value and differential status, so that the output always keeps one row per protein, in the order
#' of the counts table. Being untested, they are not counted in \code{n.diff} and are not drawn in the volcano
#' and MA plots. Proteins detected in only one of the two groups are instead retained, since that asymmetry is
#' exactly what the dropout-aware model is meant to describe.
#'
#' The \code{log2(FoldChange)} is the contrast estimate of the censored model, and not the difference between
#' the observed means: for a protein missing in one of the two groups the two quantities differ substantially,
#' since the model extrapolates below the detection limit instead of using the values that happened to be
#' observed. The \code{log2.mean.<group>} columns report the model-based (censoring-aware) group means,
#' computed as the average of the fitted values over the samples of each group; their difference coincides
#' with the reported \code{log2(FoldChange)} for balanced designs, but not necessarily when
#' \code{include.rep.model = TRUE} on an unbalanced design. The \code{sd.<group>} and \code{sem.<group>}
#' columns are instead purely descriptive and are computed on the observed values only, so they are affected
#' by the survivor bias of the missing values.
#'
#' Three extra columns are appended at the end of the results table: \code{n.detected.<group>}, the number of
#' samples in which the protein was actually quantified in each group, and \code{n.approx}, the effective
#' sample size estimated by \code{proDA} over all the samples of the model, which counts how much information
#' the censored observations carry (a value close to \code{n.obs} means that the missing values are not
#' informative).
#'
#' When set to \code{"fdrtool"}, the moderated t-statistics are passed to \code{fdrtool::fdrtool} (as normal
#' deviates, \code{statistic = "normal"}), which estimates the proportion of null features and an empirical
#' null: the resulting tail-area-based q-values are stored in the \code{padj} column, while the local false
#' discovery rate (\code{lfdr}) is added as an extra column of the results table. If fewer than 200 proteins
#' with a finite statistic are available for a contrast, or the fit fails, a Benjamini-Hochberg correction is
#' applied for that contrast (a warning is raised).
#'
#' The censoring assumption is verified before fitting the model: when \link{missingness.diagnostic} finds no
#' significant dependency between the intensity of a protein and its probability of being missing, the data
#' are not left-censored and there is nothing to gain from this model over \link{diff.analyses.limma} applied
#' to imputed counts (a warning is raised, the analyses are performed anyway). The dropout curve position
#' estimated by \code{proDA} for each sample is stored in the results list and is the per-sample equivalent of
#' the \code{LOD50} returned by the diagnostic: strongly diverging values indicate that one or more samples
#' have a detection limit of their own and should be inspected.
#'
#' @import dplyr
#' @import ggplot2
#' @import patchwork
#' @import ggtext
#' @import progress
#' @importFrom proDA proDA test_diff coefficients hyper_parameters
#' @importFrom purrr pmap
#' @importFrom RColorBrewer brewer.pal
#' @importFrom grDevices colorRampPalette
#' @importFrom stats model.matrix sd var p.adjust median runif
#' @importFrom fdrtool fdrtool
#'
#' @author Sebastian Gregoricchio
#'
#' @return An object of class \code{DEprot.analyses}
#'
#' @examples
#' # Dropout-aware analyses: the counts must still contain the missing values
#' dpo <- diff.analyses.proDA(DEprot.object = DEprot::test.toolbox$dpo.norm,
#'                            contrast.list = list(c("condition", "FBS", "6h.DMSO"),
#'                                                 c("condition", "6h.10nM.E2", "6h.DMSO")),
#'                            linear.FC.th = 1.5)
#'
#'
#' # Including the replicate as a blocking factor
#' dpo <- diff.analyses.proDA(DEprot.object = DEprot::test.toolbox$dpo.norm,
#'                            contrast.list = list(c("condition", "FBS", "6h.DMSO"),
#'                                                 c("condition", "6h.10nM.E2", "6h.DMSO")),
#'                            include.rep.model = TRUE,
#'                            replicate.column = "replicate",
#'                            linear.FC.th = 1.5)
#'
#'
#'
#'
#' @export diff.analyses.proDA

diff.analyses.proDA =
  function(DEprot.object,
           contrast.list,
           include.rep.model = FALSE,
           replicate.column = NULL,
           linear.FC.th = 2,
           linear.FC.unresp.range = c(1/1.1, 1.1),
           padj.th = 0.05,
           padj.method = "BH", # c("holm", "hochberg", "hommel", "bonferroni", "BH", "BY", "fdr", "none", "fdrtool")
           moderate.location = TRUE,
           moderate.variance = TRUE,
           min.detected = 1,
           n.subsample = NULL,
           max.iter = 20,
           max.attempts = 3,
           missingness.object = NULL,
           check.missingness = TRUE,
           up.color = "indianred",
           down.color = "steelblue",
           unresponsive.color = "purple",
           null.color = "gray",
           which.data = "normalized",
           seed = NULL,
           verbose = FALSE,
           overwrite.analyses = FALSE) {

    # ### Packages
    # require(dplyr)
    # require(proDA)
    # require(ggplot2)
    # require(patchwork)


    ### check object and extract metadata table
    if (!("DEprot" %in% class(DEprot.object))) {
      if (!("DEprot.analyses" %in% class(DEprot.object))) {
        stop("The input must be an object of class 'DEprot' or 'DEprot.analyses.")
      }
    }

    meta.tb = DEprot.object@metadata


    ### Check 'replicate.column' presence
    if (!is.null(replicate.column[[1]])) {
      if (!(replicate.column %in% colnames(meta.tb))) {
        stop("The 'replicate.column' is not present in the metadata of the object.")
      } else {
        meta.tb[,replicate.column[[1]]] = as.character(meta.tb[,replicate.column[[1]]])
      }
    } else if (include.rep.model == TRUE) {
      stop("The replicate model was required ('include.rep.model = TRUE') but no 'replicate.column' was provided.")
    }


    ### Check p-value correction method
    if (!(padj.method %in% c(stats::p.adjust.methods, "fdrtool"))) {
      stop(paste0("The 'padj.method' value is not recognized.\n",
                  "Please indicate one among: ", paste0(c(stats::p.adjust.methods, "fdrtool"), collapse = ", "), "."))
    }




    ### Check contrasts
    if (all(is.na(DEprot.object@contrasts))) {
      if ("character" %in% class(contrast.list)) {
        contrasts = list(contrast.list)
      } else if ("list" %in% class(contrast.list)) {
        contrasts = contrast.list
      } else {
        stop("The 'contrast.list' must be a list of 3-elements vectors indicating: metadata_column, variable_1, variable_2.")
        #return(DEprot.object)
      }

    } else if (overwrite.analyses == FALSE) {
      DEprot.object@contrasts
      stop("The DEprot object contains already a contrast list.\n",
           "       To overwrite the contrast list set the parameter `overwrite.analyses = TRUE`")
    } else {
      if ("character" %in% class(contrast.list)) {
        contrasts = list(contrast.list)
      } else if ("list" %in% class(contrast.list)) {
        contrasts = contrast.list
      } else {
        stop("The 'contrast.list' must be a list of 3-elements vector indicating: metadata_column, variable_1, variable_2.")
      }
    }


    # check the presence of columns and variables in the contrast
    contrasts.info = list()

    for (i in 1:length(contrasts)) {
      if (!(contrasts[[i]][1] %in% colnames(meta.tb))) {
        stop(paste0("The column indicated in the contrast #", i, " ('",contrasts[[i]][1],"'), it is not available in the metadata table."))
      } else if (!(contrasts[[i]][2] %in% meta.tb[,contrasts[[i]][1]])) {
        stop(paste0("In the contrast #", i, " ('",contrasts[[i]][1],"'), the first variable ('",contrasts[[i]][2],"') is not available."))
      } else if (!(contrasts[[i]][3] %in% meta.tb[,contrasts[[i]][1]])) {
        stop(paste0("In the contrast #", i, " ('",contrasts[[i]][1],"'), the first variable ('",contrasts[[i]][3],"') is not available."))
      } else {

        # Collect info
        contrasts.info[[i]] = list(metadata.column = contrasts[[i]][1],
                                   var.1 = contrasts[[i]][2],
                                   var.2 = contrasts[[i]][3],
                                   group.1 = meta.tb[meta.tb[,contrasts[[i]][1]] == contrasts[[i]][2],"column.id"],
                                   group.2 = meta.tb[meta.tb[,contrasts[[i]][1]] == contrasts[[i]][3],"column.id"],
                                   paired.test = include.rep.model)
        names(contrasts.info)[i] = paste0(contrasts[[i]][1], "_", contrasts[[i]][2], ".vs.", contrasts[[i]][3])
      }
    }



    ### Check and extract table
    if (tolower(which.data) == "raw") {
      if (!is.null(DEprot.object@raw.counts)) {
        mat = DEprot.object@raw.counts
        data.used = "raw"
      } else {
        stop(paste0("Use of RAW counts was required, but not available.\n",
                    "Please indicated a count type among 'raw', 'normalized', 'randomized, 'imputed', using the option 'which.data'."))
      }
    } else if (tolower(which.data) %in% c("norm", "normalized", "normalised", "normal")) {
      if (!is.null(DEprot.object@norm.counts)) {
        mat = DEprot.object@norm.counts
        data.used = "normalized"
      } else {
        stop(paste0("Use of NORMALIZED counts was required, but not available.\n",
                    "Please indicated a count type among 'raw', 'normalized', 'randomized, 'imputed', using the option 'which.data'."))
      }
    } else if (tolower(which.data) %in% c("imputed", "imp", "impute")) {
      if (!is.null(DEprot.object@imputed.counts)) {
        mat = DEprot.object@imputed.counts
        data.used = "imputed"
      } else {
        stop(paste0("Use of IMPUTED counts was required, but not available.\n",
                    "Please indicated a count type among 'raw', 'normalized', 'randomized, 'imputed', using the option 'which.data'."))
      }
    } else if (tolower(which.data) %in% c("randomized", "randomised", "random")) {
      if (!is.null(DEprot.object@random.counts)) {
        mat = DEprot.object@random.counts
        data.used = "randomized"
      } else {
        stop(paste0("Use of RANDOMIZED counts was required, but not available.\n",
                    "Please indicated a count type among 'raw', 'normalized', 'randomized, 'imputed', using the option 'which.data'."))
      }
    } else {
      stop(paste0("The 'which.data' value is not recognized.\n",
                  "Please indicated a count type among 'raw', 'normalized', 'imputed', using the option 'which.data'."))
    }


    ## Convert table to log2
    if (!is.numeric(DEprot.object@log.base)) {
      warning("The log.base is not numeric, linear counts are assumed. Counts matrix will be converted to log2+1 values to analyze the data.")
      mat.log2 = log2(mat + 1)
    } else if (as.numeric(DEprot.object@log.base) != 2) {
      warning("The log.base is not 2, counts will be converted to log2 values to analyze the data.")
      mat.log2 = log2(DEprot.object@log.base^mat)
    } else {
      mat.log2 = mat
    }

    mat.log2[is.nan(mat.log2)] = NA




    #################################################
    ## Check that the counts are still censored
    ## The model reads a missing value as an observation below the detection limit: counts in which the
    ## missing values have already been replaced (imputed or randomized) carry no censoring information
    ## anymore and the fit degenerates into a standard moderated linear model on invented values.
    if (data.used %in% c("imputed", "randomized")) {
      stop(paste0("The dropout-aware model requires counts that still contain the missing values, but ",
                  toupper(data.used), " counts were required.\n",
                  "       Please use 'which.data = \"normalized\"' (or 'raw'): the missing values are not replaced but modelled as left-censored observations."))
    }

    if (!(TRUE %in% is.na(mat.log2))) {
      warning("The counts matrix does not contain any missing value: there is nothing to censor and the model reduces to a standard moderated linear model. ",
              "Consider using 'diff.analyses.limma' instead.")
    }


    ## Check the missingness pattern
    ## The censored model is worth its cost only when the probability of being missing depends on the
    ## intensity (left-censoring). The verdict of 'missingness.diagnostic' is used here as a sanity check
    ## and its parameters are stored, together with the dropout curves estimated by the model, to allow a
    ## direct comparison between the two estimations of the detection limit.
    missingness.stats = NULL

    if (isTRUE(check.missingness) & (TRUE %in% is.na(mat.log2))) {
      if (is.null(missingness.object)) {
        missingness.object = tryCatch(expr = DEprot::missingness.diagnostic(DEprot.object = DEprot.object,
                                                                            which.data = data.used),
                                      error = function(e){NULL})
      }

      ## the diagnostic is read defensively: a failure of the check must not block the analyses
      missingness.stats = tryCatch(expr = {
        stats.list = if (isS4(missingness.object)) {missingness.object@global.stats} else {missingness.object$global.stats}
        stats.list[c("LOD50", "dropout.slope", "dropout.pvalue", "perc.missing", "perc.missing.MNAR")]
      },
      error = function(e){NULL})

      if (!is.null(missingness.stats)) {
        not.censored = isTRUE(missingness.stats$dropout.pvalue > 0.05) | isTRUE(missingness.stats$dropout.slope >= 0)

        if (not.censored) {
          warning("The missingness diagnostic does not detect a significant dependency between the intensity of a protein and its probability of being missing ",
                  "(dropout slope = ", round(missingness.stats$dropout.slope, 3), ", p = ", signif(missingness.stats$dropout.pvalue, 3), "): ",
                  "the data do not look left-censored and a dropout-aware model brings no advantage over 'diff.analyses.limma' on imputed counts. ",
                  "The analyses will be performed anyway.")
        }
      }
    }




    #################################################
    ## Define the proteins available for the fit
    ## Proteins never (or almost never) quantified cannot inform any parameter and are excluded from the
    ## fit to avoid destabilizing the estimation of the priors. They are kept in the results table with NA
    ## statistics, so that the output keeps one row per protein as for the other differential functions.
    ## The final selection is made contrast by contrast, inside the loop, since a protein can be
    ## informative for one comparison and completely absent from another one.
    prot.order = rownames(mat.log2)
    n.detected.all = rowSums(!is.na(mat.log2))
    min.detected = max(c(1, round(min.detected, 0)))
    var.all = apply(X = mat.log2, MARGIN = 1, FUN = function(x){var(x, na.rm = TRUE)})

    if (sum(n.detected.all >= min.detected) < 2) {
      stop(paste0("Only ", sum(n.detected.all >= min.detected), " protein(s) reach the minimum number of observed values required ('min.detected' = ", min.detected, "): the model cannot be fitted."))
      #return(DEprot.object)
    }


    ## The seed is defined here and reused for all the contrasts, so that the subsampling of the proteins
    ## used to estimate the hyper-parameters is reproducible whether the seed was provided or not.
    if (is.null(seed)) {
      seed = round(stats::runif(n = 1, min = 0, max = 2^31-1), 0)
    }

    max.attempts = max(c(1, round(max.attempts, 0)))


    ## Ordering of the proteins passed to the model
    ## proDA estimates the priors on the FIRST 'n_subsample' rows of the matrix, which are not a random
    ## subset of the data (the counts tables are usually sorted by intensity or by search-engine score),
    ## therefore the rows are shuffled beforehand. On top of the shuffling, the proteins that can actually
    ## inform the priors (at least two observed values and some variability) are moved to the top: a
    ## subsample made only of barely detected or constant proteins makes the likelihood degenerate and the
    ## optimizer returns a NA/NaN gradient. The results are collected by protein ID, hence the row order of
    ## the matrix is irrelevant for the output.
    shuffle.proteins =
      function(protein.ids,
               seed.value) {
        set.seed(seed.value)
        shuffled = sample(x = protein.ids, size = length(protein.ids), replace = FALSE)
        informative = which(n.detected.all[shuffled] >= 2 & !is.na(var.all[shuffled]) & var.all[shuffled] > 0)

        if (length(informative) > 0) {
          return(c(shuffled[informative], shuffled[-informative]))
        } else {
          return(shuffled)
        }
      }




    #################################################
    ## Set-up progress bar
    pb = progress::progress_bar$new(format = "(:spin) :bar :percent [Elapsed time: :elapsedfull || ETA: :eta]",
                                    total = length(contrasts.info),
                                    complete = "\u2588",   # Completion bar character
                                    incomplete = "\u2591", # Incomplete bar character
                                    current = "\u2592",    # Current bar character
                                    clear = TRUE,        # If TRUE, clears the bar when finish
                                    width = 120)       # Width of the progress bar


    ## Compute proDA-based analyses
    linear.FC.unresp.range = sort(linear.FC.unresp.range)
    diff.analyses.list = list()
    fit.cache = list()
    n.subsample.used = NA

    for (i in 1:length(contrasts.info)) {
      ## Define the design
      ## As for limma, the model is fitted on all the samples of the metadata column and the two groups of
      ## the contrast are compared afterwards, so that all the samples contribute to the priors and to the
      ## residual degrees of freedom.
      design = model.matrix(~ 0 + meta.tb[,contrasts.info[[i]]$metadata.column])
      colnames(design) = gsub("meta.tb[, contrasts.info[[i]]$metadata.column]","",colnames(design), fixed = TRUE)
      colnames(design) = make.names(colnames(design))

      if (include.rep.model == TRUE) {
        ## the replicate is added as a blocking fixed effect (the equivalent of the paired design)
        design.rep = model.matrix(~ 0 + meta.tb[,replicate.column])
        colnames(design.rep) = gsub("meta.tb[, replicate.column]","rep.",colnames(design.rep), fixed = TRUE)
        colnames(design.rep) = make.names(colnames(design.rep))
        design = cbind(design, design.rep[,-1, drop = FALSE])
      }


      ## Define the proteins usable for this contrast
      ## A protein quantified in none of the samples of the two groups compared carries no information on
      ## the contrast: the censored likelihood becomes flat and the model cannot be fitted. These proteins
      ## are excluded from the fit and re-introduced at the end with NA statistics. Proteins detected in
      ## only one of the two groups are instead kept, since that asymmetry is exactly what the
      ## dropout-aware model is meant to describe.
      n.detected.1 = rowSums(!is.na(mat.log2[,contrasts.info[[i]]$group.1, drop = FALSE]))
      n.detected.2 = rowSums(!is.na(mat.log2[,contrasts.info[[i]]$group.2, drop = FALSE]))

      prot.usable = prot.order[n.detected.all >= min.detected & (n.detected.1 + n.detected.2) >= 1]

      if (length(prot.usable) < 2) {
        stop(paste0("Only ", length(prot.usable), " protein(s) are quantified in at least one sample of the contrast '", names(contrasts.info)[i], "': the model cannot be fitted."))
        #return(DEprot.object)
      }

      prot.fit = shuffle.proteins(protein.ids = prot.usable, seed.value = seed)
      mat.fit = mat.log2[prot.fit, , drop = FALSE]
      n.sub = ifelse(is.null(n.subsample), nrow(mat.fit), min(c(round(n.subsample,0), nrow(mat.fit))))


      ## Fit the model (or recover it when the same design has already been fitted on the same proteins for
      ## a previous contrast)
      cache.id = paste0(contrasts.info[[i]]$metadata.column, "|", include.rep.model)
      ## 'vapply' and NOT 'unlist(lapply(...))': on the first contrast the cache is still
      ## empty and the latter would return NULL, which 'which' does not accept
      cache.hit = which(vapply(X = fit.cache,
                               FUN = function(x){identical(x$id, cache.id) & identical(sort(x$prot), sort(prot.fit))},
                               FUN.VALUE = logical(1)))

      if (length(cache.hit) > 0) {
        proda.fit = fit.cache[[cache.hit[1]]]$fit
      } else {
        ## A failure of the optimizer depends on which proteins end up in the subsample used for the
        ## hyper-parameters, therefore a new subsample is drawn before giving up. The last attempt is
        ## performed on all the usable proteins, which is slower but makes the estimation of the priors
        ## independent from the draw.
        proda.fit = NULL
        attempt = 1

        while (is.null(proda.fit) & attempt <= max.attempts) {
          proda.fit =
            tryCatch(expr = proDA::proDA(data = mat.fit,
                                         design = design,
                                         data_is_log_transformed = TRUE,
                                         moderate_location = moderate.location,
                                         moderate_variance = moderate.variance,
                                         n_subsample = n.sub,
                                         max_iter = max.iter,
                                         verbose = verbose),
                     error = function(e){NULL})

          if (is.null(proda.fit)) {
            if (n.sub == nrow(mat.fit)) {
              break
            } else if (attempt < (max.attempts - 1)) {
              prot.fit = shuffle.proteins(protein.ids = prot.usable, seed.value = seed + attempt)
              mat.fit = mat.log2[prot.fit, , drop = FALSE]
            } else {
              n.sub = nrow(mat.fit)
            }
          }

          attempt = attempt + 1
        }

        if (is.null(proda.fit)) {
          stop(paste0("The dropout-aware model could not be fitted for the contrast '", names(contrasts.info)[i], "'.\n",
                      "       Increasing 'min.detected', or removing the samples showing the highest missingness, could help."), call. = FALSE)
          #return(DEprot.object)
        }

        fit.cache[[length(fit.cache) + 1]] = list(id = cache.id, prot = prot.fit, fit = proda.fit)
      }

      n.subsample.used = n.sub


      ## Test the contrast (Wald test on the censored model)
      ## The contrast is built as a numeric vector over the columns of the design and passed through
      ## do.call: proDA captures the 'contrast' argument without evaluating it, and splicing the value
      ## directly into the call avoids any ambiguity in the environment in which it would be looked up.
      proda.contrast.vector = rep(0, ncol(design))
      names(proda.contrast.vector) = colnames(design)
      proda.contrast.vector[make.names(contrasts.info[[i]]$var.1)] = 1
      proda.contrast.vector[make.names(contrasts.info[[i]]$var.2)] = -1

      results.proDA =
        do.call(what = proDA::test_diff,
                args = list(fit = proda.fit,
                            contrast = proda.contrast.vector,
                            pval_adjust_method = ifelse(tolower(padj.method) == "fdrtool", "BH", padj.method),
                            sort_by = NULL))


      ## Model-based (censoring-aware) group means and base mean
      ## The fitted values are the expected abundances of the model, including for the proteins that were
      ## never observed in one of the two groups: their average over the samples of each group is the
      ## quantity consistent with the estimated log2(FoldChange), while the mean of the observed values
      ## would be biased upwards by the missing ones.
      fitted.values = proDA::coefficients(proda.fit) %*% t(design)
      dimnames(fitted.values) = list(rownames(mat.fit), colnames(mat.fit))

      mean.tb =
        data.frame(prot.id = rownames(fitted.values),
                   basemean.log2 = rowMeans(fitted.values[,c(contrasts.info[[i]]$group.1, contrasts.info[[i]]$group.2), drop = FALSE], na.rm = TRUE),
                   log2.mean.group1 = rowMeans(fitted.values[,contrasts.info[[i]]$group.1, drop = FALSE], na.rm = TRUE),
                   log2.mean.group2 = rowMeans(fitted.values[,contrasts.info[[i]]$group.2, drop = FALSE], na.rm = TRUE))


      ## Combine the results keeping one row per protein of the original matrix, in the original order:
      ## the proteins excluded from the fit ('min.detected', or not quantified in any sample of the
      ## contrast) are retained with NA statistics.
      diff.tb =
        data.frame(prot.id = prot.order) %>%
        dplyr::left_join(y = mean.tb, by = "prot.id") %>%
        dplyr::left_join(y = dplyr::select(.data = results.proDA,
                                           prot.id = name,
                                           log2.Fold_group1.vs.group2 = diff,
                                           p.value = pval,
                                           padj = adj_pval,
                                           statistic = t_statistic,
                                           df = df),
                         by = "prot.id")


      ## FDR estimation via fdrtool (Strimmer)
      ## The moderated t-statistics are passed to fdrtool as normal deviates (statistic = "normal"):
      ## fdrtool estimates the proportion of null features and an empirical null, and returns tail-area-based
      ## q-values that are used here as adjusted p-values ('padj'), together with the per-protein local FDR
      ## ('lfdr'). This mirrors the strategy adopted by the DEP package and the one available in
      ## 'diff.analyses.limma'.
      lfdr.values = NULL

      if (tolower(padj.method) == "fdrtool") {
        stat.values = diff.tb$statistic
        finite.idx = which(is.finite(stat.values))

        fdr.fit =
          tryCatch(expr = {
            if (length(finite.idx) < 200) {stop("too_few_features")}
            fdrtool::fdrtool(x = stat.values[finite.idx],
                             statistic = "normal",
                             plot = FALSE,
                             verbose = FALSE)
          },
          error = function(e){NULL})

        if (!is.null(fdr.fit)) {
          diff.tb$padj[finite.idx] = fdr.fit$qval
          lfdr.values = rep(NA, nrow(diff.tb))
          lfdr.values[finite.idx] = fdr.fit$lfdr
        } else {
          ## Not enough features (or degenerate statistic distribution) for a reliable
          ## fdrtool fit: fall back to Benjamini-Hochberg for this contrast.
          warning("fdrtool could not provide a reliable FDR estimation for the contrast '",
                  names(contrasts.info)[i],
                  "' (fewer than 200 proteins with a finite statistic or degenerate distribution): ",
                  "Benjamini-Hochberg correction has been applied instead for this contrast.")
          diff.tb$padj = stats::p.adjust(diff.tb$p.value, method = "BH")
        }
      }


      ## Define signif status
      de.status =
        function(FC, p) {
          ifelse(p < padj.th,
                 yes = ifelse(abs(FC) >= log2(linear.FC.th),
                              yes = ifelse(sign(FC) == 1,
                                           yes = contrasts.info[[i]]$var.1,
                                           no = contrasts.info[[i]]$var.2),
                              no = "null"),
                 no = ifelse(FC >= log2(linear.FC.unresp.range[1]) & FC <= log2(linear.FC.unresp.range[2]),
                             yes = "unresponsive",
                             no = "null"))
        }

      diff.tb$diff.status =
        unlist(purrr::pmap(.l = list(FC = diff.tb$log2.Fold_group1.vs.group2,
                                     p = diff.tb$padj),
                           .f = function(FC,p){de.status(FC,p)}))

      diff.tb =
        diff.tb %>%
        dplyr::mutate(diff.status = factor(diff.status,
                                           levels = c(contrasts.info[[i]]$var.2,
                                                      contrasts.info[[i]]$var.1,
                                                      "unresponsive",
                                                      "null")))

      ## A protein that has been tested but for which the status could not be assigned (for instance an
      ## NA p-value) is 'null'; a protein that has not been tested at all keeps an NA status, so that it is
      ## neither counted among the null ones nor drawn in the plots.
      tested = diff.tb$prot.id %in% results.proDA$name
      diff.tb$diff.status[is.na(diff.tb$diff.status) & tested] = "null"


      ## Compute per-group dispersion (standard deviation and standard error of the mean) and append it,
      ## together with the standard error of the log2 Fold Change, at the end of the table.
      ## Differently from log2.mean/log2.Fold, these values are descriptive and computed on the observed
      ## values only: for a protein with missing values they are estimated on the surviving replicates and
      ## are therefore expected to be under-estimated.
      mat.log2.group1 = mat.log2[,contrasts.info[[i]]$group.1, drop = FALSE]
      mat.log2.group2 = mat.log2[,contrasts.info[[i]]$group.2, drop = FALSE]

      sd.group1 = apply(X = mat.log2.group1, MARGIN = 1, FUN = function(x){sd(x, na.rm = TRUE)})
      sd.group2 = apply(X = mat.log2.group2, MARGIN = 1, FUN = function(x){sd(x, na.rm = TRUE)})

      n.samples.group1 = n.detected.1
      n.samples.group2 = n.detected.2

      sem.group1 = ifelse(n.samples.group1 > 0, sd.group1 / sqrt(n.samples.group1), NA_real_)
      sem.group2 = ifelse(n.samples.group2 > 0, sd.group2 / sqrt(n.samples.group2), NA_real_)

      ## Standard error of the log2 Fold Change: this is the standard error of the contrast estimate of the
      ## censored model, i.e. sqrt(t(contrast) %*% V %*% contrast) where V is the (moderated) variance matrix
      ## of the coefficients. It is the denominator of the t-statistic reported in the 'statistic' column
      ## (statistic = log2(FoldChange)/lfcSE) and the direct equivalent of the 'lfcSE' column returned by
      ## DESeq2::results(). Since the uncertainty on the censored observations is propagated into it, a
      ## protein detected in a minority of the replicates receives a large lfcSE instead of the artificially
      ## small one obtained after imputation.
      lfcSE = results.proDA$se[match(diff.tb$prot.id, results.proDA$name)]

      ## Values are matched on the protein IDs rather than relying on the row order of the table,
      ## which results from a join and could therefore differ from the one of the counts matrix.
      row.idx = match(diff.tb$prot.id, rownames(mat.log2))

      diff.tb$sd.group1 = unname(sd.group1[row.idx])
      diff.tb$sem.group1 = unname(sem.group1[row.idx])
      diff.tb$sd.group2 = unname(sd.group2[row.idx])
      diff.tb$sem.group2 = unname(sem.group2[row.idx])
      diff.tb$lfcSE = unname(lfcSE)

      ## Number of samples in which the protein was actually quantified in each group: it is the direct
      ## readout of how much of the fold change comes from measured values rather than from the model.
      ## 'n.approx' is instead the effective sample size estimated over all the samples of the model.
      diff.tb$n.detected.group1 = unname(n.samples.group1[row.idx])
      diff.tb$n.detected.group2 = unname(n.samples.group2[row.idx])
      diff.tb$n.approx = results.proDA$n_approx[match(diff.tb$prot.id, results.proDA$name)]

      if (!is.null(lfdr.values)) {
        diff.tb$lfdr = lfdr.values
      }


      ## Table restricted to the proteins actually tested in this contrast: it is the one used for the
      ## counts and the plots, so that the untested proteins do not appear as an extra (NA) category.
      diff.tb.tested = dplyr::filter(.data = diff.tb, !is.na(diff.status))


      ## Run PCA
      PCA.data = DEprot::perform.PCA(DEprot.object = DEprot.object,
                                     sample.subset = c(contrasts.info[[i]]$group.1, contrasts.info[[i]]$group.2),
                                     which.data = which.data)

      scatter.PC1.2 = DEprot::plot.PC.scatter(DEprot.PCA.object = PCA.data, PC.x = 1, PC.y = 2, color.column = contrasts.info[[i]]$metadata.column, shape.column = switch(isTRUE(include.rep.model)+1, NULL, replicate.column)) + theme(legend.position = "none")
      if (length(unique(sign(PCA.data@PCs$PC1))) > 1){scatter.PC1.2 + geom_vline(xintercept = 0, colour = "gray", linetype = 2)}
      scatter.PC2.3 = DEprot::plot.PC.scatter(DEprot.PCA.object = PCA.data, PC.x = 3, PC.y = 2, color.column = contrasts.info[[i]]$metadata.column, shape.column = switch(isTRUE(include.rep.model)+1, NULL, replicate.column))


      ## Run Correlations
      corr.data.pearson = DEprot::plot.correlation.heatmap(DEprot.object = DEprot.object,
                                                           correlation.method = "pearson",
                                                           sample.subset = c(contrasts.info[[i]]$group.1, contrasts.info[[i]]$group.2),
                                                           which.data = which.data,
                                                           correlation.scale.limits = c(NA,1))

      corr.data.spearman = DEprot::plot.correlation.heatmap(DEprot.object = DEprot.object,
                                                            correlation.method = "spearman",
                                                            sample.subset = c(contrasts.info[[i]]$group.1, contrasts.info[[i]]$group.2),
                                                            which.data = which.data,
                                                            correlation.scale.limits = c(NA,1))



      ## Define params and counts
      colors.plots = c(up.color, down.color, null.color, unresponsive.color)
      names(colors.plots) = c(contrasts.info[[i]]$var.1, contrasts.info[[i]]$var.2, "null", "unresponsive")


      ### Summarize the number of diff proteins
      n.diff =
        data.frame(diff.tb.tested %>%
                     dplyr::group_by(diff.status, .drop = FALSE) %>%
                     dplyr::summarise(n = n(),
                                      median.FoldChange = median(log2.Fold_group1.vs.group2, na.rm = TRUE)))


      ## Make volcano plot
      volcano =
        ggplot(diff.tb.tested,
               aes(x = log2.Fold_group1.vs.group2,
                   y = -log10(padj),
                   color = diff.status)) +
        geom_point(stroke = NA,
                   alpha = 0.5,
                   size = 2) +
        scale_color_manual(values = colors.plots,
                           name = "Differential\nstatus",
                           drop = FALSE) +
        geom_hline(yintercept = -log10(padj.th), linetype = 2, color = "gray40") +
        geom_vline(xintercept = c(-1,1)*log2(linear.FC.th), linetype = 2, color = "gray40") +
        ylab("-log<sub>10</sub>(*P<sub>adj</sub>*)") +
        xlab(paste0("log<sub>2</sub>(Fold Change<sub>",contrasts.info[[i]]$var.1,"</sup>&frasl;<sub>",contrasts.info[[i]]$var.2,"</sub></sub>)")) +
        ggtitle(paste0("**",contrasts.info[[i]]$var.1, "** *vs* **", contrasts.info[[i]]$var.2, "**")) +
        guides(color = guide_legend(override.aes = list(size = 3))) +
        theme_classic() +
        theme(axis.text.x.bottom = ggtext::element_markdown(color = "black"),
              axis.text.y.left = ggtext::element_markdown(color = "black"),
              axis.title.x = ggtext::element_markdown(color = "black"),
              axis.title.y = ggtext::element_markdown(color = "black"),
              axis.ticks = element_line(color = "black"),
              plot.title = ggtext::element_markdown(color = "black", hjust = 0.5),
              aspect.ratio = 1)

      x.max = max(abs(ggplot_build(volcano)$layout$panel_params[[1]]$x.range))

      volcano =
        volcano +
        xlim(c(-1,1)*x.max) +
        annotate(geom = "text",
                 x = -Inf, y = +Inf,
                 color = colors.plots[2],
                 hjust = -0.2, vjust = 1.5,
                 label = paste0("n = ",n.diff[n.diff$diff.status == contrasts.info[[i]]$var.2,"n"])) +
        annotate(geom = "text",
                 x = +Inf, y = +Inf,
                 hjust = 1.2, vjust = 1.5,
                 color = colors.plots[1],
                 label = paste0("n = ",n.diff[n.diff$diff.status == contrasts.info[[i]]$var.1,"n"]))



      ## Make MA-plot
      ma.plot =
        ggplot() +
        stat_density_2d(data = diff.tb.tested,
                        aes(x = basemean.log2,
                            y = log2.Fold_group1.vs.group2,
                            fill = after_stat(count)),
                        geom = "raster",
                        contour = FALSE,
                        show.legend = TRUE,
                        n = 200,
                        adjust = 5) +
        scale_fill_gradientn(colours = colorRampPalette(colors = RColorBrewer::brewer.pal(9, "Blues"))(101),
                             name = "Count")


      if (sum((n.diff %>% dplyr::filter(!(diff.status %in% c("unresponsive", "null"))))$n, na.rm = TRUE) > 0) {
        ma.plot =
          ma.plot +
          geom_point(data = dplyr::filter(diff.tb.tested, diff.status %in% c(contrasts.info[[i]]$var.1,contrasts.info[[i]]$var.2)),
                     mapping = aes(x = basemean.log2,
                                   y = log2.Fold_group1.vs.group2,
                                   color = diff.status),
                     alpha = 0.5,
                     size = 2,
                     stroke = NA,
                     show.legend = TRUE,
                     inherit.aes = FALSE) +
          scale_color_manual(values = colors.plots, name = "Differential\nstatus", drop = FALSE)
      }

      ma.plot =
        ma.plot +
        geom_hline(yintercept = c(-1,1)*log2(linear.FC.th), linetype = 2, color = "gray40") +
        geom_hline(yintercept = 0, linetype = 1, color = "steelblue") +
        theme_classic() +
        xlab("log<sub>2</sub>(Base Mean)") +
        ylab(paste0("log<sub>2</sub>(Fold Change<sub>",contrasts.info[[i]]$var.1,"</sup>&frasl;<sub>",contrasts.info[[i]]$var.2,"</sub></sub>)")) +
        ggtitle(paste0("**",contrasts.info[[i]]$var.1, "** *vs* **", contrasts.info[[i]]$var.2, "**")) +
        scale_x_continuous(expand = c(0,0)) +
        annotate(geom = "text",
                 x = -Inf, y = -Inf,
                 color = colors.plots[2],
                 hjust = -0.2, vjust = -0.5,
                 label = paste0("n = ",n.diff[n.diff$diff.status == contrasts.info[[i]]$var.2,"n"])) +
        annotate(geom = "text",
                 x = -Inf, y = +Inf,
                 hjust = -0.2, vjust = 1.5,
                 color = colors.plots[1],
                 label = paste0("n = ",n.diff[n.diff$diff.status == contrasts.info[[i]]$var.1,"n"])) +
        theme(axis.ticks = element_line(color = "black"),
              axis.text = element_text(color = "black"),
              axis.title.x = ggtext::element_markdown(color = "black"),
              axis.title.y = ggtext::element_markdown(color = "black"),
              plot.title = ggtext::element_markdown(color = "black", hjust = 0.5),
              aspect.ratio = 0.6)

      y.max = max(abs(ggplot_build(ma.plot)$layout$panel_params[[1]]$y.range))
      ma.plot = ma.plot + scale_y_continuous(expand = c(0,0), limits = c(-1,1)*y.max)



      ## Collect the dropout curves estimated by the model
      ## 'position' is the intensity at which a sample has 50% probability of detecting a protein, i.e. the
      ## per-sample equivalent of the LOD50 returned by 'missingness.diagnostic'; 'scale' describes how
      ## sharp the transition between detection and dropout is.
      dropout.curves =
        data.frame(sample.id = colnames(mat.fit),
                   position = proDA::hyper_parameters(proda.fit)$dropout_curve_position,
                   scale = proDA::hyper_parameters(proda.fit)$dropout_curve_scale)


      ### rename columns
      colnames(diff.tb) = gsub("group1", contrasts.info[[i]]$var.1, colnames(diff.tb))
      colnames(diff.tb) = gsub("group2", contrasts.info[[i]]$var.2, colnames(diff.tb))
      colnames(n.diff) = gsub("group1", contrasts.info[[i]]$var.1, colnames(n.diff))
      colnames(n.diff) = gsub("group2", contrasts.info[[i]]$var.2, colnames(n.diff))


      ### Build list
      diff.analyses.list[[i]] = list(results = diff.tb,
                                     n.diff =  n.diff,
                                     PCA.data = PCA.data,
                                     PCA.plots = (scatter.PC1.2 | scatter.PC2.3) / PCA.data@cumulative.PC.plot,
                                     correlations = corr.data.pearson@heatmap | corr.data.spearman@heatmap,
                                     volcano = volcano,
                                     MA.plot = ma.plot,
                                     statistic.distribution = DEprot::identify.distribution(diff.tb$statistic),
                                     proDA.fit = list(fit = proda.fit,
                                                      design = design,
                                                      contrast = proda.contrast.vector,
                                                      dropout.curves = dropout.curves,
                                                      n.proteins.fitted = length(prot.fit),
                                                      full.results = results.proDA))

      pb$tick()
    } #END diff analyses

    names(diff.analyses.list) = names(contrasts.info)


    ### Make DEprot.analyses object
    DEprot.object.analyses =
      new(Class = "DEprot.analyses",
          metadata = DEprot.object@metadata,
          protein.info = .get.protein.info(DEprot.object),
          raw.counts = DEprot.object@raw.counts,
          norm.counts =  DEprot.object@norm.counts,
          random.counts =  DEprot.object@random.counts,
          imputed.counts = DEprot.object@imputed.counts,
          log.base = DEprot.object@log.base,
          log.transformed = DEprot.object@log.transformed,
          imputed = DEprot.object@imputed,
          imputation.method = DEprot.object@imputation.method,
          normalized = DEprot.object@normalized,
          normalization.method = DEprot.object@normalization.method,
          randomized = DEprot.object@randomized,
          randomization.method = DEprot.object@randomization.method,
          boxplot.raw = DEprot.object@boxplot.raw,
          boxplot.norm = DEprot.object@boxplot.norm,
          boxplot.random = DEprot.object@boxplot.random,
          boxplot.imputed = DEprot.object@boxplot.imputed,
          analyses.result.list = diff.analyses.list,
          contrasts = contrasts.info,
          differential.analyses.params = list(linear.FC.th = linear.FC.th,
                                              linear.FC.unresp.range = linear.FC.unresp.range,
                                              padj.th = padj.th,
                                              padj.method = padj.method,
                                              counts.used = data.used,
                                              stat.test = "proDA",
                                              rep.model = include.rep.model,
                                              replicate.column = replicate.column,
                                              moderate.location = moderate.location,
                                              moderate.variance = moderate.variance,
                                              min.detected = min.detected,
                                              n.subsample = n.subsample.used,
                                              max.iter = max.iter,
                                              max.attempts = max.attempts,
                                              n.proteins.fitted = unlist(lapply(X = diff.analyses.list, FUN = function(x){x$proDA.fit$n.proteins.fitted})),
                                              missingness.stats = missingness.stats,
                                              seed = seed))

    return(DEprot.object.analyses)
  } # END function
