#' @title generate.mm
#'
#' @description Drafts the Material-and-Methods paragraph describing the analyses stored in a
#' \code{DEprot} or \code{DEprot.analyses} object. All the steps that left a trace in the object are
#' described in the order in which they were applied (normalization or batch correction,
#' bottom-distribution randomization, imputation, differential analyses and, when the corresponding
#' object is provided, geneset enrichment), together with the parameters that affect the results and
#' would be needed to reproduce them. Tools are cited with numbers in the text and the reference list
#' is printed underneath.
#'
#' The paragraph is a draft: the numbers and the parameters are read from the object, but the wording
#' is expected to be adapted to the study and to the style of the journal. Steps that happen upstream
#' of \code{DEprot} (sample preparation, LC-MS/MS acquisition, database search) are not stored in the
#' object; the search engine can be mentioned through \code{quantification.software}, everything else
#' must be added by hand.
#'
#' @param DEprot.object An object of class \code{DEprot} or \code{DEprot.analyses}.
#' @param enrichment.object An object of class \code{DEprot.enrichResult}, as generated by \link{geneset.enrichment}, to describe the enrichment analyses as well. Default: \code{NULL} (no enrichment paragraph).
#' @param quantification.software String naming the software used to generate the protein intensities, version included (e.g., \code{"MaxQuant (v2.4.2)"}). Default: \code{NULL}, in which case the sentence is left generic.
#' @param quantification.reference String with the citation of \code{quantification.software}. When provided, it is cited in the text and becomes the first entry of the reference list. Default: \code{NULL}.
#' @param geneset.database String naming the geneset collection used for the enrichment (e.g., \code{"CORUM v5.0"}, \code{"MSigDB Hallmark"}). Ignored when \code{enrichment.object} is \code{NULL}. Default: \code{NULL}.
#' @param geneset.reference String with the citation of \code{geneset.database}. Default: \code{NULL}.
#' @param contrasts Numeric vector indicating which contrasts should be described. Default: \code{NULL} (all the contrasts available in the object).
#' @param include.results.summary Logical value defining whether the number of differential proteins per contrast should be reported. Default: \code{TRUE}.
#' @param include.package.versions Logical value defining whether the version of the packages installed in the current session should be appended to the corresponding references. Default: \code{TRUE}.
#' @param extra.references String vector of citations to append, unnumbered in the text, at the end of the reference list. Default: \code{NULL}.
#' @param add.headers Logical value defining whether the 'Material and Methods' and 'References' headers should be added. Default: \code{TRUE}.
#' @param wrap.width Numeric value indicating the number of characters per line used to wrap the text. Set to \code{NULL} to keep each paragraph on a single line (useful when pasting into a word processor). Default: \code{100}.
#' @param output.file String with the path of a text file in which the result should be written. Default: \code{NULL} (no file written).
#' @param verbose Logical value defining whether the text should be printed in the console. Default: \code{TRUE}.
#'
#' @return Invisibly, a list containing:
#'      \describe{
#'        \item{\code{text}: }{string with the numbered Material-and-Methods paragraphs}
#'        \item{\code{references}: }{data.frame with the number, the key and the citation of each reference}
#'        \item{\code{parameters}: }{data.frame collecting the parameters mentioned in the text}
#'        \item{\code{full.text}: }{string combining text and reference list, as printed and as written in \code{output.file}}}
#'
#' @seealso \link{export.report}, \link{impute.counts}, \link{diff.analyses}, \link{geneset.enrichment}
#'
#' @author Sebastian Gregoricchio
#'
#' @examples
#' # Draft for a differential analysis
#' mm <- generate.mm(DEprot.object = DEprot::test.toolbox$diff.exp.limma)
#'
#' # Same, mentioning the search engine and writing the text to a file
#' \dontrun{
#' mm <- generate.mm(DEprot.object = DEprot::test.toolbox$diff.exp.limma,
#'                   quantification.software = "MaxQuant (v2.4.2)",
#'                   quantification.reference = paste0("Cox J., Mann M. MaxQuant enables high peptide ",
#'                                                     "identification rates. Nature Biotechnology 26, ",
#'                                                     "1367-1372, 2008. doi: 10.1038/nbt.1511"),
#'                   output.file = "material.and.methods.txt")
#' }
#'
#' @importFrom utils packageVersion
#'
#' @export generate.mm


generate.mm =
  function(DEprot.object,
           enrichment.object = NULL,
           quantification.software = NULL,
           quantification.reference = NULL,
           geneset.database = NULL,
           geneset.reference = NULL,
           contrasts = NULL,
           include.results.summary = TRUE,
           include.package.versions = TRUE,
           extra.references = NULL,
           add.headers = TRUE,
           wrap.width = 100,
           output.file = NULL,
           verbose = TRUE) {

    ### check object
    if (!any(c("DEprot", "DEprot.analyses") %in% class(DEprot.object))) {
      stop("The input must be an object of class 'DEprot' or 'DEprot.analyses'.")
    }

    if (!is.null(enrichment.object)) {
      if (!("DEprot.enrichResult" %in% class(enrichment.object))) {
        stop("The 'enrichment.object' must be an object of class 'DEprot.enrichResult'.")
      }
    }



    #############################################################################################
    ### Bibliography
    #############################################################################################

    ## 'key' is the placeholder used in the draft text, 'package' is used to append the version of
    ## the package installed in the current session (NA when the citation is not tied to a package)
    reference.database =
      data.frame(
        key = c("DEprot", "DEprot.zenodo", "R", "MBQN", "HarmonizR", "ComBat", "missForest", "VIM",
                "imputomics", "pcaMethods", "LLS", "SVDimpute", "BPCA", "PPCA", "DreamAI", "limma",
                "prolfqua", "proDA", "BH", "fdrtool", "clusterProfiler", "GSEA", "aPEAR"),
        package = c("DEprot", "DEprot", NA, "MBQN", "HarmonizR", NA, "missForest", "VIM",
                    NA, "pcaMethods", NA, NA, NA, NA, NA, "limma",
                    "prolfqua", "proDA", NA, "fdrtool", "clusterProfiler", NA, "aPEAR"),
        citation = c(
          "Eickhoff N., Hoekman L., Bleijerveld O., Bergman A.M., Zwart W., Gregoricchio S. DEprot: a comprehensive R-package for the analyses of label-free quantitation mass-spectrometry data. NAR Genomics and Bioinformatics 8(1), 2026. doi: 10.1093/nargab/lqag015",
          "Gregoricchio S. sebastian-gregoricchio/DEprot. Zenodo. doi: 10.5281/zenodo.18233890",
          "R Core Team. R: a language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. https://www.R-project.org/",
          "Brombacher E., Schad A., Kreutz C. Tail-robust quantile normalization. Proteomics 20(24), 2000068, 2020. doi: 10.1002/pmic.202000068",
          "Voss H., Schlumbohm S., Barwikowski P., Wurlitzer M., Dottermusch M., Neumann P., Schluter H., Neumann J.E., Krisp C. HarmonizR enables data harmonization across independent proteomic datasets with appropriate handling of missing values. Nature Communications 13, 3523, 2022. doi: 10.1038/s41467-022-31007-x",
          "Johnson W.E., Li C., Rabinovic A. Adjusting batch effects in microarray expression data using empirical Bayes methods. Biostatistics 8(1), 118-127, 2007. doi: 10.1093/biostatistics/kxj037",
          "Stekhoven D.J., Buhlmann P. MissForest: non-parametric missing value imputation for mixed-type data. Bioinformatics 28(1), 112-118, 2012. doi: 10.1093/bioinformatics/btr597",
          "Kowarik A., Templ M. Imputation with the R package VIM. Journal of Statistical Software 74(7), 1-16, 2016. doi: 10.18637/jss.v074.i07",
          "Chilimoniuk J., Grzesiak K., Kala J., Nowakowski D., Kretowski A., Kolenda R., Ciborowski M., Burdukiewicz M. imputomics: web server and R package for missing values imputation in metabolomics data. Bioinformatics 40(2), btae098, 2024. doi: 10.1093/bioinformatics/btae098",
          "Stacklies W., Redestig H., Scholz M., Walther D., Selbig J. pcaMethods: a Bioconductor package providing PCA methods for incomplete data. Bioinformatics 23(9), 1164-1167, 2007. doi: 10.1093/bioinformatics/btm069",
          "Kim H., Golub G.H., Park H. Missing value estimation for DNA microarray gene expression data: local least squares imputation. Bioinformatics 21(2), 187-198, 2005. doi: 10.1093/bioinformatics/bth499",
          "Troyanskaya O., Cantor M., Sherlock G., Brown P., Hastie T., Tibshirani R., Botstein D., Altman R.B. Missing value estimation methods for DNA microarrays. Bioinformatics 17(6), 520-525, 2001. doi: 10.1093/bioinformatics/17.6.520",
          "Oba S., Sato M., Takemasa I., Monden M., Matsubara K., Ishii S. A Bayesian missing value estimation method for gene expression profile data. Bioinformatics 19(16), 2088-2096, 2003. doi: 10.1093/bioinformatics/btg287",
          "Roweis S. EM algorithms for PCA and SPCA. Advances in Neural Information Processing Systems 10, 626-632, 1998.",
          "Ma W., Kim S., Chowdhury S., Li Z., Yang M., Yoo S., Petralia F., Jacobsen J., Li J.J., Ge X., Li K., Yu T., Calinawan A.P., Edwards N., Payne S.H., Boutros P.C., Rodriguez H., Stolovitzky G., Zhu J., Kang J., Fenyo D., Saez-Rodriguez J., Wang P. DreamAI: algorithm for the imputation of proteomics data. bioRxiv, 2021. doi: 10.1101/2020.07.21.214205",
          "Ritchie M.E., Phipson B., Wu D., Hu Y., Law C.W., Shi W., Smyth G.K. limma powers differential expression analyses for RNA-sequencing and microarray studies. Nucleic Acids Research 43(7), e47, 2015. doi: 10.1093/nar/gkv007",
          "Wolski W.E., Nanni P., Grossmann J., d'Errico M., Schlapbach R., Panse C. prolfqua: a comprehensive R-package for proteomics differential expression analysis. Journal of Proteome Research 22(4), 1092-1104, 2023. doi: 10.1021/acs.jproteome.2c00441",
          "Ahlmann-Eltze C., Anders S. proDA: probabilistic dropout analysis for identifying differentially abundant proteins in label-free mass spectrometry. bioRxiv, 2020. doi: 10.1101/661496",
          "Benjamini Y., Hochberg Y. Controlling the false discovery rate: a practical and powerful approach to multiple testing. Journal of the Royal Statistical Society B 57(1), 289-300, 1995.",
          "Strimmer K. fdrtool: a versatile R package for estimating local and tail area-based false discovery rates. Bioinformatics 24(12), 1461-1462, 2008. doi: 10.1093/bioinformatics/btn209",
          "Wu T., Hu E., Xu S., Chen M., Guo P., Dai Z., Feng T., Zhou L., Tang W., Zhan L., Fu X., Liu S., Bo X., Yu G. clusterProfiler 4.0: a universal enrichment tool for interpreting omics data. The Innovation 2(3), 100141, 2021. doi: 10.1016/j.xinn.2021.100141",
          "Subramanian A., Tamayo P., Mootha V.K., Mukherjee S., Ebert B.L., Gillette M.A., Paulovich A., Pomeroy S.L., Golub T.R., Lander E.S., Mesirov J.P. Gene set enrichment analysis: a knowledge-based approach for interpreting genome-wide expression profiles. PNAS 102(43), 15545-15550, 2005. doi: 10.1073/pnas.0506580102",
          "Kerseviciute I., Gordevicius J. aPEAR: an R package for autonomous visualisation of pathway enrichment networks. Bioinformatics 39(11), btad672, 2023. doi: 10.1093/bioinformatics/btad672"),
        stringsAsFactors = FALSE)


    ## citations provided by the user enter the same database and get numbered like the others
    if (!is.null(quantification.reference)) {
      reference.database = rbind(data.frame(key = "quantification.software",
                                            package = NA,
                                            citation = as.character(quantification.reference)[1],
                                            stringsAsFactors = FALSE),
                                 reference.database)
    }

    if (!is.null(geneset.reference)) {
      reference.database = rbind(reference.database,
                                 data.frame(key = "geneset.database",
                                            package = NA,
                                            citation = as.character(geneset.reference)[1],
                                            stringsAsFactors = FALSE))
    }



    #############################################################################################
    ### Internal helpers
    #############################################################################################

    ## reads a single parameter from the slots in which DEprot stores the settings: these are either
    ## param/value data.frames (normalization) or named lists (randomization, imputation, analyses)
    get.param <-
      function(x,
               name,
               default = NA) {

        if (is.data.frame(x)) {
          if (all(c("param", "value") %in% colnames(x))) {
            value = x$value[as.character(x$param) == name]
            if (length(value) > 0) {
              return(as.character(value)[1])
            }
          }
        } else if (is.list(x)) {
          if (name %in% names(x)) {
            return(x[[name]])
          }
        }

        return(default)
      }


    ## formats numbers for the text. 'digits' counts decimals and not significant digits:
    ## significant digits would turn a long seed or a large protein count into a rounded and
    ## therefore useless number. Whole numbers are printed as such, trailing zeros are dropped
    ## and values too small for the fixed notation fall back to the scientific one
    number.to.text <-
      function(x,
               digits = 3) {

        if (is.null(x)) {return(NA_character_)}
        if (length(x) == 0) {return(NA_character_)}

        x = suppressWarnings(as.numeric(x[1]))
        if (is.na(x)) {return(NA_character_)}

        if (isTRUE(x == round(x)) & abs(x) < 1e15) {
          return(sprintf("%.0f", x))
        }

        if (abs(x) < 10^(-digits)) {
          return(format(signif(x, digits), trim = TRUE, scientific = TRUE))
        }

        return(sub("\\.$", "", sub("0+$", "", formatC(x, format = "f", digits = digits))))
      }


    ## turns a vector of citation numbers into the compact form used in the text: runs of three or
    ## more consecutive numbers become ranges (e.g., '1,3-6')
    collapse.numbers <-
      function(n) {

        n = sort(unique(as.numeric(n)))

        if (length(n) == 1) {
          return(as.character(n))
        }

        cut.points = c(0, which(diff(n) != 1), length(n))
        runs = lapply(1:(length(cut.points) - 1),
                      function(i) {n[(cut.points[i] + 1):cut.points[i + 1]]})

        collapsed = sapply(runs,
                           function(r) {
                             if (length(r) >= 3) {
                               paste0(r[1], "-", r[length(r)])
                             } else {
                               paste(r, collapse = ",")
                             }
                           })

        return(paste(collapsed, collapse = ","))
      }


    ## replaces the placeholders of the draft text ('[[key]]') with the citation numbers, assigned in
    ## order of first appearance, and returns the matching reference list
    number.citations <-
      function(text) {

        single.pattern = "\\[\\[[^]]+\\]\\]"
        group.pattern = paste0("(", single.pattern, ")+")

        keys = gsub("^\\[\\[|\\]\\]$", "", unlist(regmatches(text, gregexpr(single.pattern, text))))
        key.order = unique(keys)

        if (length(key.order) == 0) {
          return(list(text = text,
                      references = data.frame(n = integer(0),
                                              key = character(0),
                                              citation = character(0),
                                              stringsAsFactors = FALSE)))
        }

        ## consecutive placeholders are merged in a single bracket, e.g. '(1,2)'
        positions = gregexpr(group.pattern, text)
        regmatches(text, positions) =
          lapply(regmatches(text, positions),
                 function(group) {
                   sapply(group,
                          function(g) {
                            g.keys = gsub("^\\[\\[|\\]\\]$", "",
                                          unlist(regmatches(g, gregexpr(single.pattern, g))))
                            paste0(" (", collapse.numbers(match(g.keys, key.order)), ")")
                          })
                 })

        references = data.frame(n = 1:length(key.order),
                                key = key.order,
                                citation = reference.database$citation[match(key.order, reference.database$key)],
                                stringsAsFactors = FALSE)

        ## a key without citation means that the draft text and the database went out of sync
        if (any(is.na(references$citation))) {
          warning(paste0("No citation available for: ",
                         paste(references$key[is.na(references$citation)], collapse = ", "), "."))
          references$citation[is.na(references$citation)] = "<<missing reference>>"
        }

        return(list(text = text,
                    references = references))
      }


    ## wrapping is applied paragraph by paragraph to keep the empty lines in between
    wrap.text <-
      function(x) {

        if (is.null(wrap.width)) {return(x)}

        paste(sapply(unlist(strsplit(x, "\n\n", fixed = TRUE)),
                     function(p) {paste(strwrap(p, width = wrap.width), collapse = "\n")}),
              collapse = "\n\n")
      }


    ### Collect the parameters reported in the text, filled while the paragraphs are built
    parameters = data.frame(step = character(0),
                            param = character(0),
                            value = character(0),
                            stringsAsFactors = FALSE)

    add.param <-
      function(step,
               param,
               value) {

        if (is.null(value)) {return(invisible(NULL))}
        if (length(value) == 0) {return(invisible(NULL))}

        parameters <<- rbind(parameters,
                             data.frame(step = step,
                                        param = param,
                                        value = paste(as.character(value), collapse = ", "),
                                        stringsAsFactors = FALSE))
      }



    #############################################################################################
    ### Dataset and software
    #############################################################################################

    ## all the counts tables share the same dimensions: the first available one is enough
    count.slots = c("raw.counts", "norm.counts", "random.counts", "imputed.counts")
    available.counts = count.slots[sapply(count.slots,
                                          function(s) {!is.null(methods::slot(DEprot.object, s))})]
    counts = if (length(available.counts) > 0) {methods::slot(DEprot.object, available.counts[1])} else {NULL}

    n.proteins = if (is.null(counts)) {NA} else {nrow(counts)}
    n.samples = if (is.null(counts)) {NA} else {ncol(counts)}

    log.base = DEprot.object@log.base
    log.text = if (is.null(log.base)) {
      "log-transformed"
    } else if (is.na(log.base)) {
      "expressed in linear scale"
    } else if (log.base == exp(1)) {
      "ln-transformed"
    } else {
      paste0("log", log.base, "-transformed")
    }

    R.version.text = paste0(R.version$major, ".", R.version$minor)
    DEprot.version.text = as.character(tryCatch(utils::packageVersion("DEprot"),
                                                error = function(e) {NA}))

    add.param(step = "dataset", param = "proteins", value = n.proteins)
    add.param(step = "dataset", param = "samples", value = n.samples)
    add.param(step = "dataset", param = "R version", value = R.version.text)
    add.param(step = "dataset", param = "DEprot version", value = DEprot.version.text)

    intro.text =
      paste0("Protein-level label-free quantification (LFQ) intensities",
             ifelse(is.null(quantification.software),
                    yes = "",
                    no = paste0(" obtained with ", quantification.software,
                                ifelse(is.null(quantification.reference),
                                       yes = "", no = "[[quantification.software]]"))),
             " were processed in R (v", R.version.text, ")[[R]] with the DEprot package",
             ifelse(is.na(DEprot.version.text), yes = "", no = paste0(" (v", DEprot.version.text, ")")),
             "[[DEprot]][[DEprot.zenodo]]. ",
             "The matrix used for the analyses covers ", n.proteins, " proteins across ",
             n.samples, " samples and the intensities are ", log.text, ".")

    ## the metadata columns are the only trace of the experimental design in the object
    metadata.columns = setdiff(colnames(DEprot.object@metadata), "column.id")
    if (length(metadata.columns) > 0) {
      intro.text = paste0(intro.text,
                          " Samples are annotated by the following variables: ",
                          paste(metadata.columns, collapse = ", "), ".")
    }



    #############################################################################################
    ### Normalization and batch correction
    #############################################################################################

    normalization.text = NULL

    if (isTRUE(DEprot.object@normalized)) {
      normalization = DEprot.object@normalization.method
      normalization.package = get.param(normalization, "package")

      if (!is.na(normalization.package) & identical(as.character(normalization.package), "MBQN")) {
        balancing.function = get.param(normalization, "function")
        NRI.RI.threshold = get.param(normalization, "NRI/RI ratio threshold")

        add.param(step = "normalization", param = "method", value = "MBQN quantile normalization")
        add.param(step = "normalization", param = "balancing function", value = balancing.function)
        add.param(step = "normalization", param = "NRI/RI ratio threshold", value = NRI.RI.threshold)

        normalization.text =
          paste0("Intensities were normalized across samples by mean/median-balanced quantile ",
                 "normalization (MBQN)[[MBQN]], an implementation of quantile normalization in which ",
                 "rank-invariant and nearly rank-invariant features are centred before the ",
                 "normalization, so that their profile is not flattened. ",
                 ifelse(is.na(balancing.function),
                        yes = "No balancing function was applied. ",
                        no = paste0("Features were balanced on their ", balancing.function, " and ")),
                 ifelse(is.na(NRI.RI.threshold),
                        yes = "",
                        no = paste0("the rank-invariance frequency threshold above which the ",
                                    "balancing is applied was set to ", NRI.RI.threshold, ".")))

      } else if (!is.na(normalization.package) & identical(as.character(normalization.package), "HarmonizR")) {
        batch.column = get.param(normalization, "batch.column")
        algorithm = get.param(normalization, "algorithm")
        ComBat.mode = get.param(normalization, "ComBat.mode")
        block = get.param(normalization, "block")

        add.param(step = "batch correction", param = "batch column", value = batch.column)
        add.param(step = "batch correction", param = "algorithm", value = algorithm)
        add.param(step = "batch correction", param = "ComBat mode", value = ComBat.mode)
        add.param(step = "batch correction", param = "block", value = block)

        normalization.text =
          paste0("Batch effects associated with the '", batch.column, "' variable were removed with ",
                 "HarmonizR[[HarmonizR]], which splits the matrix into blocks that are free of ",
                 "missing values, corrects each of them and reassembles the result, avoiding both ",
                 "the loss of proteins and the imputation of values before the correction. ",
                 ifelse(tolower(as.character(algorithm)) == "limma",
                        yes = "Correction was performed with the limma implementation[[limma]]. ",
                        no = paste0("Correction was performed with ComBat[[ComBat]] (mode ",
                                    ComBat.mode, "). ")),
                 ifelse(identical(as.character(block), "null"),
                        yes = "", no = paste0("Blocking was defined by the '", block, "' variable. ")))

      } else if (is.character(normalization) & length(normalization) == 1) {
        add.param(step = "normalization", param = "method", value = normalization)

        normalization.text =
          paste0("Intensities were used as normalized upstream by ", normalization,
                 ", without further normalization in R.")

      } else {
        normalization.text = "Intensities were normalized before the analyses."
      }

    } else {
      normalization.text = "No normalization was applied to the intensities."
    }



    #############################################################################################
    ### Bottom-distribution randomization
    #############################################################################################

    randomization.text = NULL

    if (isTRUE(DEprot.object@randomized)) {
      randomization = DEprot.object@randomization.method
      group.column = get.param(randomization, "group.column")
      percentage.missing = get.param(randomization, "percentage.missing")
      tail.percentage = get.param(randomization, "tail.percentage")
      randomization.data = get.param(randomization, "data.used")
      randomization.seed = suppressWarnings(trunc(as.numeric(get.param(randomization, "seed"))))

      add.param(step = "randomization", param = "group column", value = group.column)
      add.param(step = "randomization", param = "minimum missingness per group (%)", value = percentage.missing)
      add.param(step = "randomization", param = "sampled tail (%)", value = tail.percentage)
      add.param(step = "randomization", param = "counts used", value = randomization.data)
      add.param(step = "randomization", param = "seed", value = randomization.seed)

      ## objects imported from other tools can be flagged as randomized without carrying the
      ## settings: in that case the sentence stays generic instead of printing NA
      randomization.text =
        if (is.na(group.column) | is.na(number.to.text(tail.percentage))) {
          paste0("Proteins missing in a whole condition were assigned random values drawn from ",
                 "the bottom of the intensity distribution of each sample, so that they are not ",
                 "treated as missing at random by the imputation.")
        } else {
          paste0(ifelse(identical(number.to.text(percentage.missing), "100"),
                        yes = paste0("Proteins undetected in all the samples of a given '"),
                        no = paste0("Proteins missing in at least ", number.to.text(percentage.missing),
                                    "% of the samples of a given '")),
                 group.column, "' group were treated as missing not at random: for those ",
                 "groups, values were drawn at random from the bottom ", number.to.text(tail.percentage),
                 "% of the intensity distribution of each sample",
                 ifelse(is.na(number.to.text(randomization.seed)),
                        yes = "", no = paste0(" (random seed ", number.to.text(randomization.seed), ")")),
                 ". This step keeps the difference between a protein that is absent in one condition ",
                 "and a protein that was simply not detected, which the imputation would otherwise ",
                 "blur.")
        }
    }



    #############################################################################################
    ### Imputation
    #############################################################################################

    imputation.text = NULL

    if (isTRUE(DEprot.object@imputed)) {
      imputation = DEprot.object@imputation.method
      imputation.method = as.character(get.param(imputation, "method", default = "unknown"))
      imputation.data = get.param(imputation, "data.used")
      imputation.seed = suppressWarnings(trunc(as.numeric(get.param(imputation, "seed"))))

      add.param(step = "imputation", param = "method", value = imputation.method)
      add.param(step = "imputation", param = "counts used", value = imputation.data)
      add.param(step = "imputation", param = "seed", value = imputation.seed)

      method.text =
        switch(tolower(imputation.method),

               "missforest" = {
                 max.iterations = get.param(imputation, "max.iterations")
                 cores = get.param(imputation, "cores")

                 add.param(step = "imputation", param = "max iterations", value = max.iterations)
                 add.param(step = "imputation", param = "cores", value = cores)

                 paste0("missForest[[missForest]], a non-parametric random-forest procedure that ",
                        "predicts each protein from all the others and iterates until the change in ",
                        "the imputed values stops decreasing (at most ", number.to.text(max.iterations),
                        " iterations)")
               },

               "regimpute" = {
                 regimpute.parameters = get.param(imputation, "parameters", default = list())
                 fillmethod = get.param(regimpute.parameters, "fillmethod")
                 max.iterations = get.param(regimpute.parameters, "maxiter_RegImpute")
                 convergence = get.param(regimpute.parameters, "conv_nrmse")

                 add.param(step = "imputation", param = "fill method", value = fillmethod)
                 add.param(step = "imputation", param = "max iterations", value = max.iterations)
                 add.param(step = "imputation", param = "NRMSE convergence", value = convergence)

                 paste0("RegImpute, the iterative ridge-regression algorithm distributed with ",
                        "DreamAI[[DreamAI]], initialized with the '", fillmethod, "' strategy and run ",
                        "for at most ", number.to.text(max.iterations), " iterations or until the ",
                        "normalized RMSE between two consecutive rounds dropped below ",
                        number.to.text(convergence))
               },

               "knn" = {
                 k = get.param(imputation, "n.nearest.neighbours")
                 add.param(step = "imputation", param = "nearest neighbours", value = k)

                 paste0("k-nearest neighbours as implemented in VIM[[VIM]], with k = ", number.to.text(k),
                        " neighbours and a weighted mean as aggregating function")
               },

               "tknn" = {
                 k = get.param(imputation, "n.nearest.neighbours")
                 add.param(step = "imputation", param = "nearest neighbours", value = k)

                 paste0("truncation-distance k-nearest neighbours (tkNN) from the imputomics ",
                        "collection[[imputomics]], with k = ", number.to.text(k), " neighbours")
               },

               "corknn" = {
                 k = get.param(imputation, "n.nearest.neighbours")
                 add.param(step = "imputation", param = "nearest neighbours", value = k)

                 paste0("correlation-distance k-nearest neighbours (corkNN) from the imputomics ",
                        "collection[[imputomics]], with k = ", number.to.text(k), " neighbours")
               },

               "lls" = {
                 cluster.size = get.param(imputation, "cluster.size")
                 add.param(step = "imputation", param = "cluster size (k)", value = cluster.size)

                 paste0("local least squares (LLS)[[LLS]], as implemented in pcaMethods",
                        "[[pcaMethods]], regressing each protein on the ", number.to.text(cluster.size),
                        " most correlated ones (Pearson correlation)")
               },

               "svd" = {
                 PCs.tested = get.param(imputation, "PCs.tested")
                 add.param(step = "imputation", param = "PCs tested", value = PCs.tested)

                 paste0("svdImpute[[SVDimpute]], as implemented in pcaMethods[[pcaMethods]], with the ",
                        "number of principal components chosen by cross-validation (Q2) among the ",
                        "first ", number.to.text(PCs.tested))
               },

               "bpca" = {
                 PCs.tested = get.param(imputation, "PCs.tested")
                 add.param(step = "imputation", param = "PCs tested", value = PCs.tested)

                 paste0("Bayesian PCA (BPCA)[[BPCA]], as implemented in pcaMethods[[pcaMethods]], with ",
                        "the number of principal components chosen by cross-validation (Q2) among the ",
                        "first ", number.to.text(PCs.tested))
               },

               "ppca" = {
                 PCs.tested = get.param(imputation, "PCs.tested")
                 add.param(step = "imputation", param = "PCs tested", value = PCs.tested)

                 paste0("probabilistic PCA (PPCA)[[PPCA]], as implemented in pcaMethods[[pcaMethods]], ",
                        "with the number of principal components chosen by cross-validation (Q2) among ",
                        "the first ", number.to.text(PCs.tested))
               },

               ifelse(imputation.method == "unknown",
                      yes = "an algorithm whose settings were not recorded in the object",
                      no = paste0("the '", imputation.method, "' algorithm")))


      ## missForest measures its own accuracy: the out-of-bag error is worth reporting
      OOB.text = ""
      if (tolower(imputation.method) == "missforest") {
        OOB.error = suppressWarnings(as.numeric(get.param(imputation, "OOBerror", default = NA)))

        if (!all(is.na(OOB.error))) {
          add.param(step = "imputation", param = "out-of-bag error",
                    value = number.to.text(mean(OOB.error, na.rm = TRUE)))

          OOB.text = ifelse(length(OOB.error) > 1,
                            yes = paste0(" The mean out-of-bag error across proteins was ",
                                         number.to.text(mean(OOB.error, na.rm = TRUE)), "."),
                            no = paste0(" The out-of-bag normalized RMSE of the imputation was ",
                                        number.to.text(OOB.error), "."))
        }
      }

      imputation.text =
        paste0(ifelse(isTRUE(DEprot.object@randomized),
                      yes = "The remaining missing values were imputed on the ",
                      no = "Missing values were imputed on the "),
               ifelse(is.na(imputation.data), yes = "processed", no = as.character(imputation.data)),
               " intensities using ", method.text, ".",
               ifelse(is.na(number.to.text(imputation.seed)),
                      yes = "",
                      no = paste0(" The random seed was set to ", number.to.text(imputation.seed), ".")),
               OOB.text)

    } else if ("DEprot.analyses" %in% class(DEprot.object)) {
      if (identical(tolower(as.character(get.param(DEprot.object@differential.analyses.params,
                                                   "stat.test", default = ""))), "proda")) {
        imputation.text =
          paste0("No imputation was performed: the missing values were handled directly by the ",
                 "statistical model (see below).")
      } else {
        imputation.text = "No imputation was performed."
      }
    } else {
      imputation.text = "No imputation was performed."
    }



    #############################################################################################
    ### Differential analyses
    #############################################################################################

    differential.text = NULL
    results.text = NULL

    if ("DEprot.analyses" %in% class(DEprot.object)) {
      diff.parameters = DEprot.object@differential.analyses.params
      contrasts.info = DEprot.object@contrasts

      ## contrast selection
      if (is.null(contrasts)) {
        contrasts = 1:length(contrasts.info)
      } else if (!is.numeric(contrasts)) {
        stop("The 'contrasts' must be a numeric vector.")
      } else if (max(contrasts) > length(contrasts.info)) {
        stop("At least one of the 'contrasts' indicated is not available.")
      }

      stat.test = as.character(get.param(diff.parameters, "stat.test", default = "unknown"))
      counts.used = get.param(diff.parameters, "counts.used")
      linear.FC.th = get.param(diff.parameters, "linear.FC.th")
      unresponsive.range = get.param(diff.parameters, "linear.FC.unresp.range")
      padj.th = get.param(diff.parameters, "padj.th")
      padj.method = as.character(get.param(diff.parameters, "padj.method", default = "none"))
      replicate.column = get.param(diff.parameters, "replicate.column")
      paired.test = get.param(diff.parameters, "paired.test",
                              default = get.param(diff.parameters, "rep.model", default = FALSE))

      add.param(step = "differential analyses", param = "test", value = stat.test)
      add.param(step = "differential analyses", param = "counts used", value = counts.used)
      add.param(step = "differential analyses", param = "linear fold change threshold", value = linear.FC.th)
      add.param(step = "differential analyses", param = "unresponsive range", value = unresponsive.range)
      add.param(step = "differential analyses", param = "p.adjusted threshold", value = padj.th)
      add.param(step = "differential analyses", param = "p-value correction", value = padj.method)
      add.param(step = "differential analyses", param = "replicate column", value = replicate.column)
      add.param(step = "differential analyses", param = "paired design", value = paired.test)

      ## contrasts, with the size of each group
      contrast.descriptions =
        sapply(contrasts,
               function(i) {
                 paste0(contrasts.info[[i]]$var.1, " versus ", contrasts.info[[i]]$var.2,
                        " (n = ", length(contrasts.info[[i]]$group.1), " and n = ",
                        length(contrasts.info[[i]]$group.2), ", '",
                        contrasts.info[[i]]$metadata.column, "' variable)")
               })

      ## test-specific description
      test.text =
        switch(tolower(stat.test),

               "t.test" = paste0("a two-sided Student's t-test",
                                 ifelse(isTRUE(paired.test),
                                        yes = paste0(", paired by '", replicate.column, "'"), no = "")),

               "wilcoxon" = paste0("a two-sided Wilcoxon rank-sum test",
                                   ifelse(isTRUE(paired.test),
                                          yes = paste0(", paired by '", replicate.column, "'"), no = "")),

               "limma" = {
                 fitting.method = get.param(diff.parameters, "fitting.method")
                 add.param(step = "differential analyses", param = "limma fitting method", value = fitting.method)

                 paste0("linear models with empirical Bayes moderation of the protein-wise variances, ",
                        "as implemented in limma[[limma]]",
                        ifelse(is.na(fitting.method),
                               yes = "", no = paste0(" ('", fitting.method, "' fitting)")),
                        ifelse(isTRUE(paired.test),
                               yes = paste0(", including '", replicate.column,
                                            "' in the design to account for the paired structure of ",
                                            "the experiment"),
                               no = ""))
               },

               "prolfqua" = {
                 strategy = get.param(diff.parameters, "strategy", default = list())
                 strategy.id = get.param(strategy, "strategy.id")
                 moderate.variance = get.param(diff.parameters, "moderate.variance")
                 robust.scaling = get.param(diff.parameters, "robust.scaling")

                 add.param(step = "differential analyses", param = "prolfqua strategy", value = strategy.id)
                 add.param(step = "differential analyses", param = "variance moderation", value = moderate.variance)
                 add.param(step = "differential analyses", param = "robust scaling", value = robust.scaling)

                 paste0("the linear model framework of prolfqua[[prolfqua]]",
                        ifelse(is.na(strategy.id), yes = "", no = paste0(" ('", strategy.id, "' strategy)")),
                        ifelse(isTRUE(moderate.variance),
                               yes = ", with moderation of the residual variances", no = ""),
                        ifelse(isTRUE(robust.scaling),
                               yes = " and robust scaling of the standard errors", no = ""),
                        ifelse(isTRUE(paired.test),
                               yes = paste0(", blocking on '", replicate.column, "'"), no = ""))
               },

               "proda" = {
                 min.detected = get.param(diff.parameters, "min.detected")
                 moderate.location = get.param(diff.parameters, "moderate.location")
                 moderate.variance = get.param(diff.parameters, "moderate.variance")

                 add.param(step = "differential analyses", param = "minimum detections", value = min.detected)
                 add.param(step = "differential analyses", param = "location moderation", value = moderate.location)
                 add.param(step = "differential analyses", param = "variance moderation", value = moderate.variance)

                 paste0("proDA[[proDA]], which models the probability of a dropout as a function of ",
                        "the intensity and therefore uses the missing values as information instead ",
                        "of requiring imputation",
                        ifelse(is.na(number.to.text(min.detected)),
                               yes = "",
                               no = paste0("; proteins detected in fewer than ", number.to.text(min.detected),
                                           " samples of a contrast were not tested")),
                        ifelse(isTRUE(paired.test),
                               yes = paste0(", and '", replicate.column,
                                            "' was included in the design as a blocking factor"),
                               no = ""))
               },

               paste0("the '", stat.test, "' test"))

      ## multiple testing correction
      correction.text =
        if (tolower(padj.method) == "bh" | tolower(padj.method) == "fdr") {
          "P-values were corrected for multiple testing with the Benjamini-Hochberg procedure[[BH]]"
        } else if (tolower(padj.method) == "fdrtool") {
          paste0("False discovery rates were estimated from the moderated t-statistics with ",
                 "fdrtool[[fdrtool]]")
        } else if (tolower(padj.method) == "effective fdr") {
          paste0("False discovery rates were estimated by prolfqua from the empirical distribution ",
                 "of the test statistics")
        } else if (tolower(padj.method) == "none") {
          "No correction for multiple testing was applied"
        } else {
          paste0("P-values were corrected for multiple testing with the '", padj.method, "' method")
        }

      log2.FC.th = if (is.na(number.to.text(linear.FC.th))) {NA} else {log2(as.numeric(linear.FC.th))}

      differential.text =
        paste0("Differential protein abundance was tested on the ",
               ifelse(is.na(counts.used), yes = "processed", no = as.character(counts.used)),
               " intensities using ", test.text, ". The following comparisons were performed: ",
               paste(contrast.descriptions, collapse = "; "), ". ",
               correction.text, ". ",
               "Proteins were called differentially abundant when the ",
               ifelse(tolower(padj.method) == "none", yes = "p-value", no = "adjusted p-value"),
               " was below ", number.to.text(padj.th),
               ifelse(is.na(log2.FC.th),
                      yes = "",
                      no = paste0(" and the absolute log2(fold change) was above ",
                                  number.to.text(log2.FC.th), " (linear fold change of ",
                                  number.to.text(linear.FC.th), ")")),
               ifelse(length(unresponsive.range) < 2,
                      yes = ".",
                      no = paste0(". Proteins with a linear fold change between ",
                                  number.to.text(unresponsive.range[1]), " and ",
                                  number.to.text(unresponsive.range[2]),
                                  " were annotated as unresponsive.")))

      ## number of differential proteins per contrast
      if (isTRUE(include.results.summary) & length(DEprot.object@analyses.result.list) > 0) {
        results.summary =
          sapply(contrasts,
                 function(i) {
                   n.diff = DEprot.object@analyses.result.list[[i]]$n.diff
                   n.up = sum(n.diff$n[as.character(n.diff$diff.status) == contrasts.info[[i]]$var.1], na.rm = TRUE)
                   n.down = sum(n.diff$n[as.character(n.diff$diff.status) == contrasts.info[[i]]$var.2], na.rm = TRUE)

                   paste0(n.up + n.down, " proteins in ", contrasts.info[[i]]$var.1, " versus ",
                          contrasts.info[[i]]$var.2, " (", n.up, " enriched in ",
                          contrasts.info[[i]]$var.1, ", ", n.down, " enriched in ",
                          contrasts.info[[i]]$var.2, ")")
                 })

        results.text = paste0("These thresholds returned ",
                              paste(results.summary, collapse = "; "), ".")
      }
    }



    #############################################################################################
    ### Quality control
    #############################################################################################

    QC.text =
      paste0("Sample similarity was inspected before and after processing through the distribution ",
             "of the intensities, principal component analysis and hierarchical clustering of the ",
             "pairwise Pearson and Spearman correlation coefficients, all computed on the same ",
             "matrix used for the tests.")



    #############################################################################################
    ### Geneset enrichment
    #############################################################################################

    enrichment.text = NULL

    if (!is.null(enrichment.object)) {
      enrichment.parameters = enrichment.object@parameters
      enrichment.type = toupper(as.character(get.param(enrichment.parameters, "enrichment.type",
                                                       default = "ORA")))
      diff.status.category = get.param(enrichment.parameters, "diff.status.category")
      rank.method = get.param(enrichment.parameters, "gsea.rank.method")
      pvalueCutoff = get.param(enrichment.parameters, "pvalueCutoff")
      qvalueCutoff = get.param(enrichment.parameters, "qvalueCutoff")
      pAdjustMethod = as.character(get.param(enrichment.parameters, "pAdjustMethod", default = "BH"))

      add.param(step = "enrichment", param = "type", value = enrichment.type)
      add.param(step = "enrichment", param = "geneset collection", value = geneset.database)
      add.param(step = "enrichment", param = "protein subset", value = diff.status.category)
      add.param(step = "enrichment", param = "ranking metric", value = rank.method)
      add.param(step = "enrichment", param = "p-value cutoff", value = pvalueCutoff)
      add.param(step = "enrichment", param = "q-value cutoff", value = qvalueCutoff)
      add.param(step = "enrichment", param = "p-value correction", value = pAdjustMethod)

      enrichment.text =
        paste0(ifelse(enrichment.type == "GSEA",
                      yes = paste0("Gene set enrichment analysis (GSEA)[[GSEA]] was run on all the ",
                                   "quantified proteins ranked by ",
                                   ifelse(is.na(rank.method),
                                          yes = "fold change",
                                          no = gsub("foldchange", "fold change", as.character(rank.method)))),
                      no = paste0("Over-representation analysis was run on the ",
                                  ifelse(is.null(diff.status.category),
                                         yes = "differential proteins",
                                         no = paste0("'", paste(diff.status.category, collapse = "', '"),
                                                     "' proteins")),
                                  ", using all the quantified proteins as background")),
               ", with clusterProfiler[[clusterProfiler]]",
               ifelse(is.null(geneset.database),
                      yes = "",
                      no = paste0(" and the ", geneset.database, " collection",
                                  ifelse(is.null(geneset.reference), yes = "", no = "[[geneset.database]]"))),
               ". P-values were corrected with the '", pAdjustMethod, "' method and genesets were ",
               "retained when the adjusted p-value was below ", number.to.text(pvalueCutoff),
               ifelse(is.na(number.to.text(qvalueCutoff)),
                      yes = ".", no = paste0(" and the q-value below ", number.to.text(qvalueCutoff), ".")))

      ## the affinity propagation slot is filled only when the redundancy of the genesets is reduced
      if (!is.null(enrichment.object@affinity.propagation)) {
        enrichment.text =
          paste0(enrichment.text,
                 " Redundant genesets were grouped into clusters of similar terms by affinity ",
                 "propagation and the resulting enrichment network was drawn with aPEAR[[aPEAR]].")
      }
    }



    #############################################################################################
    ### Assemble, number the citations and format
    #############################################################################################

    paragraphs = c(paste(trimws(c(intro.text, normalization.text, randomization.text, imputation.text)),
                         collapse = " "),
                   paste(trimws(c(differential.text, results.text, QC.text)), collapse = " "),
                   trimws(enrichment.text))

    paragraphs = paragraphs[!is.na(paragraphs) & nchar(paragraphs) > 0]

    numbered = number.citations(text = paste(paragraphs, collapse = "\n\n"))

    text = numbered$text
    references = numbered$references

    ## the version of the packages actually loaded makes the reference list reproducible
    if (isTRUE(include.package.versions)) {
      packages = reference.database$package[match(references$key, reference.database$key)]

      references$citation =
        sapply(1:nrow(references),
               function(i) {
                 if (is.na(packages[i])) {return(references$citation[i])}

                 version = tryCatch(as.character(utils::packageVersion(packages[i])),
                                    error = function(e) {NA})

                 if (is.na(version)) {return(references$citation[i])}

                 paste0(references$citation[i], " [R-package v", version, "]")
               })
    }

    if (!is.null(extra.references)) {
      references = rbind(references,
                         data.frame(n = nrow(references) + (1:length(extra.references)),
                                    key = paste0("extra.", 1:length(extra.references)),
                                    citation = as.character(extra.references),
                                    stringsAsFactors = FALSE))
    }

    reference.lines = paste0(references$n, ". ", references$citation)

    full.text =
      paste(c(if (isTRUE(add.headers)) {c("MATERIAL AND METHODS", "")},
              wrap.text(text),
              "",
              if (isTRUE(add.headers)) {c("REFERENCES", "")},
              sapply(reference.lines, wrap.text)),
            collapse = "\n")


    ### Export and print
    if (!is.null(output.file)) {
      writeLines(text = full.text, con = output.file)
    }

    if (isTRUE(verbose)) {
      cat(full.text, "\n")
    }


    return(invisible(list(text = text,
                          references = references,
                          parameters = parameters,
                          full.text = full.text)))
  } # END function
