#' @title harmonize.batches
#'
#' @description The function uses the package \href{https://www.bioconductor.org/packages/release/bioc/html/HarmonizR.html}{\code{HarmonizR}} to correct batch effects in a combined table of multiple experiments.
#'
#' @param DEprot.object A \code{DEprot object}, as generated by \link{load.counts2}. Notice that this function works only with "raw" counts.
#' @param batch.column String indicating the name of a column of the metadata table in which are stored the batch IDs. Default: \code{"batch"}.
#' @param algorithm Adjustment method handed to \code{HarmonizR}. Either \code{"ComBat"} or \code{"limma"} (limma's \code{removeBatchEffect}). Default: \code{"ComBat"}
#' @param ComBat.mode Chooses the ComBat parameter set. Applied only when
#'   \code{algorithm = "ComBat"} and ignored under limma. Each number is a
#'   combination of ComBat's \code{par.prior} (parametric vs. non-parametric
#'   empirical priors) and \code{mean.only} (adjust the mean alone, or both mean
#'   and variance):
#'   \itemize{
#'     \item \code{1} — parametric priors; adjusts location and scale
#'       (\code{par.prior = TRUE}, \code{mean.only = FALSE}).
#'     \item \code{2} — parametric priors; adjusts the mean only, variance left
#'       as is (\code{par.prior = TRUE}, \code{mean.only = TRUE}).
#'     \item \code{3} — non-parametric priors; adjusts location and scale, with
#'       no Gaussian assumption on the batch effect but slower to run
#'       (\code{par.prior = FALSE}, \code{mean.only = FALSE}).
#'     \item \code{4} — non-parametric priors; adjusts the mean only
#'       (\code{par.prior = FALSE}, \code{mean.only = TRUE}).
#'   }
#'   Default: \code{1}
#' @param block Number of batches grouped together during blocking. Larger blocks
#'   yield fewer sub-matrices and cut runtime; \code{NULL} disables blocking.
#'   Default: \code{NULL}.
#' @param cores Numeric value indicating the number of cores to use for the batch correction. Default: \code{1}.
#' @param verbose Logical value indicating whether processing messages should be printed. Default: \code{TRUE}.
#'
#' @import dplyr
#' @import ggplot2
#' @importFrom HarmonizR harmonizR
#'
#' @author Sebastian Gregoricchio
#'
#' @return An object of class \code{DEprot}
#'
#' @examples
#' # Add batch column to the DEprot object
#' dpo = DEprot::test.toolbox$dpo.raw
#' dpo@metadata$batch = c(rep("A",6), rep("B",6))
#'
#' # Correct batch effects
#' dpo <- harmonize.batches(DEprot.object = dpo,
#'                          batch.column = "batch",
#'                          cores = 1)
#'
#'
#' @export harmonize.batches

harmonize.batches =
  function(DEprot.object,
           batch.column = "batch",
           algorithm = "ComBat",
           ComBat.mode = 1,
           block = NULL,
           cores = 1,
           verbose = TRUE) {

    # ### Packages
    # require(dplyr)
    # require(ggplot2)
    #
    # if (!requireNamespace("HarmonizR", quietly = TRUE)) {
    #   warning("The 'HarmonizR' (Bioconductor) package must be installed to use this function.")
    #
    #   ### Ask for installing
    #   install = readline("Do you want to install `HarmonizR`? [yes/no] ")
    #   if (tolower(install) %in% c("yes","y","yeah","yep","yo")) {
    #     BiocManager::install("HarmonizR")
    #     library(HarmonizR)
    #   } else {
    #     return(DEprot.object)
    #   }
    # } else {
    #   require(HarmonizR)
    # }

    #------------------------------------------------------------------


    ### check object and extract metadata table
    if (!("DEprot" %in% class(DEprot.object))) {
      stop("The input must be an object of class 'DEprot'.")
      #return(DEprot.object)
    }
    meta.tb = DEprot.object@metadata


    ### check if raw un-imputed data are available
    if (is.null(DEprot.object@raw.counts)) {
      stop(paste0("The 'harmonize.batches' function requires the data to be loaded as 'raw'."
                  #"Combine tables of intra-batch normalized data and then use 'harmonize.batches' to correct the signal among batches."
      ))
    }


    ### Check 'batch.column' presence and eventually the paired.test variable
    if (!is.null(batch.column[[1]])) {
      if (!(batch.column %in% colnames(meta.tb))) {
        stop("The 'batch.column' is not present in the metadata of the object.")
        #return(DEprot.object)
      } else {
        meta.tb[,batch.column[[1]]] = as.character(meta.tb[,batch.column[[1]]])
      }
    }

    ### Create description file for Harmonizer
    des = data.frame(ID = meta.tb$column.id,
                     sample = meta.tb$column.id,
                     batch = as.numeric(factor(meta.tb[,batch.column[[1]]],
                                               labels = c(1:length(unique(meta.tb[,batch.column[[1]]]))))))


    ### Harmonize batches
    batch.corrected.counts = HarmonizR::harmonizR(data_as_input = data.frame(DEprot.object@raw.counts, check.names = FALSE),
                                                  description_as_input = des,
                                                  algorithm = algorithm,
                                                  ComBat_mode = ComBat.mode,
                                                  block = block,
                                                  cores = cores,
                                                  output_file = FALSE,
                                                  sort = FALSE,
                                                  verbosity = as.numeric(verbose))

    ### Reset original order of the columns
    batch.corrected.counts = batch.corrected.counts[,colnames(data.frame(DEprot.object@raw.counts, check.names = FALSE))]



    ### Update DEprot object
    batch.corrected.DEprot = DEprot.object

    batch.corrected.DEprot@norm.counts = as.matrix(batch.corrected.counts)
    batch.corrected.DEprot@normalized = TRUE
    batch.corrected.DEprot@normalization.method =
      data.frame(param = c("package", "batch.column", "algorithm", "ComBat.mode", "block", "cores"),
                 value = c("HarmonizR", batch.column, algorithm, ComBat.mode, block, cores))

    boxplot.subtitle = paste0("HarmonizR (",
                              ifelse(test = tolower(algorithm) == "limma",
                                     yes = "limma)",
                                     no = paste0("ComBat, mode: ", ComBat.mode, ")")))

    batch.corrected.DEprot@boxplot.norm =
      DEprot::plot.counts(DEprot.object = batch.corrected.DEprot,
                          which.data = "normalized",
                          violin.color = "purple",
                          convert.log2 = TRUE,
                          title = "**Normalized**",
                          subtitle = paste0("*",boxplot.subtitle,"*"))


    ### Check whether HarmonizR dropped any protein
    # Features that can't be placed in a valid sub-matrix (present in a single
    # batch, or with too few values per batch) are not returned by HarmonizR,
    # leaving raw and normalized tables with a different number of rows. Any such
    # protein is removed from every table so the object stays consistent.
    # The warning is shown regardless of 'verbose'.
    removed.proteins = setdiff(rownames(batch.corrected.DEprot@raw.counts),
                               rownames(batch.corrected.DEprot@norm.counts))

    if (nrow(batch.corrected.DEprot@norm.counts) == 0) {# --> HarmonizR corrected no protein at all: the table is empty.
      stop(paste0("HarmonizR returned an empty table: no protein could be batch-corrected.\n",
                  "  This usually means the batch design is too sparse for '", algorithm, "'",
                  " (e.g., a batch with a single sample, or proteins with too few values per batch).\n",
                  " Check the batch composition with `table(<dpo.object>@metadata[['", batch.column, "']])`",
                  " and, if using ComBat (default), try to set `algorithm = 'limma'` or a mean-only `ComBat.mode` (i.e., 2 or 4)."),
           call. = FALSE)

    } else if (length(removed.proteins) > 0) {
      warning(paste0(length(removed.proteins),
                     " protein(s) could not be batch-corrected by HarmonizR",
                     " (usually present only in a single batch or with too few values per batch)",
                     " and were removed to keep the object consistent:\n  ",
                     paste(removed.proteins, collapse = ", ")),
              call. = FALSE, immediate. = TRUE)

      batch.corrected.DEprot =
        DEprot::filter.proteins(DEprot.object = batch.corrected.DEprot,
                                proteins = removed.proteins,
                                mode = "remove")
    }


    ## Return corrected DEprot object
    return(batch.corrected.DEprot)

  } # END function
