#' @title heatmap.counts.anno
#'
#' @description Plots an heatmap of the counts (raw, normalized, randomized or imputed) using \code{ComplexHeatmap}. It works like \link{heatmap.counts}, but any column of the metadata table can be used to annotate the samples (heatmap columns) and any column of the \code{protein.info} table to annotate the proteins (heatmap rows). The colors of the annotations are defined as in \code{pheatmap}, through a named list of named vectors. It is possible to perform a scaling (z-score) by row or by column.
#'
#' @param DEprot.object An object of class \code{DEprot} or \code{DEprot.analyses}.
#' @param which.data String indicating which type of counts should be used. One among: 'raw', 'normalized', 'norm', 'randomized', 'random', 'imputed', 'imp'. Default: \code{"imputed"}.
#' @param contrast Numeric vector indicating the position of the contrast to use for the plotting. Only differential proteins in this contrast will be shown. Option available only for an object of class \code{DEprot.analyses}. Default: \code{NULL} (non differential protein selection).
#' @param top.n Numeric value indicated the top differentially expressed proteins to consider for the contrast selected. The rank is based on the product of log2Fc and -log10Padj. Option available only for an object of class \code{DEprot.analyses}. Default: \code{NULL} (all differential proteins of that contrast).
#' @param sample.subset Character vector indicating a subset of samples to display. The identifiers must correspond to a IDs in the \code{column.id} column of the object's metadata. The samples are displayed in the order provided when the columns are not clustered. Default: \code{NULL} (all samples are shown).
#' @param protein.subset Character vector indicating a subset of proteins to display. The identifiers must correspond to the full row.names of the counts table (equivalent to the \code{prot.id} column of the fold change table of \code{DEprot.analyses} object). This options is can be used in combination with \code{contrast} and \code{top.n}. Default: \code{NULL} (all proteins are shown).
#' @param group.by.metadata.column String indicating a column from the metadata table. This column will be used to define sample groups, and for each group it will be computed a mean of the counts. Default: \code{NULL} (no groups).
#' @param column.annotation Character vector indicating one or more columns of the metadata table to use as annotation of the heatmap columns (samples). When the counts are averaged by group (\code{group.by.metadata.column}) only the columns taking a single value in each group can be displayed, the others are dropped with a warning. Default: \code{NULL} (no column annotation).
#' @param row.annotation Character vector indicating one or more columns of the \code{protein.info} table to use as annotation of the heatmap rows (proteins). An annotation table can be attached to the object with \link{add.protein.info}. Default: \code{NULL} (no row annotation).
#' @param annotation.colors Named list of colors used for the annotations, in the same format used by \code{pheatmap}: one element per annotation column, named as the column itself. Discrete annotations require a named vector of colors (one color per value), while continuous ones accept either a vector of colors, used to build a gradient, or directly a color function such as the ones generated by \code{circlize::colorRamp2}. Columns that are not listed get an automatic palette. Default: \code{NULL} (automatic colors).
#' @param annotation.na.color String indicating the color to use for the NA values in the annotations. Default: \code{"white"}.
#' @param column.annotation.side String indicating on which side of the heatmap the column annotation should be drawn: "top" or "bottom". Default: \code{"top"}.
#' @param row.annotation.side String indicating on which side of the heatmap the row annotation should be drawn: "left" or "right". Default: \code{"left"}.
#' @param show.annotation.legend Logical value indicating whether the legends of the annotations should be displayed. Default: \code{TRUE}.
#' @param column.split Either a string indicating a column of the metadata table, used to split the samples in separated blocks, or a numeric value indicating the number of blocks in which the column dendrogram should be cut. Default: \code{NULL} (no splitting).
#' @param row.split Either a string indicating a column of the \code{protein.info} table, used to split the proteins in separated blocks, or a numeric value indicating the number of blocks in which the row dendrogram should be cut. Default: \code{NULL} (no splitting).
#' @param scale String indicating whether Z-scores should be computed. Possible choices: "row" or "column". Default: \code{NULL} (no scaling).
#' @param clust.rows Logical value indicating whether heatmap rows (proteins) should be clustered. Default: \code{TRUE}.
#' @param clust.columns Logical value indicating whether heatmap columns (samples or groups) should be clustered. Default: \code{TRUE}.
#' @param distance.method The distance measure to be used. This must be one of "euclidean", "maximum", "manhattan", "canberra", "binary" or "minkowski". Any unambiguous substring can be given. Default: \code{"euclidean"}.
#' @param clustering.method The agglomeration method to be used. This should be (an unambiguous abbreviation of) one of "ward.D", "ward.D2", "single", "complete", "average" (UPGMA), "mcquitty" (WPGMA), "median" (WPGMC) or "centroid" (UPGMC). Default: \code{"complete"}.
#' @param palette List of colors to use for the color gradient of the heatmap. This parameters is used when raw-counts are plotted. For scaled data see the high, low and mid parameters. Default: \code{RColorBrewer\:\:brewer.pal(n = 9, name = "Blues")}.
#' @param high.color String indicating the color to use for positive Z-score for scaled data. Default: \code{"indianred"}.
#' @param low.color String indicating the color to use for negative Z-score for scaled data. Default: \code{"\#2166AC"} (blue).
#' @param mid.color String indicating the color to use for the 0 Z-score value for scaled data. Default: \code{"white"}.
#' @param na.color String indicating the color to use for the NA values in the heatmap. Default: \code{"gray"}.
#' @param color.limits Numeric vector of length 2 indicating lower and upper limit of the color scale values. Default: \code{c(NA,NA)}, automatic limits applied.
#' @param cell.border.color String indicating the color to use for the individual cells border. Default: \code{NA} (no border).
#' @param cell.border.width Numeric value indicating the width of the cell border line. Ignored when \code{cell.border.color = NA}. Default: \code{0.5}.
#' @param heatmap.border Logical value indicating whether a black border should be drawn around the heatmap body. Default: \code{TRUE}.
#' @param show.protein.names Logical value to indicate whether the protein names should be displayed. Default: \code{FALSE}.
#' @param show.sample.names Logical value to indicate whether the sample (or group) names should be displayed. Default: \code{TRUE}.
#' @param protein.names.pattern Character indicating a regular expression to remove from the protein IDs. Default: \code{NULL}, no alterations in the protein IDs.
#' @param title String indicating the title to use. Markdown formatting is not supported by \code{ComplexHeatmap}. Default: \code{NULL} (no title).
#' @param legend.title String indicating the title of the heatmap color legend. Default: \code{NULL} (automatic title).
#' @param use.raster Logical value indicating whether the heatmap body should be rasterized, which keeps the size of the output reasonable when thousands of proteins are plotted. Default: \code{NULL}, rasterization applied when more than 2000 rows are displayed.
#' @param use.uncorrected.pvalue Logical value indicating whether it should be used the normal p-value instead of the adjusted one (differential proteins numbers are recomputed). Default: \code{FALSE}, padj is used.
#'
#' @return A \code{DEprot.counts.heatmap} object, which contains the \code{ComplexHeatmap} heatmap and the hclust objects used to order rows and columns.
#'
#' @details The heatmap is returned unevaluated: rows and columns are ordered by \code{ComplexHeatmap} at drawing time. Any further customization can be applied on the \code{heatmap} slot of the object using the standard \code{ComplexHeatmap} syntax, for instance to concatenate more heatmaps or annotations. When the heatmap is split by a column of the metadata (or of the \code{protein.info}), the clustering is recomputed within each block, while the hclust objects stored in the returned object are always computed on the full matrix.
#'
#' @seealso \link{heatmap.counts}, \link{add.protein.info}, \link{heatmap.contrasts}
#'
#' @import dplyr
#' @importFrom grid gpar
#' @importFrom RColorBrewer brewer.pal
#' @importFrom purrr pmap
#' @importFrom stats dist hclust setNames
#' @importFrom viridis viridis mako
#' @importFrom ComplexHeatmap Heatmap HeatmapAnnotation
#' @importFrom circlize colorRamp2
#'
#' @author Sebastian Gregoricchio
#'
#' @examples
#' \donttest{
#' # Top differential proteins, samples annotated by condition and replicate
#' heatmap.counts.anno(DEprot.object = DEprot::test.toolbox$diff.exp.limma,
#'                     contrast = 1,
#'                     top.n = 20,
#'                     scale = "row",
#'                     column.annotation = c("condition", "replicate"))
#'
#' # Same heatmap with custom colors and samples split by condition
#' heatmap.counts.anno(DEprot.object = DEprot::test.toolbox$diff.exp.limma,
#'                     contrast = 1,
#'                     top.n = 20,
#'                     scale = "row",
#'                     column.annotation = c("condition", "replicate"),
#'                     column.split = "condition",
#'                     annotation.colors = list(condition = c("6h.10nM.E2" = "indianred",
#'                                                            "6h.DMSO" = "steelblue",
#'                                                            "FBS" = "forestgreen")))
#' }
#'
#' @export heatmap.counts.anno

heatmap.counts.anno =
  function(DEprot.object,
           which.data = "imputed",
           contrast = NULL,
           top.n = NULL,
           sample.subset = NULL,
           protein.subset = NULL,
           group.by.metadata.column = NULL,
           column.annotation = NULL,
           row.annotation = NULL,
           annotation.colors = NULL,
           annotation.na.color = "white",
           column.annotation.side = "top",
           row.annotation.side = "left",
           show.annotation.legend = TRUE,
           column.split = NULL,
           row.split = NULL,
           scale = NULL,
           clust.rows = TRUE,
           clust.columns = TRUE,
           distance.method = "euclidean",
           clustering.method = "complete",
           palette = RColorBrewer::brewer.pal(n = 9, name = "Blues"),
           high.color = "firebrick",
           low.color = "#2166AC",
           mid.color = "white",
           na.color = "gray",
           color.limits = c(NA,NA),
           cell.border.color = NA,
           cell.border.width = 0.5,
           heatmap.border = TRUE,
           show.protein.names = FALSE,
           show.sample.names = TRUE,
           protein.names.pattern = NULL,
           title = NULL,
           legend.title = NULL,
           use.raster = NULL,
           use.uncorrected.pvalue = FALSE) {

    ### Internal functions
    de.status =
      function(FC, p, contrasts.info, params) {
        ifelse(p < params$padj.th,
               yes = ifelse(abs(FC) >= log2(params$linear.FC.th),
                            yes = ifelse(sign(FC) == 1,
                                         yes = contrasts.info$var.1,
                                         no = contrasts.info$var.2),
                            no = "null"),
               no = ifelse(FC >= log2(params$linear.FC.unresp.range[1]) & FC <= log2(params$linear.FC.unresp.range[2]),
                           yes = "unresponsive",
                           no = "null"))
      }


    check.matrix =
      function(m){
        warn = "Upon subsetting, no values to show are left."
        if (!is.logical(m)) {
          if (nrow(m) == 0 | ncol(m) == 0) {
            stop(warn)
          }
        } else {
          stop(warn)
        }
      }



    is.nan_df = function(data.frame) {do.call(cbind, lapply(data.frame, is.nan))}



    scale_matrix =
      function(mat, scale){
        if(!(scale %in% c("none", "row", "column"))){
          stop("scale argument shoud take values: 'none', 'row' or 'column'")
        }

        scale_rows = function(x){
          m = apply(x, 1, mean, na.rm = T)
          s = apply(x, 1, sd, na.rm = T)
          return((x - m) / s)
        }

        mat = switch(scale, none = mat, row = scale_rows(mat), column = t(scale_rows(t(mat))))
        return(mat)
      }


    ## Collects metadata columns and aligns them to the columns of the heatmap.
    ## When the counts are averaged by group, a column can be kept only if it takes
    ## a single value in each group (e.g. the cell line, but not the replicate).
    collect.column.info =
      function(columns, on.ambiguous = "drop") {
        if (is.null(columns)) {return(NULL)}

        missing.columns = columns[!(columns %in% colnames(meta))]
        if (length(missing.columns) > 0) {
          stop(paste0("The following columns are not available in the metadata table: ",
                      paste0(missing.columns, collapse = ", "), ".\n",
                      "Available column IDs: ", paste0(colnames(meta), collapse = ", ")),
               call. = FALSE)
        }

        if (is.null(group.by.metadata.column)) {
          info = meta[match(colnames(final.mat), meta$column.id), columns, drop = FALSE]
          rownames(info) = colnames(final.mat)
          return(info)
        }

        groups.vector = make.names(meta[,group.by.metadata.column])
        info = data.frame(row.names = colnames(final.mat))
        ambiguous = c()

        for (i in columns) {
          values = lapply(colnames(final.mat), function(g){unique(meta[[i]][groups.vector == g])})

          if (any(lengths(values) != 1)) {
            ambiguous = c(ambiguous, i)
            next
          }

          info[[i]] = unlist(values)
        }

        if (length(ambiguous) > 0) {
          ambiguity.message = paste0("The following columns take more than one value within at least one group defined by '",
                                     group.by.metadata.column, "': ", paste0(ambiguous, collapse = ", "), ".")

          if (on.ambiguous == "stop") {
            stop(ambiguity.message, call. = FALSE)
          } else {
            warning(paste0(ambiguity.message, " They are not displayed."), call. = FALSE)
          }
        }

        if (ncol(info) == 0) {return(NULL)}
        return(info)
      }


    ## Collects protein.info columns and aligns them to the rows of the heatmap
    collect.row.info =
      function(columns) {
        if (is.null(columns)) {return(NULL)}

        protein.info = .get.protein.info(DEprot.object)

        if (is.null(protein.info)) {
          stop(paste0("No 'protein.info' table is stored in this object, hence the rows cannot be annotated.\n",
                      "An annotation can be added with `add.protein.info()`."),
               call. = FALSE)
        }

        missing.columns = columns[!(columns %in% colnames(protein.info))]
        if (length(missing.columns) > 0) {
          stop(paste0("The following columns are not available in the 'protein.info' table: ",
                      paste0(missing.columns, collapse = ", "), ".\n",
                      "Available column IDs: ", paste0(colnames(protein.info), collapse = ", ")),
               call. = FALSE)
        }

        info = protein.info[match(rownames(final.mat), rownames(protein.info)), columns, drop = FALSE]
        rownames(info) = rownames(final.mat)
        return(info)
      }


    ## Builds the color mapping of the annotations (pheatmap-like syntax).
    ## Numeric columns for which a named vector of colors is provided are converted
    ## to characters, so that they are treated as discrete annotations.
    prepare.annotation =
      function(annotation.table, palette.offset = 0) {
        if (is.null(annotation.table)) {return(NULL)}

        viridis.options = c("D", "G", "F", "C", "E", "A", "B")
        color.list = list()

        for (i in 1:ncol(annotation.table)) {
          column.name = colnames(annotation.table)[i]
          values = annotation.table[[column.name]]
          user.colors = annotation.colors[[column.name]]

          ## color functions (e.g. circlize::colorRamp2) are used as they are
          if (is.function(user.colors)) {
            color.list[[column.name]] = user.colors
            next
          }

          discrete = !is.numeric(values) | (!is.null(user.colors) & !is.null(names(user.colors)))

          if (discrete == TRUE) {
            annotation.table[[column.name]] = as.character(values)

            if (is.factor(values)) {
              annotation.values = levels(droplevels(values))
            } else {
              annotation.values = sort(unique(as.character(values[!is.na(values)])))
            }

            if (!is.null(user.colors)) {
              if (is.null(names(user.colors))) {
                stop(paste0("The colors provided for the annotation '", column.name,
                            "' must be a named vector: one color per value of the annotation."),
                     call. = FALSE)
              }

              undefined.values = annotation.values[!(annotation.values %in% names(user.colors))]
              if (length(undefined.values) > 0) {
                stop(paste0("No color is provided for the following values of the annotation '", column.name, "': ",
                            paste0(undefined.values, collapse = ", "), "."),
                     call. = FALSE)
              }

              color.list[[column.name]] = user.colors[annotation.values]
            } else {
              viridis.option = viridis.options[((i + palette.offset - 1) %% length(viridis.options)) + 1]
              color.list[[column.name]] = stats::setNames(viridis::viridis(n = length(annotation.values),
                                                                           option = viridis.option,
                                                                           end = 0.9),
                                                          annotation.values)
            }

          } else {
            ## continuous annotation
            if (!is.null(user.colors)) {
              gradient = unname(user.colors)
            } else {
              gradient = viridis::mako(n = 3, direction = -1)
            }

            if (length(gradient) < 2) {
              stop(paste0("At least two colors are required to build the gradient of the annotation '", column.name, "'."),
                   call. = FALSE)
            }

            value.range = range(values, na.rm = TRUE)

            if (!all(is.finite(value.range))) {next}
            if (diff(value.range) == 0) {value.range = value.range + c(-0.5, 0.5)}

            color.list[[column.name]] = circlize::colorRamp2(breaks = seq(value.range[1], value.range[2], length.out = length(gradient)),
                                                             colors = gradient)
          }
        }

        return(list(table = annotation.table,
                    colors = color.list))
      }

    ######################################################################################

    ### ------------------------------------------------------------------- checks
    if (!(methods::is(DEprot.object, "DEprot.analyses"))) {
      if (!(methods::is(DEprot.object, "DEprot"))) {
        stop("The input must be an object of class 'DEprot' or 'DEprot.analyses'.", call. = FALSE)
      }
    }


    column.annotation.side = match.arg(tolower(as.character(column.annotation.side)[1]),
                                       choices = c("top", "bottom"))

    row.annotation.side = match.arg(tolower(as.character(row.annotation.side)[1]),
                                    choices = c("left", "right"))


    ### check grouping column
    if (!is.null(group.by.metadata.column)) {
      if (!(group.by.metadata.column %in% colnames(DEprot.object@metadata))) {
        stop(paste0("The 'group.by.metadata.column' is not present in the metadata of the object provided.\n",
                    "Available column IDs: ", paste0(colnames(DEprot.object@metadata), collapse = ", ")),
             call. = FALSE)
      }
    }


    ### check the annotation colors
    if (!is.null(annotation.colors)) {
      if (!is.list(annotation.colors) | is.null(names(annotation.colors))) {
        stop(paste0("The 'annotation.colors' must be a named list, one element per annotation column, ",
                    "each of them containing a named vector of colors (same syntax used by `pheatmap`)."),
             call. = FALSE)
      }

      unused.colors = names(annotation.colors)[!(names(annotation.colors) %in% c(column.annotation, row.annotation))]
      if (length(unused.colors) > 0) {
        warning(paste0("The following elements of 'annotation.colors' do not correspond to any annotation and are ignored: ",
                       paste0(unused.colors, collapse = ", "), "."),
                call. = FALSE)
      }
    }


    ### metadata table, restricted to the samples displayed
    meta = as.data.frame(DEprot.object@metadata)
    if (!is.null(sample.subset)) {
      meta = meta %>% dplyr::filter(column.id %in% sample.subset)
    }



    ### ------------------------------------------------------------------- counts table
    if (tolower(which.data) == "raw") {
      if (!is.null(DEprot.object@raw.counts)) {
        mat = DEprot.object@raw.counts
        data.used = "raw"
      } else {
        stop(paste0("Use of RAW counts was required, but not available.\n",
                    "Please indicated a count type among 'raw', 'normalized', 'imputed', using the option 'which.data'."),
             call. = FALSE)
      }
    } else if (tolower(which.data) %in% c("norm", "normalized", "normal")) {
      if (!is.null(DEprot.object@norm.counts)) {
        mat = DEprot.object@norm.counts
        data.used = "normalized"
      } else {
        stop(paste0("Use of NORMALIZED counts was required, but not available.\n",
                    "Please indicated a count type among 'raw', 'normalized', 'imputed', using the option 'which.data'."),
             call. = FALSE)
      }
    } else if (tolower(which.data) %in% c("imputed", "imp", "impute")) {
      if (!is.null(DEprot.object@imputed.counts)) {
        mat = DEprot.object@imputed.counts
        data.used = "imputed"
      } else {
        stop(paste0("Use of IMPUTED counts was required, but not available.\n",
                    "Please indicated a count type among 'raw', 'normalized', 'imputed', using the option 'which.data'."),
             call. = FALSE)
      }
    } else if (tolower(which.data) %in% c("randomized", "random")) {
      if (!is.null(DEprot.object@random.counts)) {
        mat = DEprot.object@random.counts
        data.used = "randomized"
      } else {
        stop(paste0("Use of RANDOMIZED counts was required, but not available.\n",
                    "Please indicated a count type among 'raw', 'normalized', 'randomized, 'imputed', using the option 'which.data'."),
             call. = FALSE)
      }
    } else {
      stop(paste0("The 'which.data' value is not recognized.\n",
                  "Please indicated a count type among 'raw', 'normalized', 'imputed', using the option 'which.data'."),
           call. = FALSE)
    }



    ### ------------------------------------------------------------------- subsetting
    if (!is.null(sample.subset)) {
      samples.to.show = unique(sample.subset)
      mat.filtered = mat[,samples.to.show[samples.to.show %in% colnames(mat)], drop = FALSE]
    } else {
      mat.filtered = mat
    }
    check.matrix(mat.filtered)


    if (!is.null(protein.subset)) {
      proteins.to.show = unique(protein.subset)
      mat.filtered = mat.filtered[proteins.to.show[proteins.to.show %in% rownames(mat.filtered)],, drop = FALSE]
    }
    check.matrix(mat.filtered)



    ### check and collect contrast (if possible: requires DEprot.analyses-class object)
    if (!is.null(contrast)) {
      if (methods::is(DEprot.object, "DEprot.analyses")) {
        if (is.numeric(contrast)) {
          if (contrast <= length(DEprot.object@analyses.result.list)) {
            fc.data = DEprot.object@analyses.result.list[[contrast]]$results
            colnames(fc.data)[5] = "log2.Fold_group1.vs.group2"

            # Change the column name for 'FDR' column into 'padj' for prolfqua analyses
            if ("strategy" %in% names(DEprot.object@differential.analyses.params)) {
              fc.data = fc.data %>% dplyr::rename(padj = FDR)
            }

            ## recompute up-downs if required
            if (use.uncorrected.pvalue == TRUE) {
              fc.data$padj = fc.data$p.value

              fc.data$diff.status =
                unlist(purrr::pmap(.l = list(FC = fc.data$log2.Fold_group1.vs.group2,
                                             p = fc.data$padj),
                                   .f = function(FC,p){
                                     de.status(FC, p,
                                               contrasts.info = DEprot.object@contrasts[[contrast]],
                                               params = DEprot.object@differential.analyses.params)}))
            }


            ## select top.n proteins
            if (!is.null(top.n)) {
              ## Use log2FC * -log10(padj) as ranking score
              fc.data =
                fc.data %>%
                dplyr::mutate(contrast = names(DEprot.object@contrasts)[contrast],
                              ranking.score = log2.Fold_group1.vs.group2 * -log10(fc.data$padj)) %>%
                dplyr::arrange(desc(abs(ranking.score))) %>%
                dplyr::mutate(rank = 1:nrow(fc.data))

              diff.prot = (fc.data %>% dplyr::filter(!(diff.status %in% c("null", "unresponsive"))))$prot.id
              diff.prot = unique(diff.prot[1:min(c(length(diff.prot), top.n))])

            } else {
              diff.prot = unique((fc.data %>% dplyr::filter(!(diff.status %in% c("null", "unresponsive"))))$prot.id)
            }


            ## filter the matrix for these proteins
            mat.filtered = mat.filtered[which(rownames(mat.filtered) %in% diff.prot),,drop=FALSE]
            check.matrix(mat.filtered)


          } else {
            stop("The 'contrast' indicated is not available.", call. = FALSE)
          }
        } else {
          stop("The 'contrast' must be a numeric value.", call. = FALSE)
        }
      } else {
        stop("The 'contrast' cannot be determined from a 'DEprot' object, provide a 'DEprot.analyses' object instead.", call. = FALSE)
      }
    }



    ### ------------------------------------------------------------------- grouping
    if (!is.null(group.by.metadata.column)) {
      groups = unique(unique(meta[,group.by.metadata.column]))

      groups.tb = meta[,c("column.id", group.by.metadata.column)]
      colnames(groups.tb)[2] = "group"

      new.data = list()
      for (i in 1:length(groups)) {
        samples.in.group = (dplyr::filter(.data = groups.tb, group == groups[i]))$column.id
        new.data[[i]] = rowMeans(mat.filtered[,samples.in.group, drop = FALSE], na.rm = TRUE)
      }

      new.data = data.frame(new.data)
      colnames(new.data) = make.names(groups)
      rownames(new.data) = rownames(mat.filtered)
      mat.filtered = as.matrix(new.data)
    }



    ### ------------------------------------------------------------------- scaling
    scaled = FALSE

    if (!is.null(scale)) {
      if (tolower(scale) %in% c("col", "columns", "col", "column", "c", "cols")) {
        if (nrow(mat.filtered) > 1) {
          final.mat = scale_matrix(mat = (DEprot.object@log.base^mat.filtered)-1, scale = "column")
          final.mat[is.nan_df(final.mat)] = 0
          scale.legend.title = "Z-score\n(by column)"
          scaled = TRUE
        } else {
          warning("Scaling by column is not possible because the number of rows is only 1.", call. = FALSE)
          final.mat = mat.filtered # no scaling applied
          scale.legend.title = paste(data.used, "counts")
        }
      } else if (tolower(scale) %in% c("row", "rows", "r")) {
        if (ncol(mat.filtered) > 1) {
          final.mat = scale_matrix(mat = (DEprot.object@log.base^mat.filtered)-1, scale = "row")
          final.mat[is.nan_df(final.mat)] = 0
          scale.legend.title = paste0("Z-score\n", data.used, " counts\n(by row)")
          scaled = TRUE
        } else {
          warning("Scaling by row is not possible because the number of columns is only 1.", call. = FALSE)
          final.mat = mat.filtered # no scaling applied
          scale.legend.title = paste(data.used, "counts")
        }
      } else {
        final.mat = mat.filtered # no scaling applied
        scale.legend.title = paste(data.used, "counts")
      }
    } else {
      final.mat = mat.filtered # no scaling applied
      scale.legend.title = paste(data.used, "counts")
    }

    if (!is.null(legend.title)) {scale.legend.title = legend.title}



    ### ------------------------------------------------------------------- annotations
    column.annotation.table = collect.column.info(columns = column.annotation, on.ambiguous = "drop")
    row.annotation.table = collect.row.info(columns = row.annotation)

    column.annotation.object = NULL
    row.annotation.object = NULL

    if (!is.null(column.annotation.table)) {
      prepared.column.annotation = prepare.annotation(annotation.table = column.annotation.table)

      column.annotation.arguments = list(df = prepared.column.annotation$table,
                                         which = "column",
                                         na_col = annotation.na.color,
                                         show_legend = show.annotation.legend,
                                         annotation_name_side = "right")

      if (length(prepared.column.annotation$colors) > 0) {
        column.annotation.arguments$col = prepared.column.annotation$colors
      }

      column.annotation.object = do.call(what = ComplexHeatmap::HeatmapAnnotation,
                                         args = column.annotation.arguments)
    }

    if (!is.null(row.annotation.table)) {
      prepared.row.annotation = prepare.annotation(annotation.table = row.annotation.table,
                                                   palette.offset = length(column.annotation.table))

      row.annotation.arguments = list(df = prepared.row.annotation$table,
                                      which = "row",
                                      na_col = annotation.na.color,
                                      show_legend = show.annotation.legend,
                                      annotation_name_side = "bottom")

      if (length(prepared.row.annotation$colors) > 0) {
        row.annotation.arguments$col = prepared.row.annotation$colors
      }

      row.annotation.object = do.call(what = ComplexHeatmap::HeatmapAnnotation,
                                      args = row.annotation.arguments)
    }



    ### ------------------------------------------------------------------- splitting
    column.split.parameter = NULL
    row.split.parameter = NULL

    if (!is.null(column.split)) {
      if (is.numeric(column.split)) {
        if (clust.columns == TRUE & ncol(final.mat) > 1) {
          column.split.parameter = column.split
        } else {
          warning("The columns can be split in a given number of blocks only when they are clustered. The 'column.split' is ignored.", call. = FALSE)
        }
      } else {
        column.split.parameter = collect.column.info(columns = as.character(column.split)[1], on.ambiguous = "stop")[[1]]
      }
    }

    if (!is.null(row.split)) {
      if (is.numeric(row.split)) {
        if (clust.rows == TRUE & nrow(final.mat) > 1) {
          row.split.parameter = row.split
        } else {
          warning("The rows can be split in a given number of blocks only when they are clustered. The 'row.split' is ignored.", call. = FALSE)
        }
      } else {
        row.split.parameter = collect.row.info(columns = as.character(row.split)[1])[[1]]
      }
    }



    ### ------------------------------------------------------------------- clustering
    if (clust.rows == TRUE & nrow(final.mat) > 1) {
      row.clust = stats::hclust(d = stats::dist(x = final.mat,
                                                method = distance.method),
                                method = clustering.method)
      row.clust$call = "hclust(d = dist(x = counts.matrix, method = distance.method), method = clustering.method)"
    } else {
      row.clust = NULL
    }


    if (clust.columns == TRUE & ncol(final.mat) > 1) {
      columns.clust = stats::hclust(d = stats::dist(x = t(final.mat),
                                                    method = distance.method),
                                    method = clustering.method)
      columns.clust$call = "hclust(d = dist(x = t(counts.matrix), method = distance.method), method = clustering.method)"
    } else {
      columns.clust = NULL
    }


    ## When the heatmap is split by a discrete variable the clustering must be recomputed
    ## within each block: ComplexHeatmap gets the clustering parameters instead of the
    ## hclust objects computed above, which are exported anyway in the final object.
    if (is.null(row.clust)) {
      row.cluster.parameter = FALSE
    } else if (!is.null(row.split.parameter) & !is.numeric(row.split.parameter)) {
      row.cluster.parameter = TRUE
    } else {
      row.cluster.parameter = row.clust
    }

    if (is.null(columns.clust)) {
      column.cluster.parameter = FALSE
    } else if (!is.null(column.split.parameter) & !is.numeric(column.split.parameter)) {
      column.cluster.parameter = TRUE
    } else {
      column.cluster.parameter = columns.clust
    }



    ### ------------------------------------------------------------------- protein IDs
    if (!is.null(protein.names.pattern)) {
      if (!("character" %in% class(protein.names.pattern))) {
        stop("The 'protein.names.pattern' must be a character indicating a regular expression to remove from the protein IDs.", call. = FALSE)
      }

      rownames(final.mat) = gsub(protein.names.pattern, "", rownames(final.mat))
      if (!is.null(row.clust)) {row.clust$labels = gsub(protein.names.pattern, "", row.clust$labels)}
    }



    ### ------------------------------------------------------------------- colors of the cells
    if (length(color.limits) != 2) {
      stop("The 'color.limits' must be a numeric vector of length 2, indicating lower and upper limit of the color scale.", call. = FALSE)
    }

    if (scaled == TRUE) {
      max.score = max(abs(final.mat), na.rm = TRUE)
      lower.limit = ifelse(is.na(color.limits[1]), -max.score, color.limits[1])
      upper.limit = ifelse(is.na(color.limits[2]), max.score, color.limits[2])

      if (!all(is.finite(c(lower.limit, upper.limit))) | lower.limit >= upper.limit) {
        lower.limit = -1
        upper.limit = 1
      }

      heatmap.colors = circlize::colorRamp2(breaks = c(lower.limit, 0, upper.limit),
                                            colors = c(low.color, mid.color, high.color))
    } else {
      lower.limit = ifelse(is.na(color.limits[1]), min(final.mat, na.rm = TRUE), color.limits[1])
      upper.limit = ifelse(is.na(color.limits[2]), max(final.mat, na.rm = TRUE), color.limits[2])

      if (!all(is.finite(c(lower.limit, upper.limit)))) {
        lower.limit = 0
        upper.limit = 1
      }

      if (lower.limit >= upper.limit) {upper.limit = lower.limit + 1}

      heatmap.colors = circlize::colorRamp2(breaks = seq(lower.limit, upper.limit, length.out = length(palette)),
                                            colors = palette)
    }



    ### ------------------------------------------------------------------- heatmap
    if (is.null(use.raster)) {use.raster = nrow(final.mat) > 2000}

    heatmap =
      ComplexHeatmap::Heatmap(matrix = final.mat,
                              name = scale.legend.title,
                              col = heatmap.colors,
                              na_col = na.color,
                              rect_gp = grid::gpar(col = cell.border.color, lwd = cell.border.width),
                              border = heatmap.border,
                              column_title = title,
                              cluster_rows = row.cluster.parameter,
                              cluster_columns = column.cluster.parameter,
                              clustering_distance_rows = distance.method,
                              clustering_distance_columns = distance.method,
                              clustering_method_rows = clustering.method,
                              clustering_method_columns = clustering.method,
                              show_row_dend = !is.null(row.clust),
                              show_column_dend = !is.null(columns.clust),
                              row_split = row.split.parameter,
                              column_split = column.split.parameter,
                              show_row_names = show.protein.names,
                              show_column_names = show.sample.names,
                              row_names_side = ifelse(row.annotation.side == "left", "right", "left"),
                              top_annotation = if (column.annotation.side == "top") {column.annotation.object} else {NULL},
                              bottom_annotation = if (column.annotation.side == "bottom") {column.annotation.object} else {NULL},
                              left_annotation = if (row.annotation.side == "left") {row.annotation.object} else {NULL},
                              right_annotation = if (row.annotation.side == "right") {row.annotation.object} else {NULL},
                              use_raster = use.raster)



    ##############################################
    ### Export heatmap object
    DEprot.counts.heatmap.object =
      new(Class = "DEprot.counts.heatmap",
          heatmap = heatmap,
          row.cluster = row.clust,
          column.cluster = columns.clust)

    return(DEprot.counts.heatmap.object)
  } # END of function
