#' @title normalize.counts
#'
#' @description Function that allows for the tail-robust quantile normalization of the counts using the \href{https://analyticalsciencejournals.onlinelibrary.wiley.com/doi/full/10.1002/pmic.202000068}{MBQN package}.
#'
#' @param DEprot.object A \code{DEprot object}, as generated by \link{load.counts}.
#' @param balancing.function A string indicating the function to use to balance the quantile normalization. Default: \code{"median"}.
#' @param NRI.RI.ratio.threshold Value indicating the NRI/RI (nearly rank invariant (NRI)/rank invariant (RI)) ratio threshold. Default: \code{0.5}.
#' @param overwrite.normalization Logical value to indicate whether, in the case already available, the table of normalized counts should be overwritten. Default: \code{FALSE}.
#'
#' @seealso \link{load.counts}, \href{https://analyticalsciencejournals.onlinelibrary.wiley.com/doi/full/10.1002/pmic.202000068}{MBQN package}.
#'
#' @return A \code{DEprot} object. A boxplot showing the distribution of the protein intensity after normalization for each sample is added to the slot (\code{boxplot.norm}).
#'
#' @import dplyr
#' @import ggplot2
#' @importFrom MBQN mbqnNRI
#' @importFrom reshape2 melt
#' @import ggtext
#'
#' @author Sebastian Gregoricchio
#'
#' @examples
#' normalize.counts(DEprot.object = DEprot::test.toolbox$dpo.raw)
#'
#'
#' @export normalize.counts


normalize.counts =
  function(DEprot.object,
           balancing.function = "median",
           NRI.RI.ratio.threshold = 0.5,
           overwrite.normalization = FALSE) {

    # ### Libraries
    # require(dplyr)
    # require(ggplot2)


    ### check object
    if (!("DEprot" %in% class(DEprot.object))) {
      stop("The input must be an object of class 'DEprot'.")
      #return(DEprot.object)
    }

    ### Check if normalization already available
    if (DEprot.object@normalized == TRUE) {
      if (overwrite.normalization == FALSE) {
        stop(paste0("The 'DEprot' object contains already a normalized table.\n",
                    "       If you wish to overwrite the normalization, set the 'overwrite.normalization = TRUE'."))
        #return(DEprot.object)
      } else if (is.null(DEprot.object@raw.counts)) {
        stop("You asked to overwrite the normalized counts, but not 'raw.counts' are available in the object.")
        #return(DEprot.object)
      }
    }


    ### Run normalization
    norm.cnt = MBQN::mbqnNRI(as.matrix(DEprot.object@raw.counts),
                             FUN = balancing.function,
                             low_thr = NRI.RI.ratio.threshold,
                             verbose = FALSE)

    # Add counts and method to DEprot object
    DEprot.object@norm.counts = norm.cnt
    DEprot.object@normalized = TRUE
    DEprot.object@normalization.method =
      data.frame(param = c("package", "method", "balanced", "function", "NRI/RI ratio threshold"),
                 value = c("MBQN", "Quantile normalization",
                           ifelse(is.null(balancing.function), yes = FALSE, no = TRUE),
                           ifelse("character" %in% class(balancing.function), yes = balancing.function, no = NA),
                           NRI.RI.ratio.threshold))


    ### Generate normalized boxplot
    # melt counts table
    melt.norm.cnt =
      suppressMessages(reshape2::melt(as.data.frame(DEprot.object@norm.counts))) %>%
      dplyr::mutate(variable = factor(variable, levels = colnames(DEprot.object@norm.counts)))

    # compute stats
    norm.cnt.stats =
      melt.norm.cnt %>%
      dplyr::group_by(variable) %>%
      dplyr::summarise(min = min(value, na.rm = TRUE),
                       max = max(value, na.rm = TRUE))

    boxplot.norm =
      ggplot() +
      geom_violin(data = melt.norm.cnt,
                  mapping = aes(x = variable,
                                y = value,
                                group = variable),
                  width = 0.75,
                  alpha = 0.75,
                  fill = "purple",
                  color = NA) +
      geom_boxplot(data = melt.norm.cnt,
                   mapping = aes(x = variable,
                                 y = value,
                                 group = variable),
                   fill = "white",
                   color = "purple4",
                   width = 0.15,
                   outlier.color = "black",
                   outlier.stroke = NA,
                   outlier.size = 2,
                   outlier.alpha = 0.25) +
      geom_line(data = data.frame(norm.cnt.stats),
                mapping = aes(x = variable,
                              y = max,
                              group = 1),
                color = "indianred",
                linetype = 2,
                inherit.aes = FALSE) +
      geom_line(data = data.frame(norm.cnt.stats),
                mapping = aes(x = variable,
                              y = min,
                              group = 1),
                color = "steelblue",
                linetype = 2,
                inherit.aes = FALSE) +
      ylab(ifelse(is.null(DEprot.object@log.base),
                  yes = "Intensity",
                  no = paste0(ifelse(DEprot.object@log.base == exp(1),
                                     yes = "ln", no = paste0("log~",DEprot.object@log.base,"~")),
                              "(Intensity)"))) +
      ggtitle("**Normalized**",
              subtitle = paste0("*",DEprot.object@normalization.method[2,2],", ",
                                ifelse(DEprot.object@normalization.method[3,2] == TRUE,
                                       yes = paste0(DEprot.object@normalization.method[4,2], " balanced"),
                                       no = "unbalanced"),
                                " [MBQN]*")) +
      xlab("Sample") +
      theme_classic() +
      theme(axis.text.y = element_text(color = "black"),
            axis.text.x = element_text(color = "black", hjust = 1, angle = 30),
            axis.title = ggtext::element_markdown(color = "black"),
            axis.ticks.y = element_line(color = "black"),
            axis.ticks.x = element_blank(),
            plot.title = ggtext::element_markdown(hjust = 0.5),
            plot.subtitle = ggtext::element_markdown(hjust = 0.5),
            aspect.ratio = 10/ncol(norm.cnt))

    # Assign the boxplot
    DEprot.object@boxplot.norm = boxplot.norm

    return(DEprot.object)
  } #END function
