#' @title perform.PCoA
#'
#' @description This function performs a Principal Coordinate Analysis (PCoA, also known as classical
#' Multi-Dimensional Scaling) starting from the sample dissimilarities computed by \link{plot.correlation.heatmap}.
#' Differently from \link{perform.PCA}, which always works on euclidean distances between samples, PCoA allows the use of
#' correlation-based dissimilarities (\code{1 - correlation}), which are frequently more robust for LFQ intensities
#' since they emphasize the co-variation profile of the samples rather than the absolute intensity magnitude.
#'
#' @param DEprot.correlation.object An object of class \code{DEprot.correlation}, as generated by \link{plot.correlation.heatmap}.
#' @param DEprot.object Optional object of class \code{DEprot} or \code{DEprot.analyses} used to compute the protein-vs-axis projections (\code{axis.loadings}). It must be the same object used to generate the \code{DEprot.correlation.object}. Default: \code{NULL} (no protein projection computed).
#' @param n.axes Integer indicating the number of principal coordinates to compute. It cannot exceed \code{n_samples - 1}. Default: \code{NULL} (all the computable axes, \code{n_samples - 1}).
#' @param correlation.method String indicating the correlation method that was used to generate the \code{DEprot.correlation} object ('pearson', 'spearman', 'kendall'). When \code{NULL} the value is read from the \code{method} slot of the \code{DEprot.correlation} object; for objects generated before that slot existed, the method is recovered from the heatmap title and falls back to \code{"unknown"}. Default: \code{NULL}.
#' @param distance.transformation String indicating the transformation to apply to the \code{1 - correlation} dissimilarities. One among: 'none' (dissimilarities used as they are stored in the \code{DEprot.correlation} object), 'sqrt' (\code{sqrt(1 - correlation)}, which is a proper metric and is euclidean-embeddable, hence it removes negative eigenvalues). Default: \code{"none"}.
#' @param correction String indicating the correction to apply when the dissimilarities are not euclidean-embeddable (negative eigenvalues). One among: 'none', 'cailliez' (additive constant correction, implemented by \code{stats::cmdscale(add = TRUE)}), 'lingoes' (\code{sqrt(d^2 + 2c)}, with \code{c} the absolute value of the most negative eigenvalue). Default: \code{"none"}.
#' @param PCo.x Number indicating which Principal Coordinate (PCo) to display on the x-axis of the stored scatter plot. Default: \code{2} (PCo2).
#' @param PCo.y Number indicating which Principal Coordinate (PCo) to display on the y-axis of the stored scatter plot. Default: \code{1} (PCo1).
#' @param color.column String indicating the name of the column in the \code{metadata} to use as factor for the dot colors of the stored plots. Default: \code{"column.id"} (each sample a color).
#' @param shape.column String indicating the name of the column in the \code{metadata} to use as factor for the dot shapes of the stored plots. Default: \code{NULL} (all dots).
#' @param label.column String indicating the name of the column in the \code{metadata} to use as label of the dots of the stored plots. Default: \code{NULL} (no labeling).
#' @param dot.colors Color-vector indicating the colors to use for the points of the stored combined scatter (\code{scatter.plot.123}). Default: \code{NULL} (automatic colors).
#' @param bar.color String indicating the color to use for the bar fill of the cumulative plot. Default: \code{"steelblue"}.
#' @param line.color String indicating the color to use for the line and dots of the cumulative curve. Default: \code{"navyblue"}.
#' @param verbose Logical value indicating whether messages regarding the euclidean-embeddability of the dissimilarities should be printed. Default: \code{TRUE}.
#'
#' @return A \code{DEprot.PCoA} object.
#'
#' @details
#' The dissimilarities are rebuilt from the \code{corr.matrix} slot of the \code{DEprot.correlation} object, so that
#' the requested \code{distance.transformation} is always applied consistently; the untransformed \code{dist} object
#' originally stored by \link{plot.correlation.heatmap} is kept in the \code{distance.input} slot for reference.\cr\cr
#' \strong{Negative eigenvalues.} \code{1 - correlation} is a valid dissimilarity but not a metric (it does not satisfy
#' the triangle inequality), therefore the resulting eigenvalues can be negative, meaning that the dissimilarities
#' cannot be perfectly embedded in a euclidean space. The function always reports the number and the magnitude of the
#' negative eigenvalues in the \code{euclidean.diagnostics} slot, and the proportions of variance are computed using
#' only the positive eigenvalues as denominator, which avoids the nonsensical percentages returned by a naive
#' \code{eig/sum(eig)}. If the negative eigenvalues are large, use \code{distance.transformation = "sqrt"}
#' (recommended, since \code{sqrt(1 - r)} is a metric and its double, \code{sqrt(2(1 - r))}, is exactly the euclidean
#' distance between standardized profiles) or one of the \code{correction} methods.\cr\cr
#' \strong{Axis selection.} The \code{importance} table includes the broken-stick expectation: axes whose proportion of
#' variance exceeds the corresponding broken-stick value are usually considered non-trivial.\cr\cr
#' \strong{Note on protein loadings.} PCoA works on the sample-by-sample dissimilarity matrix and therefore, differently
#' from a PCA, it has no native protein loadings. When a \code{DEprot.object} is provided, the projections stored in
#' \code{axis.loadings} are computed a posteriori as the correlation between each protein profile and each principal
#' coordinate; they are an interpretative aid and must not be read as PCA rotations.
#'
#' @seealso \link{plot.correlation.heatmap}, \link{plot.PCoA.scatter}, \link{perform.PCA}
#'
#' @name perform.PCoA
#'
#' @import dplyr
#' @import ggplot2
#' @import ggtext
#' @importFrom stats as.dist cmdscale cor dist
#'
#' @author Sebastian Gregoricchio
#'
#' @examples
#' # Compute the sample correlations
#' correlation <- plot.correlation.heatmap(DEprot.object = DEprot::test.toolbox$dpo.imp,
#'                                         correlation.method = "spearman")
#'
#' # Perform the Principal Coordinate Analyses (PCoA)
#' pcoa <- perform.PCoA(DEprot.correlation.object = correlation,
#'                      color.column = "condition",
#'                      shape.column = "replicate")
#'
#' # Show the stored plots
#' pcoa@scatter.plot
#' pcoa@scatter.plot.123
#' pcoa@cumulative.PCo.plot
#' pcoa@shepard.plot
#'
#' # Same, but forcing euclidean-embeddable dissimilarities
#' pcoa.sqrt <- perform.PCoA(DEprot.correlation.object = correlation,
#'                           distance.transformation = "sqrt",
#'                           color.column = "condition")
#'
#' @export perform.PCoA

perform.PCoA =
  function(DEprot.correlation.object,
           DEprot.object = NULL,
           n.axes = NULL,
           correlation.method = NULL,
           distance.transformation = "none",
           correction = "none",
           PCo.x = 2,
           PCo.y = 1,
           color.column = "column.id",
           shape.column = NULL,
           label.column = NULL,
           dot.colors = NULL,
           bar.color = "steelblue",
           line.color = "navyblue",
           verbose = TRUE) {

    ### check object
    if (!("DEprot.correlation" %in% class(DEprot.correlation.object))) {
      stop("The input must be an object of class 'DEprot.correlation', as generated by 'plot.correlation.heatmap'.")
    }


    ### check parameters
    distance.transformation = tolower(distance.transformation)
    correction = tolower(correction)

    if (!(distance.transformation %in% c("none", "sqrt"))) {
      stop("The 'distance.transformation' is not recognized. Choose one among: 'none', 'sqrt'.")
    }

    if (!(correction %in% c("none", "cailliez", "lingoes"))) {
      stop("The 'correction' is not recognized. Choose one among: 'none', 'cailliez', 'lingoes'.")
    }


    ### Collect the correlation matrix and the metadata
    corr.mat = DEprot.correlation.object@corr.matrix

    if (is.null(corr.mat)) {
      stop("The 'corr.matrix' slot of the DEprot.correlation object is empty.")
    }

    if (nrow(corr.mat) < 3) {
      stop(paste0("At least 3 samples are required to compute a PCoA (", nrow(corr.mat), " provided)."))
    }

    PCoA.meta = DEprot.correlation.object@corr.metadata


    ### Recover the correlation method
    # priority: (1) explicit argument, (2) the 'method' slot of the DEprot.correlation object,
    #           (3) fallback parsing of the heatmap title (for objects generated before the slot existed)
    if (is.null(correlation.method)) {
      slot.method = tryCatch(DEprot.correlation.object@method, error = function(e) {NULL})

      if (!is.null(slot.method) && length(slot.method) == 1 && !is.na(slot.method) && nzchar(slot.method)) {
        correlation.method = tolower(slot.method)
      } else {
        # legacy fallback: recover from the heatmap title
        corr.title = tryCatch(tolower(paste(DEprot.correlation.object@heatmap$labels$title, collapse = " ")),
                              error = function(e) {""})
        detected = c("pearson", "spearman", "kendall")[c("pearson", "spearman", "kendall") %in%
                                                         unlist(strsplit(gsub("[^a-z]", " ", corr.title), " +"))]
        correlation.method = ifelse(length(detected) == 1, detected, "unknown")
      }
    } else {
      correlation.method = tolower(correlation.method)
      if (!(correlation.method %in% c("pearson", "spearman", "kendall"))) {
        stop("The 'correlation.method' is not supported. Choose one among: 'pearson', 'spearman', 'kendall'.")
      }
    }


    ### Build the dissimilarities
    # rebuilt from the correlation matrix so that the transformation is applied consistently;
    # the original dist object is anyway kept in the 'distance.input' slot
    diss.mat = 1 - corr.mat

    if (distance.transformation == "sqrt") {
      diss.mat[diss.mat < 0] = 0  # numerical safety (correlations marginally > 1)
      diss.mat = sqrt(diss.mat)
      distance.method = "sqrt(1 - correlation.matrix)"
    } else {
      distance.method = "1 - correlation.matrix"
    }

    diag(diss.mat) = 0
    distance = stats::as.dist(diss.mat)


    ### Apply the correction for non-euclidean dissimilarities (if requested)
    add.constant = FALSE

    if (correction == "lingoes") {
      distance = .lingoes.correction(distance)
      distance.method = paste0("Lingoes-corrected ", distance.method)
    } else if (correction == "cailliez") {
      add.constant = TRUE
      distance.method = paste0("Cailliez-corrected ", distance.method)
    }


    ### Define the number of axes
    max.axes = attr(distance, "Size") - 1

    if (is.null(n.axes)) {
      n.axes = max.axes
    } else {
      n.axes = min(round(n.axes, 0), max.axes)
      if (n.axes < 2) {stop("At least 2 axes must be computed.")}
    }

    ### check the axes requested for the stored scatter
    PCo.x = round(PCo.x, 0)
    PCo.y = round(PCo.y, 0)

    if (PCo.x == PCo.y) {
      stop("'PCo.x' and 'PCo.y' must indicate two different principal coordinates.")
    }

    if (max(PCo.x, PCo.y) > n.axes) {
      stop(paste0("The axes requested (PCo", PCo.x, ", PCo", PCo.y, ") exceed the number of ",
                  "principal coordinates computed (", n.axes, ")."))
    }


    ### Compute the ordination
    # the cmdscale warning on non-positive eigenvalues is suppressed because a more
    # informative diagnostic is generated below and stored in 'euclidean.diagnostics'
    cs = suppressWarnings(stats::cmdscale(d = distance,
                                          k = n.axes,
                                          eig = TRUE,
                                          add = add.constant))

    coordinates = data.frame(cs$points)
    colnames(coordinates) = paste0("PCo", seq_len(ncol(coordinates)))

    ### when negative eigenvalues are present cmdscale returns fewer axes than requested
    n.axes.computed = ncol(coordinates)

    if (n.axes.computed < n.axes) {
      if (verbose == TRUE) {
        message(paste0("Only ", n.axes.computed, " of the ", n.axes, " principal coordinates requested ",
                       "correspond to a positive eigenvalue and could be computed."))
      }
      n.axes = n.axes.computed
    }

    if (max(PCo.x, PCo.y) > n.axes) {
      stop(paste0("The axes requested (PCo", PCo.x, ", PCo", PCo.y, ") exceed the number of ",
                  "principal coordinates that could be computed (", n.axes, ").\n",
                  "       Re-run using 'distance.transformation = \"sqrt\"' or a 'correction'."))
    }


    ### Eigenvalues and diagnostics
    # the last eigenvalue is structurally ~0 (double-centering), hence dropped
    eig = cs$eig[seq_len(max.axes)]

    # eigenvalues within +/- eig.tol of zero are treated as numerically null: this avoids
    # counting machine-precision residuals (e.g. ~1e-15 left by the Cailliez/Lingoes corrections)
    # as genuine negative eigenvalues.
    eig.tol = 1e-8 * max(abs(eig))

    positive.eig = eig[eig > eig.tol]
    negative.eig = eig[eig < -eig.tol]

    max.relative.negative = ifelse(length(negative.eig) > 0,
                                   abs(min(negative.eig)) / max(positive.eig),
                                   0)

    euclidean.diagnostics =
      list(n.negative.eigenvalues = length(negative.eig),
           sum.negative.eigenvalues = ifelse(length(negative.eig) > 0, sum(negative.eig), 0),
           max.relative.negative.eigenvalue = max.relative.negative,
           euclidean.embeddable = (length(negative.eig) == 0),
           GOF = cs$GOF,
           additive.constant = ifelse(is.null(cs$ac), NA, cs$ac))

    if (verbose == TRUE) {
      if (length(negative.eig) > 0) {
        message(paste0("The dissimilarities are not euclidean-embeddable: ", length(negative.eig),
                       " negative eigenvalue(s) detected (largest relative magnitude = ",
                       round(max.relative.negative, 4), ")."))
        if (max.relative.negative > 0.05 & distance.transformation == "none" & correction == "none") {
          message(paste0("       The negative eigenvalues are non-negligible. Consider using ",
                         "'distance.transformation = \"sqrt\"' or 'correction = \"cailliez\"'/'correction = \"lingoes\"'.\n",
                         "       The proportions of variance are computed using only the positive eigenvalues as denominator."))
        }
      }
    }


    ### Importance table
    # the proportions are computed on the positive eigenvalues only
    total.positive = sum(positive.eig)
    proportion = eig / total.positive

    # broken-stick expectation, computed on the positive eigenvalues
    n.positive = length(positive.eig)
    broken.stick = sapply(seq_len(n.positive),
                          function(i) {sum(1/seq(i, n.positive)) / n.positive})
    broken.stick = c(broken.stick, rep(NA, length(eig) - n.positive))

    importance.tb =
      data.frame(Eigenvalue = eig,
                 Proportion.of.Variance = proportion,
                 Cumulative.Proportion = cumsum(proportion),
                 Percentage.of.Variance = proportion * 100,
                 Broken.stick = broken.stick,
                 Positive.eigenvalue = (eig > eig.tol)) %>%
      dplyr::mutate(PCo = factor(seq_len(length(eig)), levels = seq_len(length(eig))),
                    Above.broken.stick = (Proportion.of.Variance > Broken.stick))

    rownames(importance.tb) = paste0("PCo", seq_len(nrow(importance.tb)))


    ### Combine coordinates with the metadata
    combo.tb = dplyr::left_join(dplyr::mutate(coordinates,
                                              column.id = rownames(coordinates)),
                                PCoA.meta,
                                by = "column.id")


    ### Protein-vs-axis projections (optional)
    axis.loadings = NULL

    if (!is.null(DEprot.object)) {
      axis.loadings = .PCoA.axis.loadings(DEprot.object = DEprot.object,
                                          which.data = DEprot.correlation.object@data.used,
                                          coordinates = coordinates,
                                          verbose = verbose)
    }


    ### Build the object (plots added afterwards)
    DEprot.PCoA.object =
      new(Class = "DEprot.PCoA",
          PCoA.metadata = PCoA.meta,
          sample.subset = paste(PCoA.meta$column.id, collapse = ", "),
          data.used = DEprot.correlation.object@data.used,
          correlation.method = correlation.method,
          correlation.matrix = corr.mat,
          distance.input = DEprot.correlation.object@distance,
          distance = distance,
          distance.method = distance.method,
          cmdscale = cs,
          PCos = combo.tb,
          eigenvalues = eig,
          importance = importance.tb,
          euclidean.diagnostics = euclidean.diagnostics,
          axis.loadings = axis.loadings,
          scatter.plot = NULL,
          scatter.plot.123 = NULL,
          cumulative.PCo.plot = NULL,
          shepard.plot = NULL,
          parameters = list(n.axes = n.axes,
                            distance.transformation = distance.transformation,
                            correction = correction,
                            data.used = DEprot.correlation.object@data.used,
                            PCo.x = PCo.x,
                            PCo.y = PCo.y,
                            color.column = color.column,
                            shape.column = shape.column,
                            label.column = label.column,
                            sample.subset = DEprot.correlation.object@sample.subset))


    ##################### PLOTS ##########################

    ### Scatter requested by the user
    DEprot.PCoA.object@scatter.plot =
      plot.PCoA.scatter(DEprot.PCoA.object = DEprot.PCoA.object,
                        PCo.x = PCo.x,
                        PCo.y = PCo.y,
                        color.column = color.column,
                        shape.column = shape.column,
                        label.column = label.column)

    ### Combined PCo1-vs-PCo2 / PCo3-vs-PCo2 scatter
    if (n.axes >= 3) {
      DEprot.PCoA.object@scatter.plot.123 =
        plot.PCoA.scatter.123(DEprot.PCoA.object = DEprot.PCoA.object,
                              color.column = color.column,
                              shape.column = shape.column,
                              label.column = label.column,
                              dot.colors = dot.colors)
    } else {
      if (verbose == TRUE) {
        message("Less than 3 axes available: the combined 'scatter.plot.123' will not be generated.")
      }
    }


    ### Cumulative variance plot
    DEprot.PCoA.object@cumulative.PCo.plot =
      plot.PCoA.cumulative(DEprot.PCoA.object = DEprot.PCoA.object,
                           bar.color = bar.color,
                           line.color = line.color,
                           broken.stick = TRUE)


    ### Shepard-like diagnostic plot (embedding quality)
    reconstructed = stats::dist(as.matrix(coordinates[, c(min(PCo.x, PCo.y), max(PCo.x, PCo.y))]))
    reconstructed.full = stats::dist(as.matrix(coordinates))

    shepard.tb = data.frame(observed = as.vector(distance),
                            reconstructed.2D = as.vector(reconstructed),
                            reconstructed.all = as.vector(reconstructed.full))

    shepard.correlation = suppressWarnings(stats::cor(shepard.tb$observed,
                                                      shepard.tb$reconstructed.2D,
                                                      method = "pearson",
                                                      use = "complete.obs"))

    DEprot.PCoA.object@shepard.plot =
      ggplot(data = shepard.tb,
             aes(x = observed, y = reconstructed.2D)) +
      geom_abline(slope = 1, intercept = 0, color = "gray", linetype = 2) +
      geom_point(size = 2, color = line.color, alpha = 0.7, stroke = NA) +
      xlab("Input dissimilarity") +
      ylab(paste0("Distance in the PCo", min(PCo.x, PCo.y), "-PCo", max(PCo.x, PCo.y), " plane")) +
      ggtitle(label = "**Embedding quality**",
              subtitle = paste0("*Pearson's r = ", round(shepard.correlation, 3),
                                " &middot; dashed line: 1:1*")) +
      theme_classic() +
      theme(aspect.ratio = 1,
            axis.line = element_blank(),
            axis.ticks = element_line(color = "black"),
            axis.text = element_text(color = "black"),
            panel.border = element_rect(color = "black", fill = NA),
            plot.title = ggtext::element_markdown(color = "black", hjust = 0.5),
            plot.subtitle = ggtext::element_markdown(color = "black", hjust = 0.5))

    DEprot.PCoA.object@euclidean.diagnostics$shepard.correlation = shepard.correlation


    return(DEprot.PCoA.object)
  } # END function




## ==================================================================== ##
##  Internal helpers
##  (to be moved to 'R/internal_functions.R' if preferred)
## ==================================================================== ##

#' @title .lingoes.correction
#' @description Internal. Applies the Lingoes (1971) correction to a \code{dist} object, i.e.
#' \code{d_prime = sqrt(d^2 + 2*c)} for \code{i != j}, where \code{c} is the absolute value of the most
#' negative eigenvalue of the Gower-centered matrix. This makes the dissimilarities euclidean-embeddable.
#' @param d An object of class \code{dist}.
#' @return An object of class \code{dist}.
#' @importFrom stats as.dist
#' @keywords internal

.lingoes.correction =
  function(d) {
    n = attr(d, "Size")
    D = as.matrix(d)

    ## Gower double-centering: G = -0.5 * J %*% D^2 %*% J
    J = diag(n) - matrix(1/n, nrow = n, ncol = n)
    G = -0.5 * (J %*% (D^2) %*% J)

    ev = eigen((G + t(G))/2, symmetric = TRUE, only.values = TRUE)$values
    c1 = min(ev)

    if (c1 >= 0) {return(d)}  # already euclidean, nothing to correct

    D.corrected = sqrt(D^2 + 2*abs(c1))
    diag(D.corrected) = 0

    return(stats::as.dist(D.corrected))
  }



#' @title .PCoA.axis.loadings
#' @description Internal. Computes the a-posteriori projection of the proteins onto the principal
#' coordinates, as the correlation between each protein profile and each axis.
#' @param DEprot.object An object of class \code{DEprot} or \code{DEprot.analyses}.
#' @param which.data String indicating the count type to use.
#' @param coordinates data.frame of the principal coordinates (samples as rows).
#' @param verbose Logical value indicating whether messages should be printed.
#' @return A data.frame of protein-vs-axis correlations.
#' @importFrom stats cor
#' @keywords internal

.PCoA.axis.loadings =
  function(DEprot.object,
           which.data,
           coordinates,
           verbose = TRUE) {

    if (!("DEprot" %in% class(DEprot.object)) & !("DEprot.analyses" %in% class(DEprot.object))) {
      warning("The 'DEprot.object' provided is not of class 'DEprot'. The protein projections will not be computed.")
      return(NULL)
    }

    ### Extract the counts
    if (tolower(which.data) == "raw") {
      mat = DEprot.object@raw.counts
    } else if (tolower(which.data) %in% c("norm", "normalized", "normal")) {
      mat = DEprot.object@norm.counts
    } else if (tolower(which.data) %in% c("imputed", "imp", "impute")) {
      mat = DEprot.object@imputed.counts
    } else if (tolower(which.data) %in% c("randomized", "random")) {
      mat = DEprot.object@random.counts
    } else {
      mat = NULL
    }

    if (is.null(mat)) {
      warning(paste0("Counts of type '", which.data, "' are not available in the 'DEprot.object'. ",
                     "The protein projections will not be computed."))
      return(NULL)
    }

    ### Match the samples used in the ordination
    samples = rownames(coordinates)

    if (!all(samples %in% colnames(mat))) {
      warning(paste0("Some of the samples used in the correlation are not available in the 'DEprot.object' counts. ",
                     "The protein projections will not be computed."))
      return(NULL)
    }

    mat = mat[, samples, drop = FALSE]

    ### Convert to log2 (same behavior of perform.PCA)
    if (!is.numeric(DEprot.object@log.base)) {
      if (verbose == TRUE) {
        message("The log.base is not numeric, linear counts are assumed. Counts will be converted to log2(score+1) values to compute the protein projections.")
      }
      mat = log2(mat + 1)
    } else if (as.numeric(DEprot.object@log.base) != 2) {
      if (verbose == TRUE) {
        message("The log.base is not 2, counts will be converted to log2 values to compute the protein projections.")
      }
      mat = log2(DEprot.object@log.base^mat)
    }

    mat[is.nan(mat)] = NA

    ### Remove non-informative proteins (constant or fully missing)
    protein.sd = apply(mat, 1, stats::sd, na.rm = TRUE)
    keep = !is.na(protein.sd) & protein.sd > 0
    mat = mat[keep, , drop = FALSE]

    if (nrow(mat) == 0) {
      warning("No protein with a non-zero variance is available. The protein projections will not be computed.")
      return(NULL)
    }

    ### Correlate each protein profile with each axis
    loadings = suppressWarnings(stats::cor(x = t(mat),
                                           y = as.matrix(coordinates),
                                           use = "pairwise.complete.obs"))

    loadings.df = data.frame(protein = rownames(loadings),
                             data.frame(loadings),
                             row.names = NULL)

    return(loadings.df)
  }
