#' @title plot.PC.scatter.123
#'
#' @description Plot combined scatter of the PCs 1-2,2-3 from an object generated by \link{perform.PCA}.
#'
#' @param DEprot.PCA.object An object of class \code{DEprot.PCA.object}, as generated by \link{perform.PCA}.
#' @param color.column String indicating the name of the column in the \code{metadata} to use as factor for the dot colors. Default: \code{"column.id"} (each sample a color).
#' @param shape.column String indicating the name of the column in the \code{metadata} to use as factor for the dot shapes. Default: \code{NULL} (all dots).
#' @param label.column String indicating the name of the column in the \code{metadata} to use as label of the dots. Default: \code{NULL} (no labeling).
#' @param dot.colors Color-vector indicating the colors to use for the points in the plot. If \code{NULL} (default) or the number of colors is lower than the required, automatic colors will be assign using the \code{rainbow} function. Default: \code{NULL}.
#' @param title String indicating a title to add to the plot (markdown syntax supported). Default: \code{NULL} (no)
#' @param plot.zero.line.y.12 Logical value to indicate whether to plot two gray dashed lines in correspondence of y=0 in the PC1-vs-PC2 plot. Default: \code{TRUE}.
#' @param plot.zero.line.x.12 Logical value to indicate whether to plot two gray dashed lines in correspondence of x=0 in the PC1-vs-PC2 plot. Default: \code{TRUE}.
#' @param plot.zero.line.y.23 Logical value to indicate whether to plot two gray dashed lines in correspondence of y=0 in the PC2-vs-PC3 plot. Default: \code{TRUE}.
#' @param plot.zero.line.x.23 Logical value to indicate whether to plot two gray dashed lines in correspondence of x=0 in the PC2-vs-PC3 plot. Default: \code{TRUE}.
#'
#' @return A patchwork object result of a combination of two ggplot objects.
#'
#' @seealso \link{perform.PCA} and \link{plot.PC.scatter}
#'
#' @name plot.PC.scatter.123
#'
#' @export plot.PC.scatter.123

plot.PC.scatter.123 =
  function(DEprot.PCA.object,
           color.column = "column.id",
           shape.column = NULL,
           label.column = NULL,
           dot.colors = NULL,
           title = NULL,
           plot.zero.line.y.12 = TRUE,
           plot.zero.line.x.12 = TRUE,
           plot.zero.line.y.23 = TRUE,
           plot.zero.line.x.23 = TRUE) {


    ### Libraries
    require(ggplot2)


    ### check object
    if (!("DEprot.PCA" %in% class(DEprot.PCA.object))) {
      return(warning("The input must be an object of class 'DEprot.PCA'."))
    }


    ### check feature/aes column
    if (!(color.column %in% colnames(DEprot.PCA.object@PCs))) {
      return(warning(paste0("The color column '", color.column, "' is not present in the PC analyses table.\n",
                            "Available columns: ", paste0(colnames(DEprot.PCA.object@PCs)[!grepl("^PC", colnames(DEprot.PCA.object@PCs))],
                                                          collapse = ", "))))
    }


    if (!is.null(shape.column)) {
      if (!(shape.column %in% colnames(DEprot.PCA.object@PCs))) {
        return(warning(paste0("The shape column '", shape.column, "' is not present in the PC analyses table.\n",
                              "Available columns: ", paste0(colnames(DEprot.PCA.object@PCs)[!grepl("^PC", colnames(DEprot.PCA.object@PCs))],
                                                            collapse = ", "))))
      } else {
        shape.scores = DEprot.PCA.object@PCs[,shape.column]
        shape.label = guide_legend(title = stringr::str_to_title(shape.column))
      }
    } else {
      shape.scores = "Samples"
      shape.label = "none"
    }


    if (!is.null(label.column)) {
      if (!(label.column %in% colnames(DEprot.PCA.object@PCs))) {
        return(warning(paste0("The label column '", label.column, "' is not present in the PC analyses table.\n",
                              "Available columns: ", paste0(colnames(DEprot.PCA.object@PCs)[!grepl("^PC", colnames(DEprot.PCA.object@PCs))],
                                                            collapse = ", "))))
      }
    }



    ### Define/check colors
    # Get length and labels of colors
    if (is.factor(DEprot.PCA.object@PCA.metadata[,color.column])) {
      color.labels = levels(DEprot.PCA.object@PCA.metadata[,color.column])
    } else {
      color.labels = unique(DEprot.PCA.object@PCA.metadata[,color.column])
    }

    # assign/collect colors
    if (is.null(dot.colors) | length(dot.colors) < length(color.labels)) {
      if (!is.null(dot.colors)) {message(paste0("The number of 'dot.colors' provided is lower the required values (",length(color.labels),").\nValues will be assigned automatically."))}
      scatter.colors = rainbow(n = length(color.labels), s = 0.5)
    } else {
      scatter.colors = dot.colors
    }

    # assign names to the colors if necessary
    if (is.null(names(scatter.colors))) {
      names(scatter.colors) = color.labels
    }



    ##### Generate plots
    pca.1.2 =
      DEprot::plot.PC.scatter(DEprot.PCA.object,
                              PC.x = 1,
                              PC.y = 2,
                              color.column = color.column,
                              shape.column = shape.column,
                              label.column = label.column,
                              plot.zero.lines = F) +
      scale_color_manual(values = scatter.colors) +
      theme(legend.position = "none")

    pca.2.3 =
      DEprot::plot.PC.scatter(DEprot.PCA.object,
                              PC.x = 3,
                              PC.y = 2,
                              color.column = color.column,
                              shape.column = shape.column,
                              label.column = label.column,
                              plot.zero.lines = F) +
      ylab(NULL) +
      scale_color_manual(values = scatter.colors)



    ## Add zero-lines
    if (plot.zero.line.y.12 == T) {pca.1.2 = pca.1.2 + geom_hline(yintercept = 0, linetype = 2, color = "gray")}
    if (plot.zero.line.y.23 == T) {pca.2.3 = pca.2.3 + geom_hline(yintercept = 0, linetype = 2, color = "gray")}

    if (plot.zero.line.x.12 == T) {pca.1.2 = pca.1.2 + geom_vline(xintercept = 0, linetype = 2, color = "gray")}
    if (plot.zero.line.x.23 == T) {pca.2.3 = pca.2.3 + geom_vline(xintercept = 0, linetype = 2, color = "gray")}


    ### Export combined plot
    if (is.null(title)) {
      return(patchwork::wrap_plots(pca.1.2, pca.2.3, nrow = 1))
    } else {
      return(patchwork::wrap_plots(pca.1.2, pca.2.3, nrow = 1) +
               patchwork::plot_annotation(title = title,
                                          theme = theme(plot.title = ggtext::element_markdown(hjust = 0.5)))
             )
    }

  } # END FUNCTION
