#' @title plot.PCoA.scatter
#'
#' @description Plot a scatter of the principal coordinates from an object generated by \link{perform.PCoA}.
#'
#' @param DEprot.PCoA.object An object of class \code{DEprot.PCoA}, as generated by \link{perform.PCoA}.
#' @param PCo.x Number indicating which Principal Coordinate (PCo) to display on the x-axis. Default: \code{2} (PCo2).
#' @param PCo.y Number indicating which Principal Coordinate (PCo) to display on the y-axis. Default: \code{1} (PCo1).
#' @param color.column String indicating the name of the column in the \code{metadata} to use as factor for the dot colors. Default: \code{"column.id"} (each sample a color).
#' @param shape.column String indicating the name of the column in the \code{metadata} to use as factor for the dot shapes. Default: \code{NULL} (all dots).
#' @param label.column String indicating the name of the column in the \code{metadata} to use as label of the dots. Default: \code{NULL} (no labeling).
#' @param plot.zero.line.x Logical value to indicate whether to plot a gray dashed line in correspondence of x=0. Default: \code{TRUE}.
#' @param plot.zero.line.y Logical value to indicate whether to plot a gray dashed line in correspondence of y=0. Default: \code{TRUE}.
#'
#' @return A ggplot object.
#'
#' @details
#' The axis labels report the proportion of variance of each principal coordinate, computed using only the
#' positive eigenvalues as denominator (see \link{perform.PCoA}). Axes corresponding to a negative eigenvalue
#' have no real representation and raise an error.
#'
#' @seealso \link{perform.PCoA}, \link{plot.PCoA.scatter.123}, \link{plot.PC.scatter}
#'
#' @name plot.PCoA.scatter
#'
#' @import ggplot2
#' @importFrom stringr str_to_title
#' @import ggrepel
#'
#' @author Sebastian Gregoricchio
#'
#' @examples
#' # Compute the sample correlations and the PCoA
#' correlation <- plot.correlation.heatmap(DEprot.object = DEprot::test.toolbox$dpo.imp,
#'                                         correlation.method = "spearman")
#'
#' pcoa <- perform.PCoA(DEprot.correlation.object = correlation)
#'
#' # Plot the PCo1-vs-PCo2 scatter
#' plot.PCoA.scatter(DEprot.PCoA.object = pcoa,
#'                   PCo.x = 1,
#'                   PCo.y = 2,
#'                   color.column = "condition",
#'                   shape.column = "replicate",
#'                   label.column = "replicate")
#'
#' @export plot.PCoA.scatter

plot.PCoA.scatter =
  function(DEprot.PCoA.object,
           PCo.x = 2,
           PCo.y = 1,
           color.column = "column.id",
           shape.column = NULL,
           label.column = NULL,
           plot.zero.line.x = TRUE,
           plot.zero.line.y = TRUE) {


    ### check object
    if (!("DEprot.PCoA" %in% class(DEprot.PCoA.object))) {
      stop("The input must be an object of class 'DEprot.PCoA'.")
    }

    ### harmonized access to the ordination slots
    ord = .ordination.slots(DEprot.PCoA.object)


    ### Generate the plot (shared body with plot.PC.scatter)
    PCoA.plot =
      .ordination.scatter(coordinates = ord$coordinates,
                          importance = ord$importance,
                          axis.prefix = ord$axis.prefix,
                          axis.x = PCo.x,
                          axis.y = PCo.y,
                          color.column = color.column,
                          shape.column = shape.column,
                          label.column = label.column,
                          plot.zero.line.x = plot.zero.line.x,
                          plot.zero.line.y = plot.zero.line.y,
                          positive.axis = ord$positive.axis)

    return(PCoA.plot)
  } # END function
