#' @title plot.PC.biplot
#'
#' @description Plot a biplot of the PCs from an object generated by \link{perform.PCA}.
#' A biplot overlays sample scores (dots) with variable loadings (arrows), showing which
#' proteins contribute most to the separation of samples along the selected principal components.
#'
#' @param DEprot.PCA.object An object of class \code{DEprot.PCA}, as generated by \link{perform.PCA}.
#' @param PC.x Number indicating which Principal Component (PC) to display on the x-axis. Default: \code{2} (PC2).
#' @param PC.y Number indicating which Principal Component (PC) to display on the y-axis. Default: \code{1} (PC1).
#' @param color.column String indicating the name of the column in the \code{metadata} to use as factor for the dot colors. Default: \code{"column.id"} (each sample a color).
#' @param shape.column String indicating the name of the column in the \code{metadata} to use as factor for the dot shapes. Default: \code{NULL} (all dots).
#' @param label.column String indicating the name of the column in the \code{metadata} to use as label of the dots. Default: \code{NULL} (no labeling).
#' @param plot.zero.line.x Logical value to indicate whether to plot two gray dashed line in correspondence of x=0. Default: \code{TRUE}.
#' @param plot.zero.line.y Logical value to indicate whether to plot two gray dashed line in correspondence of y=0. Default: \code{TRUE}.
#' @param n.loadings Integer indicating the number of top contributing protein loadings (arrows) to display on the biplot. Proteins are ranked by their Euclidean distance from the origin in the selected 2D PC plane. Default: \code{10}.
#' @param loading.color String indicating the color used for the loading arrows and labels. Default: \code{"turquoise4"}.
#' @param loading.arrow.size Numeric value indicating the linewidth of the loading arrows. Default: \code{0.6}.
#' @param loading.label.size Numeric value indicating the font size of the loading labels. Default: \code{3}.
#' @param loading.alpha Numeric value (0 to 1) indicating the transparency of the loading arrows and labels. Default: \code{0.7}.
#' @param loading.scale Numeric value used as a multiplier to manually adjust the scaling of the loading arrows relative to the sample scores. Values > 1 make arrows longer, values < 1 make them shorter. Default: \code{0.8}.
#'
#' @return A ggplot object.
#'
#' @details
#' The function extracts protein loadings from the PCA object stored in the \code{prcomp} slot.
#' When the PCA was computed using \code{stats::prcomp} (no missing values), the protein projections
#' from \code{prcomp$rotation} are used. When the PCA was computed using \code{pcaMethods::pca} (missing values
#' present), the protein loadings from the \code{loadings} slot are used.\cr
#' In both cases, the loadings are scaled so that the arrows fit visually within the range of the
#' sample scores. Only the top \code{n.loadings} proteins (by Euclidean distance from origin in the
#' selected PC plane) are displayed to keep the plot readable.\cr
#' Gene/protein names are extracted from the row names of the loadings matrix.\cr\cr
#' \strong{Note.} The arrows of a PCA biplot are the rotation coefficients, i.e. the exact linear map between
#' the proteins and the components. They are conceptually different from the arrows displayed by
#' \link{plot.PCoA.biplot}, which are an a-posteriori projection.
#'
#' @seealso \link{perform.PCA}, \link{plot.PC.scatter}, \link{plot.PCoA.biplot}
#'
#' @name plot.PC.biplot
#'
#' @import ggplot2
#' @importFrom stringr str_to_title
#' @import ggrepel
#'
#' @author Sebastian Gregoricchio
#'
#' @examples
#' # Perform Principal Component Analyses (PCA)
#' pca <- perform.PCA(DEprot.object = DEprot::test.toolbox$dpo.imp)
#'
#' # Plot biplot of PC1-vs-PC2
#' plot.PC.biplot(DEprot.PCA.object = pca,
#'                color.column = "condition",
#'                shape.column = "replicate",
#'                n.loadings = 10)
#'
#' # Plot biplot of PC2-vs-PC3 with more loadings
#' plot.PC.biplot(DEprot.PCA.object = pca,
#'                PC.x = 3,
#'                PC.y = 2,
#'                color.column = "condition",
#'                n.loadings = 15,
#'                loading.color = "gray30")
#'
#' @export plot.PC.biplot

plot.PC.biplot =
  function(DEprot.PCA.object,
           PC.x = 2,
           PC.y = 1,
           color.column = "column.id",
           shape.column = NULL,
           label.column = NULL,
           plot.zero.line.x = TRUE,
           plot.zero.line.y = TRUE,
           n.loadings = 10,
           loading.color = "turquoise4",
           loading.arrow.size = 0.6,
           loading.label.size = 3,
           loading.alpha = 0.7,
           loading.scale = 0.8) {


    ### check object
    if (!("DEprot.PCA" %in% class(DEprot.PCA.object))) {
      stop("The input must be an object of class 'DEprot.PCA'.")
    }

    ### harmonized access to the ordination slots
    ord = .ordination.slots(DEprot.PCA.object)


    ### -----------------------------------------------
    ### Extract protein loadings from the PCA object
    ### -----------------------------------------------
    pc.object = DEprot.PCA.object@prcomp

    if ("prcomp" %in% class(pc.object)) {
      # prcomp case: t(mat) = samples x proteins
      # pc$rotation = protein loadings (proteins x PCs)
      loadings.mat = data.frame(pc.object$rotation)
    } else if ("pcaRes" %in% class(pc.object)) {
      # pcaMethods case: t(mat) = samples x proteins
      # pc@loadings = protein loadings (proteins x PCs)
      loadings.mat = data.frame(pc.object@loadings)
    } else {
      stop("The PCA object stored in the 'prcomp' slot is not recognized as 'prcomp' or 'pcaRes' (pcaMethods).")
    }


    ### Check that requested PCs exist in the loadings
    pc.x.col = paste0("PC", PC.x)
    pc.y.col = paste0("PC", PC.y)

    if (!(pc.x.col %in% colnames(loadings.mat)) | !(pc.y.col %in% colnames(loadings.mat))) {
      stop(paste0("The requested PCs (", pc.x.col, ", ", pc.y.col,
                  ") are not available in the loadings matrix.\n",
                  "       Available PCs: ", paste0(colnames(loadings.mat), collapse = ", ")))
    }


    ### Build loadings data.frame
    loadings.df = data.frame(variable = rownames(loadings.mat),
                             loading.x = loadings.mat[, pc.x.col],
                             loading.y = loadings.mat[, pc.y.col])


    ### Rank and rescale the loadings (shared with plot.PCoA.biplot)
    scaled = .scale.loadings(loadings.df = loadings.df,
                             scores.x = ord$coordinates[,pc.x.col],
                             scores.y = ord$coordinates[,pc.y.col],
                             n.loadings = n.loadings,
                             loading.scale = loading.scale)


    ### -----------------------------------------------
    ### Build the biplot (arrows are inserted below the points)
    ### -----------------------------------------------
    biplot =
      .ordination.scatter(coordinates = ord$coordinates,
                          importance = ord$importance,
                          axis.prefix = ord$axis.prefix,
                          axis.x = PC.x,
                          axis.y = PC.y,
                          color.column = color.column,
                          shape.column = shape.column,
                          label.column = label.column,
                          plot.zero.line.x = plot.zero.line.x,
                          plot.zero.line.y = plot.zero.line.y,
                          positive.axis = ord$positive.axis,
                          extra.layers = .loading.layers(loadings.top = scaled$top,
                                                         loading.color = loading.color,
                                                         loading.arrow.size = loading.arrow.size,
                                                         loading.label.size = loading.label.size,
                                                         loading.alpha = loading.alpha))

    return(biplot)
  } # END function
