#' @title plot.PC.biplot
#'
#' @description Plot a biplot of the PCs from an object generated by \link{perform.PCA}.
#' A biplot overlays sample scores (dots) with variable loadings (arrows), showing which
#' proteins contribute most to the separation of samples along the selected principal components.
#'
#' @param DEprot.PCA.object An object of class \code{DEprot.PCA}, as generated by \link{perform.PCA}.
#' @param PC.x Number indicating which Principal Component (PC) to display on the x-axis. Default: \code{2} (PC2).
#' @param PC.y Number indicating which Principal Component (PC) to display on the y-axis. Default: \code{1} (PC1).
#' @param color.column String indicating the name of the column in the \code{metadata} to use as factor for the dot colors. Default: \code{"column.id"} (each sample a color).
#' @param shape.column String indicating the name of the column in the \code{metadata} to use as factor for the dot shapes. Default: \code{NULL} (all dots).
#' @param label.column String indicating the name of the column in the \code{metadata} to use as label of the dots. Default: \code{NULL} (no labeling).
#' @param plot.zero.line.x Logical value to indicate whether to plot two gray dashed line in correspondence of x=0. Default: \code{TRUE}.
#' @param plot.zero.line.y Logical value to indicate whether to plot two gray dashed line in correspondence of y=0. Default: \code{TRUE}.
#' @param n.loadings Integer indicating the number of top contributing protein loadings (arrows) to display on the biplot. Proteins are ranked by their Euclidean distance from the origin in the selected 2D PC plane. Default: \code{10}.
#' @param loading.color String indicating the color used for the loading arrows and labels. Default: \code{"turquoise4"}.
#' @param loading.arrow.size Numeric value indicating the linewidth of the loading arrows. Default: \code{0.6}.
#' @param loading.label.size Numeric value indicating the font size of the loading labels. Default: \code{3}.
#' @param loading.alpha Numeric value (0 to 1) indicating the transparency of the loading arrows and labels. Default: \code{0.7}.
#' @param loading.scale Numeric value used as a multiplier to manually adjust the scaling of the loading arrows relative to the sample scores. Values > 1 make arrows longer, values < 1 make them shorter. Default: \code{0.8}.
#'
#' @return A ggplot object.
#'
#' @details
#' The function extracts protein loadings from the PCA object stored in the \code{prcomp} slot.
#' When the PCA was computed using \code{stats::prcomp} (no missing values), the protein projections
#' from \code{prcomp$x} are used. When the PCA was computed using \code{pcaMethods::pca} (missing values
#' present), the protein loadings from the \code{loadings} slot are used.\cr
#' In both cases, the loadings are scaled so that the arrows fit visually within the range of the
#' sample scores. Only the top \code{n.loadings} proteins (by Euclidean distance from origin in the
#' selected PC plane) are displayed to keep the plot readable.\cr
#' Gene/protein names are extracted from the row names of the loadings matrix.
#'
#' @seealso \link{perform.PCA}, \link{plot.PC.scatter}
#'
#' @name plot.PC.biplot
#'
#' @import ggplot2
#' @importFrom stringr str_to_title
#' @import ggrepel
#'
#' @author Sebastian Gregoricchio
#'
#' @examples
#' # Perform Principal Component Analyses (PCA)
#' pca <- perform.PCA(DEprot.object = DEprot::test.toolbox$dpo.imp)
#'
#' # Plot biplot of PC1-vs-PC2
#' plot.PC.biplot(DEprot.PCA.object = pca,
#'                color.column = "condition",
#'                shape.column = "replicate",
#'                n.loadings = 10)
#'
#' # Plot biplot of PC2-vs-PC3 with more loadings
#' plot.PC.biplot(DEprot.PCA.object = pca,
#'                PC.x = 3,
#'                PC.y = 2,
#'                color.column = "condition",
#'                n.loadings = 15,
#'                loading.color = "gray30")
#'
#' @export plot.PC.biplot

plot.PC.biplot =
  function(DEprot.PCA.object,
           PC.x = 2,
           PC.y = 1,
           color.column = "column.id",
           shape.column = NULL,
           label.column = NULL,
           plot.zero.line.x = TRUE,
           plot.zero.line.y = TRUE,
           n.loadings = 10,
           loading.color = "turquoise4",
           loading.arrow.size = 0.6,
           loading.label.size = 3,
           loading.alpha = 0.7,
           loading.scale = 0.8) {


    ### check object
    if (!("DEprot.PCA" %in% class(DEprot.PCA.object))) {
      stop("The input must be an object of class 'DEprot.PCA'.")
    }


    ### check feature/aes column
    if (!(color.column %in% colnames(DEprot.PCA.object@PCs))) {
      stop(paste0("The color column '", color.column, "' is not present in the PC analyses table.\n",
                  "Available columns: ", paste0(colnames(DEprot.PCA.object@PCs)[!grepl("^PC", colnames(DEprot.PCA.object@PCs))],
                                                collapse = ", ")))
    }


    if (!is.null(shape.column)) {
      if (!(shape.column %in% colnames(DEprot.PCA.object@PCs))) {
        stop(paste0("The shape column '", shape.column, "' is not present in the PC analyses table.\n",
                    "       Available columns: ", paste0(colnames(DEprot.PCA.object@PCs)[!grepl("^PC", colnames(DEprot.PCA.object@PCs))],
                                                         collapse = ", ")))
      } else {
        shape.scores = DEprot.PCA.object@PCs[,shape.column]
        shape.label = guide_legend(title = stringr::str_to_title(shape.column))
      }
    } else {
      shape.scores = "Samples"
      shape.label = "none"
    }


    if (!is.null(label.column)) {
      if (!(label.column %in% colnames(DEprot.PCA.object@PCs))) {
        stop(paste0("The label column '", label.column, "' is not present in the PC analyses table.\n",
                    "       Available columns: ", paste0(colnames(DEprot.PCA.object@PCs)[!grepl("^PC", colnames(DEprot.PCA.object@PCs))],
                                                         collapse = ", ")))
      } else {
        show.labels = TRUE
      }
    } else {
      label.column = color.column
      show.labels = FALSE
    }


    ### Build table for plot (sample scores)
    tb = data.frame(PC.x = DEprot.PCA.object@PCs[,paste0("PC",PC.x)],
                    PC.y = DEprot.PCA.object@PCs[,paste0("PC",PC.y)],
                    color = factor(DEprot.PCA.object@PCs[,color.column]),
                    shape = factor(shape.scores),
                    label = DEprot.PCA.object@PCs[,label.column])


    ### -----------------------------------------------
    ### Extract protein loadings from the PCA object
    ### -----------------------------------------------
    pc.object = DEprot.PCA.object@prcomp

    if ("prcomp" %in% class(pc.object)) {
      # prcomp case: t(mat) = samples x proteins
      # pc$rotation = protein loadings (proteins x PCs)
      loadings.mat = data.frame(pc.object$rotation)
    } else if ("pcaRes" %in% class(pc.object)) {
      # pcaMethods case: t(mat) = samples x proteins
      # pc@loadings = protein loadings (proteins x PCs)
      loadings.mat = data.frame(pc.object@loadings)
    } else {
      stop("The PCA object stored in the 'prcomp' slot is not recognized as 'prcomp' or 'pcaRes' (pcaMethods).")
    }


    ### Check that requested PCs exist in the loadings
    pc.x.col = paste0("PC", PC.x)
    pc.y.col = paste0("PC", PC.y)

    if (!(pc.x.col %in% colnames(loadings.mat)) | !(pc.y.col %in% colnames(loadings.mat))) {
      stop(paste0("The requested PCs (", pc.x.col, ", ", pc.y.col,
                  ") are not available in the loadings matrix.\n",
                  "       Available PCs: ", paste0(colnames(loadings.mat), collapse = ", ")))
    }


    ### Build loadings data.frame
    loadings.df = data.frame(
      variable = rownames(loadings.mat),
      loading.x = loadings.mat[, pc.x.col],
      loading.y = loadings.mat[, pc.y.col]
    )

    # Compute Euclidean distance from origin for ranking
    loadings.df$distance = sqrt(loadings.df$loading.x^2 + loadings.df$loading.y^2)


    ### Scale loadings to fit within the score range
    # The scaling maps the loadings range to the scores range so that arrows are visually comparable
    score.range = max(abs(c(tb$PC.x, tb$PC.y)), na.rm = TRUE)
    loading.range = max(abs(c(loadings.df$loading.x, loadings.df$loading.y)), na.rm = TRUE)

    if (loading.range > 0) {
      scale.factor = (score.range / loading.range) * loading.scale
    } else {
      scale.factor = 1
    }

    loadings.df$loading.x.scaled = loadings.df$loading.x * scale.factor
    loadings.df$loading.y.scaled = loadings.df$loading.y * scale.factor


    ### Select top N loadings
    n.loadings = min(n.loadings, nrow(loadings.df))
    loadings.top = loadings.df[order(loadings.df$distance, decreasing = TRUE),][seq_len(n.loadings),]



    ### -----------------------------------------------
    ### Build the biplot
    ### -----------------------------------------------
    biplot =
      ggplot(data = tb,
             aes(x = PC.x,
                 y = PC.y,
                 shape = shape,
                 color = color,
                 label = label))

    if (plot.zero.line.x == TRUE) {
      biplot =
        biplot +
        geom_vline(xintercept = 0, color = "gray", linetype = 2)
    }

    if (plot.zero.line.y == TRUE) {
      biplot =
        biplot +
        geom_hline(yintercept = 0, color = "gray", linetype = 2)
    }


    ## Add loading arrows (behind points)
    biplot =
      biplot +
      geom_segment(data = loadings.top,
                   aes(x = 0, y = 0,
                       xend = loading.x.scaled,
                       yend = loading.y.scaled),
                   inherit.aes = FALSE,
                   arrow = arrow(length = unit(0.2, "cm"), type = "closed"),
                   color = loading.color,
                   linewidth = loading.arrow.size,
                   alpha = loading.alpha) +
      ggrepel::geom_text_repel(data = loadings.top,
                               aes(x = loading.x.scaled,
                                   y = loading.y.scaled,
                                   label = variable),
                               inherit.aes = FALSE,
                               color = loading.color,
                               size = loading.label.size,
                               alpha = loading.alpha,
                               fontface = "italic",
                               max.overlaps = 100,
                               segment.color = loading.color,
                               segment.alpha = loading.alpha * 0.5,
                               segment.size = 0.3)


    ## Add sample points (on top of arrows)
    biplot =
      biplot +
      geom_point(size = 3) +
      theme_classic() +
      xlab(paste0("PC", PC.x, " (", round(DEprot.PCA.object@importance$Percentage.of.Variance[PC.x],1), "%)")) +
      ylab(paste0("PC", PC.y, " (", round(DEprot.PCA.object@importance$Percentage.of.Variance[PC.y],1), "%)")) +
      theme(aspect.ratio = 1,
            axis.line = element_blank(),
            axis.ticks = element_line(color = "black"),
            axis.text = element_text(color = "black"),
            panel.border = element_rect(color = "black", fill = NA))


    ## Add sample labels
    if (show.labels == TRUE) {
      biplot = biplot + ggrepel::geom_text_repel(max.overlaps = 100,
                                                 show.legend = FALSE)
    }

    biplot =
      biplot +
      guides(color = guide_legend(title = ifelse(color.column == "column.id", yes = "Samples", no = stringr::str_to_title(color.column))),
             shape = shape.label)


    return(biplot)
  }
