#' @title plot.PC.scatter
#'
#' @description Plot a scatter of the PCs from an object generated by \link{perform.PCA}.
#'
#' @param DEprot.PCA.object An object of class \code{DEprot.PCA.object}, as generated by \link{perform.PCA}.
#' @param PC.x Number indicating which Principal Component (PC) display on the x-axis. Default: \code{2} (PC2).
#' @param PC.y Number indicating which Principal Component (PC) display on the y-axis. Default: \code{1} (PC1).
#' @param color.column String indicating the name of the column in the \code{metadata} to use as factor for the dot colors. Default: \code{"column.id"} (each sample a color).
#' @param shape.column String indicating the name of the column in the \code{metadata} to use as factor for the dot shapes. Default: \code{NULL} (all dots).
#' @param label.column String indicating the name of the column in the \code{metadata} to use as label of the dots. Default: \code{NULL} (no labeling).
#' @param plot.zero.line.x Logical value to indicate whether to plot two gray dashed line in correspondence of x=0. Default: \code{TRUE}.
#' @param plot.zero.line.y Logical value to indicate whether to plot two gray dashed line in correspondence of y=0. Default: \code{TRUE}.
#'
#' @return A ggplot object.
#'
#' @seealso \link{perform.PCA}, \link{plot.PC.scatter.123}, \link{plot.PCoA.scatter}
#'
#' @name plot.PC.scatter
#'
#' @import ggplot2
#' @importFrom stringr str_to_title
#' @import ggrepel
#'
#' @author Sebastian Gregoricchio
#'
#' @examples
#' # Perform Principal Component Analyses (PCA)
#' pca <- perform.PCA(DEprot.object = DEprot::test.toolbox$dpo.imp)
#'
#' # Plot PC1-vs-PC2 scatter
#' plot.PC.scatter(DEprot.PCA.object = pca,
#'                 color.column = "condition",
#'                 shape.column = "replicate",
#'                 label.column = "replicate",
#'                 plot.zero.line.y = FALSE)
#'
#' # Plot PC2-vs-PC3 scatter
#' plot.PC.scatter(DEprot.PCA.object = pca,
#'                 PC.x = 3,
#'                 PC.y = 2,
#'                 color.column = "condition",
#'                 shape.column = "replicate",
#'                 label.column = "replicate")
#'
#'
#' @export plot.PC.scatter

plot.PC.scatter =
  function(DEprot.PCA.object,
           PC.x = 2,
           PC.y = 1,
           color.column = "column.id",
           shape.column = NULL,
           label.column = NULL,
           plot.zero.line.x = TRUE,
           plot.zero.line.y = TRUE) {


    ### check object
    if (!("DEprot.PCA" %in% class(DEprot.PCA.object))) {
      stop("The input must be an object of class 'DEprot.PCA'.")
    }

    ### harmonized access to the ordination slots
    ord = .ordination.slots(DEprot.PCA.object)


    ### Generate the plot (shared body with plot.PCoA.scatter)
    PCA.plot =
      .ordination.scatter(coordinates = ord$coordinates,
                          importance = ord$importance,
                          axis.prefix = ord$axis.prefix,
                          axis.x = PC.x,
                          axis.y = PC.y,
                          color.column = color.column,
                          shape.column = shape.column,
                          label.column = label.column,
                          plot.zero.line.x = plot.zero.line.x,
                          plot.zero.line.y = plot.zero.line.y,
                          positive.axis = ord$positive.axis)

    return(PCA.plot)
  } # END function
