#' @title plot.PCoA.cumulative
#'
#' @description Function to plot the cumulative variance of all the principal coordinates of a PCoA.
#'
#' @param DEprot.PCoA.object An object of class \code{DEprot.PCoA}, as generated by \link{perform.PCoA}.
#' @param bar.color String indicating the color to use for the bar fill. Default: \code{"steelblue"}.
#' @param line.color String indicating the color to use for the line and the dots of the cumulative curve. Default: \code{"navyblue"}.
#' @param title String indicating the title of the plot (markdown annotation supported). Default: \code{NULL}.
#' @param broken.stick Logical value indicating whether the broken-stick expectation should be displayed as a dashed gray line. Default: \code{TRUE}.
#'
#' @return A barplot in ggplot format.
#'
#' @details
#' Only the principal coordinates corresponding to a positive eigenvalue are displayed, and the proportions of
#' variance are computed using the positive eigenvalues as denominator (see \link{perform.PCoA}).\cr
#' The broken-stick expectation provides a criterion for the axis retention: the axes whose proportion of variance
#' exceeds the corresponding broken-stick value are usually considered non-trivial.
#'
#' @seealso \link{perform.PCoA}, \link{plot.PC.cumulative}
#'
#' @name plot.PCoA.cumulative
#'
#' @import ggplot2
#' @import ggtext
#'
#' @author Sebastian Gregoricchio
#'
#' @examples
#' # Compute the sample correlations and the PCoA
#' correlation <- plot.correlation.heatmap(DEprot.object = DEprot::test.toolbox$dpo.imp,
#'                                         correlation.method = "spearman")
#'
#' pcoa <- perform.PCoA(DEprot.correlation.object = correlation)
#'
#' # Plot cumulative variance barplot
#' plot.PCoA.cumulative(pcoa)
#'
#' @export plot.PCoA.cumulative

plot.PCoA.cumulative =
  function(DEprot.PCoA.object,
           bar.color = "steelblue",
           line.color = "navyblue",
           title = NULL,
           broken.stick = TRUE) {


    ### check object
    if (!("DEprot.PCoA" %in% class(DEprot.PCoA.object))) {
      stop("The input must be an object of class 'DEprot.PCoA'.")
    }

    ### harmonized access to the ordination slots
    ord = .ordination.slots(DEprot.PCoA.object)


    ### Generate plot (shared body with plot.PC.cumulative)
    cumulative.plot =
      .cumulative.plot(importance = ord$importance,
                       axis.prefix = ord$axis.prefix,
                       axis.title = ord$axis.title,
                       bar.color = bar.color,
                       line.color = line.color,
                       title = title,
                       broken.stick = broken.stick,
                       filter.positive = TRUE)

    return(cumulative.plot)
  } #END function
