#' @title plot.PCoA.scatter.123
#'
#' @description Plot combined scatter of the principal coordinates 1-2,2-3 from an object generated by \link{perform.PCoA}.
#'
#' @param DEprot.PCoA.object An object of class \code{DEprot.PCoA}, as generated by \link{perform.PCoA}.
#' @param color.column String indicating the name of the column in the \code{metadata} to use as factor for the dot colors. Default: \code{"column.id"} (each sample a color).
#' @param shape.column String indicating the name of the column in the \code{metadata} to use as factor for the dot shapes. Default: \code{NULL} (all dots).
#' @param label.column String indicating the name of the column in the \code{metadata} to use as label of the dots. Default: \code{NULL} (no labeling).
#' @param dot.colors Color-vector indicating the colors to use for the points in the plot. If \code{NULL} (default) or the number of colors is lower than the required, automatic colors will be assign using the \code{rainbow} function. Default: \code{NULL}.
#' @param title String indicating a title to add to the plot (markdown syntax supported). Default: \code{NULL} (no title).
#' @param plot.zero.line.y.12 Logical value to indicate whether to plot a gray dashed line in correspondence of y=0 in the PCo1-vs-PCo2 plot. Default: \code{TRUE}.
#' @param plot.zero.line.x.12 Logical value to indicate whether to plot a gray dashed line in correspondence of x=0 in the PCo1-vs-PCo2 plot. Default: \code{TRUE}.
#' @param plot.zero.line.y.23 Logical value to indicate whether to plot a gray dashed line in correspondence of y=0 in the PCo2-vs-PCo3 plot. Default: \code{TRUE}.
#' @param plot.zero.line.x.23 Logical value to indicate whether to plot a gray dashed line in correspondence of x=0 in the PCo2-vs-PCo3 plot. Default: \code{TRUE}.
#'
#' @return A patchwork object result of a combination of two ggplot objects.
#'
#' @seealso \link{perform.PCoA}, \link{plot.PCoA.scatter}, \link{plot.PC.scatter.123}
#'
#' @name plot.PCoA.scatter.123
#'
#' @import ggplot2
#' @importFrom stringr str_to_title
#' @import patchwork
#' @importFrom grDevices rainbow
#'
#' @author Sebastian Gregoricchio
#'
#' @examples
#' # Compute the sample correlations and the PCoA
#' correlation <- plot.correlation.heatmap(DEprot.object = DEprot::test.toolbox$dpo.imp,
#'                                         correlation.method = "spearman")
#'
#' pcoa <- perform.PCoA(DEprot.correlation.object = correlation)
#'
#' # Visualize the PCoA
#' plot.PCoA.scatter.123(DEprot.PCoA.object = pcoa,
#'                       color.column = "condition",
#'                       shape.column = "replicate",
#'                       label.column = "replicate")
#'
#' @export plot.PCoA.scatter.123

plot.PCoA.scatter.123 =
  function(DEprot.PCoA.object,
           color.column = "column.id",
           shape.column = NULL,
           label.column = NULL,
           dot.colors = NULL,
           title = NULL,
           plot.zero.line.y.12 = TRUE,
           plot.zero.line.x.12 = TRUE,
           plot.zero.line.y.23 = TRUE,
           plot.zero.line.x.23 = TRUE) {


    ### check object
    if (!("DEprot.PCoA" %in% class(DEprot.PCoA.object))) {
      stop("The input must be an object of class 'DEprot.PCoA'.")
    }

    ### harmonized access to the ordination slots
    ord = .ordination.slots(DEprot.PCoA.object)


    ### Generate the combined plot (shared body with plot.PC.scatter.123)
    combined.plot =
      .ordination.scatter.123(coordinates = ord$coordinates,
                              metadata = ord$metadata,
                              importance = ord$importance,
                              axis.prefix = ord$axis.prefix,
                              color.column = color.column,
                              shape.column = shape.column,
                              label.column = label.column,
                              dot.colors = dot.colors,
                              title = title,
                              plot.zero.line.y.12 = plot.zero.line.y.12,
                              plot.zero.line.x.12 = plot.zero.line.x.12,
                              plot.zero.line.y.23 = plot.zero.line.y.23,
                              plot.zero.line.x.23 = plot.zero.line.x.23,
                              positive.axis = ord$positive.axis)

    return(combined.plot)
  } # END FUNCTION
