#' @title simplify.enrichment
#'
#' @description Perform Gene Set Enrichment Analyses (GSEA) or OverRepresentation Analyses (ORA) on a proteomics differential analyses.
#'
#' @param enrichment.results Object of class \code{DEprot.enrichResult} as generated using \link{geneset.enrichment}.
#'
#' @return An object of class \code{DEprot.enrichResult}.
#'
#' @import dplyr
#' @import ggplot2
#' @importFrom plyr ldply
#' @import ggtext
#' @import clusterProfiler
#' @import viridis
#' @importFrom BiocManager install
#' @importFrom devtools install_github
#'
#' @export simplify.enrichment

simplify.enrichment =
  function(enrichment.results) {

    # ## Libraries
    # require(dplyr)
    # require(ggplot2)


    # if (!requireNamespace("clusterProfiler", quietly = TRUE)) {
    #   warning("The 'clusterProfiler' (Bioconductor) package must be installed to use this function.")
    #
    #   ### Ask for installing
    #   install = readline("Do you want to install `clusterProfiler`? [yes/no] ")
    #   if (tolower(install) %in% c("yes","y","yeah","yep","yo")) {
    #     BiocManager::install("clusterProfiler")
    #     library(clusterProfiler)
    #   } else {
    #     return(DEprot.object)
    #   }
    # } else {
    #   require(clusterProfiler)
    # }



    if (!requireNamespace("aPEAR", quietly = TRUE)) {
      warning("The 'aPEAR' (GitHub, previously on CRAN) package must be installed to use this function.")

      ### Ask for installing
      install = readline("Do you want to install `aPEAR`? [yes/no] ")
      if (tolower(install) %in% c("yes","y","yeah","yep","yo")) {
        devtools::install_github("kerseviciute/aPEAR",
                                 build_manual = FALSE,
                                 build_vignettes = FALSE)
        library(aPEAR)
      } else {
        return(DEprot.object)
      }
    } else {
      require(aPEAR)
    }


    ######################################################################################

    ## check the objects
    if (!("DEprot.enrichResult" %in% class(enrichment.results))) {
      stop("The 'enrichment.results' must be an object of calss 'DEprot.enrichResult' as generated by the 'geneset.enrichment' function.")
      #return(invisible())
    }

    # if (!("DEprot.analyses" %in% class(dpo.analyses.object))) {
    #   stop("The 'dpo.analyses.object' must be an object of calss 'DEprot.analyses'.")
    #   #return(invisible())
    # }


    # ### get contrast index and indirectly check the dpo.analyses object
    # i=0
    # contrast.idx = 0
    # stop = FALSE
    # while (stop == FALSE & i < (length(dpo.analyses.object@contrasts)+1)) {
    #   i = i+1
    #   if (i > length(dpo.analyses.object@contrasts)) {
    #     stop = TRUE
    #     stop("The contrast cannot be found in the dpo.analyses.object. Verify that the latter was the one used for the original enrichment.genset analyses.")
    #     #return(invisible())
    #   }  else if (dpo.analyses.object@contrasts[[i]]$metadata.column == enrichment.results@parameters$contrast$metadata.column &
    #       all(dpo.analyses.object@contrasts[[i]]$group.1 %in% enrichment.results@parameters$contrast$group.1) &
    #       all(dpo.analyses.object@contrasts[[i]]$group.2 %in% enrichment.results@parameters$contrast$group.2)) {
    #     contrast.idx = i
    #     stop = TRUE
    #   }
    # }

    ######################################################################################

    ## Collect info for affinity propagation
    padj_list = enrichment.results@enrichment.discovery@result$p.adjust
    names(padj_list) = enrichment.results@enrichment.discovery@result$ID

    set_list = enrichment.results@enrichment.discovery@geneSets[names(padj_list)]

    ## Define geneSet clusters
    clusters = DEprot::affinity.propagation(idsInSet = set_list,
                                            score = -log10(padj_list))



    ## Plot heatmaps of overalps
    heatmap_list = list()

    for (i in 1:length(clusters$clusters)) {
      sets = clusters$clusters[[i]]
      set_subset = set_list[sets]

      gene_mat = plyr::ldply(set_subset, data.frame)

      most_reccurent_genes =
        gene_mat %>%
        dplyr::group_by(`X..i..`) %>%
        dplyr::summarise(n = n()) %>%
        dplyr::arrange(n, `X..i..`)

      gene_mat =
        gene_mat %>%
        dplyr::mutate(presence = 1,
                      `.id` = factor(`.id`, levels = sets),
                      `X..i..` = factor(`X..i..`, levels = most_reccurent_genes$X..i..))

      heatmap_list[[i]] =
        ggplot(data = unique(gene_mat),
               aes(x = `.id`,
                   y = `X..i..`,
                   fill = presence)) +
        geom_tile(show.legend = FALSE) +
        ggtitle(paste0("Cluster: **",clusters$representatives[i],"**")) +
        xlab(NULL) +
        ylab(NULL) +
        scale_x_discrete(expand = c(0,0)) +
        scale_y_discrete(expand = c(0,0)) +
        theme_classic() +
        theme(axis.ticks = element_blank(),
              axis.text.y = element_text(color = "black"),
              axis.text.x = element_text(color = "black", hjust = 1, angle = 90),
              plot.title = ggtext::element_textbox(color = "black", hjust = 0.5),
              axis.line = element_blank(),
              panel.border = element_rect(fill = NA, color = "black", linewidth = 1))
    }

    names(heatmap_list) = clusters$representatives

    clusters[[3]] = heatmap_list
    names(clusters)[3] = "heatmap.cluster.overalp"


    ## Remake geneset table
    geneSet_tb = plyr::ldply(set_list[names(set_list) %in% clusters$representatives], data.frame)
    colnames(geneSet_tb) = c("gs_name", "gene_symbol")

    ######################################################################################

    ## Filter the results
    filtered_results =
      clusterProfiler::filter(enrichment.results@enrichment.discovery,
                              ID %in% clusters$representatives)

    filtered_results@geneSets = filtered_results@geneSets[names(filtered_results@geneSets) %in% clusters$representatives]

    ######################################################################################

    enrichment.type = enrichment.results@parameters$enrichment.type
    contrasts.info = enrichment.results@parameters$contrast

    if (toupper(enrichment.type) == "GSEA") { ### GSEA analyses
      ## plot pathway networks
      pathway.network.clusters = tryCatch(aPEAR::findPathClusters(filtered_results@result),error = function(x)(return(NULL)))
      pathway.network.plot = tryCatch(aPEAR::enrichmentNetwork(filtered_results@result, drawEllipses = TRUE, colorBy = "NES"),
                                      error = function(x)(return(NULL)))

      NES.plot = tryCatch(DEprot::NES.plot(enrichResult = filtered_results,
                                           pos.NES.label = contrasts.info$var.1,
                                           neg.NES.label = contrasts.info$var.2,
                                           title = paste0(contrasts.info$metadata.column,": **", contrasts.info$var.1, "** *vs* **", contrasts.info$var.2,"**")),
                          error = function(x)(return(NULL)))

      dotplot_fold.enrichment = NULL

    } else { ## ORA analyses
      ## plot pathway networks
      pathway.network.clusters = tryCatch(aPEAR::findPathClusters(filtered_results@result),error = function(x)(return(NULL)))
      pathway.network.plot = tryCatch(aPEAR::enrichmentNetwork(filtered_results@result, colorBy = 'pvalue', colorType = 'pval', pCutoff = -5, nodeSize = "Count"),
                                      error = function(x)(return(NULL)))

      NES.plot = NULL


      dotplot_fold.enrichment =
        tryCatch(clusterProfiler::dotplot(filtered_results,
                                          x = "FoldEnrichment",
                                          showCategory = enrichment.results@parameters$dotplot.n) +
                   ggtitle(paste0(contrasts.info$metadata.column,": **", contrasts.info$var.1, "** *vs* **", contrasts.info$var.2,"**")) +
                   viridis::scale_fill_viridis(option = "mako", direction = -1, begin = 0.3) +
                   theme(plot.title = ggtext::element_markdown(hjust = 0.5),
                         axis.ticks.y = element_blank()),
                 error = function(x)(return(NULL)))
    }


    ## plot protein networks
    protein.network = tryCatch(clusterProfiler::cnetplot(filtered_results), error = function(x)(return(NULL)))


    ## plot dotplot
    dotplot_gene.ratio =
      tryCatch(clusterProfiler::dotplot(filtered_results,
                                        x = "GeneRatio",
                                        showCategory = enrichment.results@parameters$dotplot.n) +
                 ggtitle(paste0(contrasts.info$metadata.column,": **", contrasts.info$var.1, "** *vs* **", contrasts.info$var.2,"**")) +
                 viridis::scale_fill_viridis(option = "rocket", direction = -1, begin = 0.3) +
                 theme(plot.title = ggtext::element_markdown(hjust = 0.5),
                       axis.ticks.y = element_blank()))


    ######################################################################################

    # Export filtered object
    new_analyses =
      new(Class = "DEprot.enrichResult",
          enrichment.discovery = filtered_results,
          protein.network = protein.network,
          pathway.network = list(clusters = pathway.network.clusters,
                                 plot = pathway.network.plot),
          NES.plot = NES.plot,
          dotplot_gene.ratio = dotplot_gene.ratio,
          dotplot_fold.enrichment = dotplot_fold.enrichment,
          parameters = enrichment.results@parameters,
          affinity.propagation = clusters)

    return(new_analyses)
  } # END function





