# ----------------------------------------------------------------------------------------
###                              sPLS-DA PLOTTING FUNCTIONS                             ###
# ----------------------------------------------------------------------------------------

#' @title .splsda.axis.labels
#'
#' @description
#' Internal. Builds the axis titles of the sPLS-DA scatters. The generic ordination label ('comp1 (12.3%)') is replaced by an explicit one, since on a supervised model the percentage refers to the protein block and not to the separation between the classes.
#'
#' @param importance importance table of the \code{DEprot.sPLSDA} object.
#' @param axis Number of the component.
#'
#' @return A string.
#'
#' @keywords internal

.splsda.axis.labels =
  function(importance,
           axis) {

    percentage = importance$Percentage.of.Variance[axis]

    if (is.na(percentage)) {
      return(paste0("Component ", axis))
    }

    return(paste0("Component ", axis, " (", round(percentage, 1), "% of the protein variance)"))
  } # END function




# ----------------------------------------------------------------------------------------


#' @title .splsda.group.colors
#'
#' @description
#' Internal. Checks the colors provided for the classes and completes them when they are missing or too few.
#'
#' @param group.colors Named (or unnamed) color vector, or \code{NULL}.
#' @param group.labels Character vector of the class names.
#'
#' @return A named color vector.
#'
#' @importFrom grDevices rainbow
#'
#' @keywords internal

.splsda.group.colors =
  function(group.colors,
           group.labels) {

    if (is.null(group.colors) | length(group.colors) < length(group.labels)) {
      if (!is.null(group.colors)) {
        message("The number of colors provided is lower than the number of classes (",
                length(group.labels), "). Values will be assigned automatically.")
      }
      group.colors = grDevices::rainbow(n = length(group.labels), s = 0.5)
    }

    if (is.null(names(group.colors))) {
      names(group.colors) = group.labels
    }

    return(group.colors)
  } # END function




# ----------------------------------------------------------------------------------------


#' @title plot.sPLSDA.scatter
#'
#' @description Plots the scatter of two components of a sPLS-DA, as generated by \link{perform.sPLSDA}.
#'
#' @param DEprot.sPLSDA.object An object of class \code{DEprot.sPLSDA}.
#' @param comp.x Number indicating which component to display on the x-axis. Default: \code{1}.
#' @param comp.y Number indicating which component to display on the y-axis. Default: \code{2}.
#' @param color.column String indicating the name of the column in the metadata to use as factor for the dot colors. Default: \code{NULL} (the column used to fit the model).
#' @param shape.column String indicating the name of the column in the metadata to use as factor for the dot shapes. Default: \code{NULL} (all dots).
#' @param label.column String indicating the name of the column in the metadata to use as label of the dots. Default: \code{NULL} (no labeling).
#' @param ellipse Logical value indicating whether a confidence ellipse should be drawn around each group of the \code{color.column}. Default: \code{TRUE}.
#' @param ellipse.level Numeric value (0-1) indicating the confidence level of the ellipses. Default: \code{0.95}.
#' @param plot.zero.line.x Logical value to indicate whether to plot a gray dashed line in correspondence of x=0. Default: \code{TRUE}.
#' @param plot.zero.line.y Logical value to indicate whether to plot a gray dashed line in correspondence of y=0. Default: \code{TRUE}.
#' @param point.size Numeric value indicating the size of the dots. Default: \code{3}.
#'
#' @details
#' The ellipses are a reading aid, not a test: a supervised model is fitted to separate the classes, so on the training samples the groups will look tidy even when the cross-validated error rate is poor. The error rates stored in the \code{performance} slot are what says whether the separation holds (\link{plot.sPLSDA.performance}).
#'
#' @return A ggplot object.
#'
#' @seealso \link{perform.sPLSDA}, \link{plot.sPLSDA.scatter.123}, \link{plot.sPLSDA.biplot}
#'
#' @name plot.sPLSDA.scatter
#'
#' @import ggplot2
#' @import ggrepel
#'
#' @author Sebastian Gregoricchio
#'
#' @examples
#' splsda <- perform.sPLSDA(DEprot.object = DEprot::test.toolbox$dpo.imp,
#'                          group.column = "condition",
#'                          keepX = 5,
#'                          validate = FALSE)
#'
#' plot.sPLSDA.scatter(DEprot.sPLSDA.object = splsda,
#'                     comp.x = 1,
#'                     comp.y = 2,
#'                     shape.column = "replicate")
#'
#' @export plot.sPLSDA.scatter

plot.sPLSDA.scatter =
  function(DEprot.sPLSDA.object,
           comp.x = 1,
           comp.y = 2,
           color.column = NULL,
           shape.column = NULL,
           label.column = NULL,
           ellipse = TRUE,
           ellipse.level = 0.95,
           plot.zero.line.x = TRUE,
           plot.zero.line.y = TRUE,
           point.size = 3) {

    ### check object
    if (!("DEprot.sPLSDA" %in% class(DEprot.sPLSDA.object))) {
      stop("The input must be an object of class 'DEprot.sPLSDA'.")
    }

    if (is.null(color.column)) {color.column = DEprot.sPLSDA.object@group.column}

    ### harmonized access to the ordination slots
    ord = .ordination.slots(DEprot.sPLSDA.object)


    ### Generate the plot (shared body with the PCA and PCoA scatters)
    splsda.plot =
      .ordination.scatter(coordinates = ord$coordinates,
                          importance = ord$importance,
                          axis.prefix = ord$axis.prefix,
                          axis.x = comp.x,
                          axis.y = comp.y,
                          color.column = color.column,
                          shape.column = shape.column,
                          label.column = label.column,
                          plot.zero.line.x = plot.zero.line.x,
                          plot.zero.line.y = plot.zero.line.y,
                          positive.axis = ord$positive.axis,
                          point.size = point.size)


    ### Confidence ellipses around the groups of the color column
    if (ellipse == TRUE) {
      group.sizes = table(ord$coordinates[, color.column])

      if (min(group.sizes) < 3) {
        message("Some groups of '", color.column, "' contain less than 3 samples: no ellipse can be drawn for them.")
      }

      splsda.plot =
        splsda.plot +
        stat_ellipse(mapping = aes(group = color),
                     type = "norm",
                     level = ellipse.level,
                     linetype = 2,
                     linewidth = 0.4,
                     show.legend = FALSE)
    }


    ### Explicit axis titles
    splsda.plot =
      splsda.plot +
      xlab(.splsda.axis.labels(importance = ord$importance, axis = comp.x)) +
      ylab(.splsda.axis.labels(importance = ord$importance, axis = comp.y))

    return(splsda.plot)
  } # END function




# ----------------------------------------------------------------------------------------


#' @title plot.sPLSDA.scatter.123
#'
#' @description Combines the component1-vs-component2 and component3-vs-component2 scatters of a sPLS-DA.
#'
#' @param DEprot.sPLSDA.object An object of class \code{DEprot.sPLSDA}.
#' @param color.column String indicating the name of the column in the metadata to use as factor for the dot colors. Default: \code{NULL} (the column used to fit the model).
#' @param shape.column String indicating the name of the column in the metadata to use as factor for the dot shapes. Default: \code{NULL} (all dots).
#' @param label.column String indicating the name of the column in the metadata to use as label of the dots. Default: \code{NULL} (no labeling).
#' @param dot.colors Color-vector to use for the points. Default: \code{NULL} (automatic colors).
#' @param ellipse Logical value indicating whether a confidence ellipse should be drawn around each group. Default: \code{TRUE}.
#' @param ellipse.level Numeric value (0-1) indicating the confidence level of the ellipses. Default: \code{0.95}.
#' @param title String indicating the title of the combined plot (markdown annotation supported). Default: \code{NULL}.
#'
#' @return A patchwork object.
#'
#' @seealso \link{perform.sPLSDA}, \link{plot.sPLSDA.scatter}
#'
#' @name plot.sPLSDA.scatter.123
#'
#' @import ggplot2
#' @import ggtext
#' @import patchwork
#'
#' @author Sebastian Gregoricchio
#'
#' @examples
#' splsda <- perform.sPLSDA(DEprot.object = DEprot::test.toolbox$dpo.imp,
#'                          group.column = "condition",
#'                          keepX = 5,
#'                          validate = FALSE)
#'
#' plot.sPLSDA.scatter.123(DEprot.sPLSDA.object = splsda,
#'                         shape.column = "replicate")
#'
#' @export plot.sPLSDA.scatter.123

plot.sPLSDA.scatter.123 =
  function(DEprot.sPLSDA.object,
           color.column = NULL,
           shape.column = NULL,
           label.column = NULL,
           dot.colors = NULL,
           ellipse = TRUE,
           ellipse.level = 0.95,
           title = NULL) {

    ### check object
    if (!("DEprot.sPLSDA" %in% class(DEprot.sPLSDA.object))) {
      stop("The input must be an object of class 'DEprot.sPLSDA'.")
    }

    if (is.null(color.column)) {color.column = DEprot.sPLSDA.object@group.column}

    if (DEprot.sPLSDA.object@parameters$ncomp < 3) {
      stop("At least 3 components are required to generate the combined scatter, but the model has ",
           DEprot.sPLSDA.object@parameters$ncomp, ".")
    }


    ### Define the colors
    coordinates = DEprot.sPLSDA.object@components

    if (is.factor(coordinates[, color.column])) {
      color.labels = levels(droplevels(coordinates[, color.column]))
    } else {
      color.labels = unique(coordinates[, color.column])
    }

    scatter.colors = .splsda.group.colors(group.colors = dot.colors, group.labels = color.labels)


    ### Generate the two panels
    plot.1.2 =
      plot.sPLSDA.scatter(DEprot.sPLSDA.object = DEprot.sPLSDA.object,
                          comp.x = 1,
                          comp.y = 2,
                          color.column = color.column,
                          shape.column = shape.column,
                          label.column = label.column,
                          ellipse = ellipse,
                          ellipse.level = ellipse.level) +
      scale_color_manual(values = scatter.colors) +
      theme(legend.position = "none")

    plot.3.2 =
      plot.sPLSDA.scatter(DEprot.sPLSDA.object = DEprot.sPLSDA.object,
                          comp.x = 3,
                          comp.y = 2,
                          color.column = color.column,
                          shape.column = shape.column,
                          label.column = label.column,
                          ellipse = ellipse,
                          ellipse.level = ellipse.level) +
      ylab(NULL) +
      scale_color_manual(values = scatter.colors)


    ### Export the combined plot
    if (is.null(title)) {
      return(patchwork::wrap_plots(plot.1.2, plot.3.2, nrow = 1))
    } else {
      return(patchwork::wrap_plots(plot.1.2, plot.3.2, nrow = 1) +
               patchwork::plot_annotation(title = title,
                                          theme = theme(plot.title = ggtext::element_markdown(hjust = 0.5))))
    }
  } # END function




# ----------------------------------------------------------------------------------------


#' @title plot.sPLSDA.cumulative
#'
#' @description Plots the proportion of protein variance carried by each component of a sPLS-DA, with the cumulative curve on top.
#'
#' @param DEprot.sPLSDA.object An object of class \code{DEprot.sPLSDA}.
#' @param bar.color String indicating the color to use for the bar fill. Default: \code{"steelblue"}.
#' @param line.color String indicating the color to use for the line and the dots of the cumulative curve. Default: \code{"navyblue"}.
#' @param title String indicating the title of the plot (markdown annotation supported). Default: \code{NULL}.
#'
#' @details
#' A sPLS-DA component is built to separate the classes, not to capture variance, and it only sees the handful of proteins retained by \code{keepX}. The percentages are therefore much lower than the ones of a PCA computed on the same data, and comparing the two is meaningless: what this plot shows is how the (little) variance used by the model is spread over the components.
#'
#' @return A ggplot object.
#'
#' @seealso \link{perform.sPLSDA}, \link{plot.PC.cumulative}
#'
#' @name plot.sPLSDA.cumulative
#'
#' @import ggplot2
#' @import ggtext
#'
#' @author Sebastian Gregoricchio
#'
#' @examples
#' splsda <- perform.sPLSDA(DEprot.object = DEprot::test.toolbox$dpo.imp,
#'                          group.column = "condition",
#'                          keepX = 5,
#'                          validate = FALSE)
#'
#' plot.sPLSDA.cumulative(DEprot.sPLSDA.object = splsda)
#'
#' @export plot.sPLSDA.cumulative

plot.sPLSDA.cumulative =
  function(DEprot.sPLSDA.object,
           bar.color = "steelblue",
           line.color = "navyblue",
           title = NULL) {

    ### check object
    if (!("DEprot.sPLSDA" %in% class(DEprot.sPLSDA.object))) {
      stop("The input must be an object of class 'DEprot.sPLSDA'.")
    }

    ### harmonized access to the ordination slots
    ord = .ordination.slots(DEprot.sPLSDA.object)


    ### Generate the plot (shared body with the PCA and PCoA cumulative plots)
    cumulative.plot =
      .cumulative.plot(importance = ord$importance,
                       axis.prefix = ord$axis.prefix,
                       axis.title = ord$axis.title,
                       bar.color = bar.color,
                       line.color = line.color,
                       title = title,
                       broken.stick = FALSE,
                       filter.positive = FALSE)

    return(cumulative.plot)
  } # END function




# ----------------------------------------------------------------------------------------


#' @title plot.sPLSDA.biplot
#'
#' @description Overlays the loadings of the selected proteins on the scatter of two components of a sPLS-DA.
#'
#' @param DEprot.sPLSDA.object An object of class \code{DEprot.sPLSDA}.
#' @param comp.x Number indicating which component to display on the x-axis. Default: \code{1}.
#' @param comp.y Number indicating which component to display on the y-axis. Default: \code{2}.
#' @param color.column String indicating the name of the column in the metadata to use as factor for the dot colors. Default: \code{NULL} (the column used to fit the model).
#' @param shape.column String indicating the name of the column in the metadata to use as factor for the dot shapes. Default: \code{NULL} (all dots).
#' @param label.column String indicating the name of the column in the metadata to use as label of the dots. Default: \code{NULL} (no labeling).
#' @param ellipse Logical value indicating whether a confidence ellipse should be drawn around each group. Default: \code{FALSE}.
#' @param ellipse.level Numeric value (0-1) indicating the confidence level of the ellipses. Default: \code{0.95}.
#' @param plot.zero.line.x Logical value to indicate whether to plot a gray dashed line in correspondence of x=0. Default: \code{TRUE}.
#' @param plot.zero.line.y Logical value to indicate whether to plot a gray dashed line in correspondence of y=0. Default: \code{TRUE}.
#' @param n.loadings Number of proteins to display, ranked by their distance from the origin in the plane displayed. Default: \code{10}.
#' @param loading.color String indicating the color of the arrows and of their labels. Default: \code{"turquoise4"}.
#' @param loading.arrow.size Numeric value indicating the linewidth of the arrows. Default: \code{0.6}.
#' @param loading.label.size Numeric value indicating the font size of the labels. Default: \code{3}.
#' @param loading.alpha Numeric value (0-1) indicating the transparency of arrows and labels. Default: \code{0.7}.
#' @param loading.scale Numeric multiplier to manually adjust the length of the arrows. Default: \code{0.8}.
#'
#' @details
#' Only the proteins retained on at least one of the two components displayed can appear: a protein dropped by the sparsity penalty has a coefficient of exactly zero and no direction to point to.
#'
#' @return A ggplot object.
#'
#' @seealso \link{perform.sPLSDA}, \link{plot.sPLSDA.scatter}, \link{plot.sPLSDA.loadings}
#'
#' @name plot.sPLSDA.biplot
#'
#' @import ggplot2
#' @import ggrepel
#'
#' @author Sebastian Gregoricchio
#'
#' @examples
#' splsda <- perform.sPLSDA(DEprot.object = DEprot::test.toolbox$dpo.imp,
#'                          group.column = "condition",
#'                          keepX = 5,
#'                          validate = FALSE)
#'
#' plot.sPLSDA.biplot(DEprot.sPLSDA.object = splsda,
#'                    comp.x = 1,
#'                    comp.y = 2,
#'                    n.loadings = 5)
#'
#' @export plot.sPLSDA.biplot

plot.sPLSDA.biplot =
  function(DEprot.sPLSDA.object,
           comp.x = 1,
           comp.y = 2,
           color.column = NULL,
           shape.column = NULL,
           label.column = NULL,
           ellipse = FALSE,
           ellipse.level = 0.95,
           plot.zero.line.x = TRUE,
           plot.zero.line.y = TRUE,
           n.loadings = 10,
           loading.color = "turquoise4",
           loading.arrow.size = 0.6,
           loading.label.size = 3,
           loading.alpha = 0.7,
           loading.scale = 0.8) {

    ### check object
    if (!("DEprot.sPLSDA" %in% class(DEprot.sPLSDA.object))) {
      stop("The input must be an object of class 'DEprot.sPLSDA'.")
    }

    if (is.null(color.column)) {color.column = DEprot.sPLSDA.object@group.column}

    ord = .ordination.slots(DEprot.sPLSDA.object)


    ### Build the loadings table for the plane displayed
    loadings = DEprot.sPLSDA.object@loadings

    available = sort(unique(loadings$component))

    if (!(comp.x %in% available) | !(comp.y %in% available)) {
      stop("The components requested (", comp.x, ", ", comp.y, ") are not available.\n",
           "       Available components: ", paste(available, collapse = ", "))
    }

    loading.x = loadings[loadings$component == comp.x, c("prot.id", "loading")]
    loading.y = loadings[loadings$component == comp.y, c("prot.id", "loading")]

    colnames(loading.x)[2] = "loading.x"
    colnames(loading.y)[2] = "loading.y"

    loadings.df = merge(loading.x, loading.y, by = "prot.id")
    colnames(loadings.df)[1] = "variable"

    ## a protein dropped on both components sits exactly on the origin and would only add
    ## an arrow of length zero
    loadings.df = loadings.df[loadings.df$loading.x != 0 | loadings.df$loading.y != 0, , drop = FALSE]

    if (nrow(loadings.df) == 0) {
      stop("No protein was selected on the components ", comp.x, " and ", comp.y, ": the biplot is empty.")
    }


    ### Rank and rescale the loadings (shared with the PCA and PCoA biplots)
    scaled = .scale.loadings(loadings.df = loadings.df,
                             scores.x = ord$coordinates[, paste0("comp", comp.x)],
                             scores.y = ord$coordinates[, paste0("comp", comp.y)],
                             n.loadings = n.loadings,
                             loading.scale = loading.scale)


    ### Build the biplot (the arrows are inserted below the points)
    biplot =
      .ordination.scatter(coordinates = ord$coordinates,
                          importance = ord$importance,
                          axis.prefix = ord$axis.prefix,
                          axis.x = comp.x,
                          axis.y = comp.y,
                          color.column = color.column,
                          shape.column = shape.column,
                          label.column = label.column,
                          plot.zero.line.x = plot.zero.line.x,
                          plot.zero.line.y = plot.zero.line.y,
                          positive.axis = ord$positive.axis,
                          extra.layers = .loading.layers(loadings.top = scaled$top,
                                                         loading.color = loading.color,
                                                         loading.arrow.size = loading.arrow.size,
                                                         loading.label.size = loading.label.size,
                                                         loading.alpha = loading.alpha))

    if (ellipse == TRUE) {
      biplot =
        biplot +
        stat_ellipse(mapping = aes(group = color),
                     type = "norm",
                     level = ellipse.level,
                     linetype = 2,
                     linewidth = 0.4,
                     show.legend = FALSE)
    }

    biplot =
      biplot +
      xlab(.splsda.axis.labels(importance = ord$importance, axis = comp.x)) +
      ylab(.splsda.axis.labels(importance = ord$importance, axis = comp.y))

    return(biplot)
  } # END function




# ----------------------------------------------------------------------------------------


#' @title plot.sPLSDA.loadings
#'
#' @description Plots the loadings of the proteins retained on a component of a sPLS-DA, colored by the class in which each of them is the highest.
#'
#' @param DEprot.sPLSDA.object An object of class \code{DEprot.sPLSDA}.
#' @param component Numeric value indicating the component to display. Default: \code{1}.
#' @param n.proteins Numeric value indicating the maximum number of proteins to display, ranked by absolute loading. Default: \code{25}.
#' @param group.colors Color-vector (optionally named on the classes) used for the bars. Default: \code{NULL} (automatic colors).
#' @param protein.names.pattern String indicating a pattern to be passed to gsub and removed from the protein names. Default: \code{NULL} (no changes).
#' @param bar.width Numeric value indicating the width of the bars. Default: \code{0.75}.
#' @param axes.text.size Numeric value indicating the font size of the axis text. Default: \code{9}.
#' @param title String indicating the title of the plot (markdown annotation supported). Default: \code{NULL} (automatic title).
#'
#' @details
#' The sign of a loading is only interpretable once the orientation of the component is fixed, which \link{perform.sPLSDA} does through the \code{reference.group} argument: a positive coefficient marks a protein pulling the samples towards that group. The color adds the information the coefficient alone does not carry, namely in which class the protein is actually the most abundant, assigned by the highest median as done by \code{mixOmics::plotLoadings}.
#'
#' @return A ggplot object.
#'
#' @seealso \link{perform.sPLSDA}, \link{plot.sPLSDA.stability}, \link{get.sPLSDA.results}
#'
#' @name plot.sPLSDA.loadings
#'
#' @import ggplot2
#' @import ggtext
#'
#' @author Sebastian Gregoricchio
#'
#' @examples
#' splsda <- perform.sPLSDA(DEprot.object = DEprot::test.toolbox$dpo.imp,
#'                          group.column = "condition",
#'                          keepX = 5,
#'                          validate = FALSE)
#'
#' plot.sPLSDA.loadings(DEprot.sPLSDA.object = splsda,
#'                      component = 1,
#'                      n.proteins = 5)
#'
#' @export plot.sPLSDA.loadings

plot.sPLSDA.loadings =
  function(DEprot.sPLSDA.object,
           component = 1,
           n.proteins = 25,
           group.colors = NULL,
           protein.names.pattern = NULL,
           bar.width = 0.75,
           axes.text.size = 9,
           title = NULL) {

    ### check object
    if (!("DEprot.sPLSDA" %in% class(DEprot.sPLSDA.object))) {
      stop("The input must be an object of class 'DEprot.sPLSDA'.")
    }

    available = sort(unique(DEprot.sPLSDA.object@loadings$component))

    if (!(component %in% available)) {
      stop("The component ", component, " is not available.\n",
           "       Available components: ", paste(available, collapse = ", "))
    }


    ### Collect the selected proteins
    tb = DEprot.sPLSDA.object@loadings
    tb = tb[tb$component == component & tb$selected %in% TRUE, , drop = FALSE]

    if (nrow(tb) == 0) {
      stop("No protein was selected on the component ", component, ": there is nothing to plot.")
    }

    tb = tb[order(-tb$abs.loading), , drop = FALSE]

    if (!is.null(n.proteins)) {
      tb = utils::head(tb, round(n.proteins, 0))
    }

    if (!is.null(protein.names.pattern)) {
      tb$prot.id = gsub(protein.names.pattern, "", tb$prot.id)
    }

    ## the bars are sorted by the value of the loading, so that the two directions of the
    ## component sit on the two sides of the zero line
    tb = tb[order(tb$loading), , drop = FALSE]
    tb$prot.id = factor(tb$prot.id, levels = unique(tb$prot.id))


    ### Colors of the classes
    group.labels = DEprot.sPLSDA.object@parameters$groups
    bar.colors = .splsda.group.colors(group.colors = group.colors, group.labels = group.labels)

    if (is.null(title)) {
      title = paste0("**Component ", component, "** (", nrow(tb), " of ",
                     length(DEprot.sPLSDA.object@selected.proteins[[component]]), " selected proteins)")
    }


    ### Generate the plot
    loadings.plot =
      ggplot(data = tb,
             aes(x = loading,
                 y = prot.id,
                 fill = factor(contrib.group, levels = group.labels))) +
      geom_vline(xintercept = 0, color = "gray", linetype = 2) +
      geom_bar(stat = "identity", width = bar.width) +
      scale_fill_manual(values = bar.colors,
                        name = DEprot.sPLSDA.object@group.column,
                        drop = FALSE) +
      xlab("Loading") +
      ylab(NULL) +
      ggtitle(label = title,
              subtitle = paste0("*positive: towards ", DEprot.sPLSDA.object@parameters$reference.group, "*")) +
      theme_classic() +
      theme(axis.line.y = element_blank(),
            axis.ticks.y = element_blank(),
            axis.text = element_text(color = "black", size = axes.text.size),
            panel.background = element_blank(),
            panel.grid.major.x = element_line(color = "gray", linewidth = 0.1),
            plot.title = ggtext::element_markdown(hjust = 0.5),
            plot.subtitle = ggtext::element_markdown(hjust = 0.5, size = 8))

    return(loadings.plot)
  } # END function




# ----------------------------------------------------------------------------------------


#' @title plot.sPLSDA.tuning
#'
#' @description Plots the classification error obtained over the grid of \code{keepX} values tested during the tuning of a sPLS-DA, and marks the value retained on each component.
#'
#' @param DEprot.sPLSDA.object An object of class \code{DEprot.sPLSDA}.
#' @param component Numeric value (or vector) indicating the component(s) to display. Default: \code{NULL} (all the components).
#' @param line.colors Color-vector used for the components. Default: \code{NULL} (automatic colors).
#' @param show.sd Logical value indicating whether the standard deviation over the repeats should be drawn as a ribbon. Default: \code{TRUE}.
#' @param title String indicating the title of the plot (markdown annotation supported). Default: \code{"**Tuning of keepX**"}.
#'
#' @details
#' The curves are usually flat over a wide range of values: many different numbers of proteins classify the samples equally well, and the minimum picked by the tuning is one point of a plateau rather than an optimum. Reading the plot is worth the time, because a value sitting at the left edge of that plateau gives a shorter and more interpretable protein list at no cost in error rate.
#'
#' @return A ggplot object.
#'
#' @seealso \link{perform.sPLSDA}, \link{plot.sPLSDA.performance}
#'
#' @name plot.sPLSDA.tuning
#'
#' @import ggplot2
#' @import ggtext
#'
#' @author Sebastian Gregoricchio
#'
#' @examples
#' \donttest{
#' # the tuning runs only when 'keepX' is left to NULL
#' splsda <- perform.sPLSDA(DEprot.object = DEprot::test.toolbox$dpo.imp,
#'                          group.column = "condition",
#'                          test.keepX = c(5, 10, 20),
#'                          validate = FALSE,
#'                          folds = 3,
#'                          nrepeat = 1)
#'
#' plot.sPLSDA.tuning(DEprot.sPLSDA.object = splsda)
#' }
#'
#' @export plot.sPLSDA.tuning

plot.sPLSDA.tuning =
  function(DEprot.sPLSDA.object,
           component = NULL,
           line.colors = NULL,
           show.sd = TRUE,
           title = "**Tuning of keepX**") {

    ### check object
    if (!("DEprot.sPLSDA" %in% class(DEprot.sPLSDA.object))) {
      stop("The input must be an object of class 'DEprot.sPLSDA'.")
    }

    if (is.null(DEprot.sPLSDA.object@tuning)) {
      stop("This object does not contain any tuning: the 'keepX' was provided at the `perform.sPLSDA` call.")
    }


    tb = DEprot.sPLSDA.object@tuning$error.rate

    if (!is.null(component)) {
      missing.components = setdiff(component, unique(tb$component))

      if (length(missing.components) > 0) {
        stop("The component(s) ", paste(missing.components, collapse = ", "), " are not available in the tuning.")
      }

      tb = tb[tb$component %in% component, , drop = FALSE]
    }

    tb$component.label = factor(paste0("comp", tb$component),
                                levels = paste0("comp", sort(unique(tb$component))))


    ### Values retained on each component
    choice = DEprot.sPLSDA.object@tuning$choice.keepX

    choice.tb =
      data.frame(component = seq_along(choice),
                 keepX = as.numeric(choice),
                 stringsAsFactors = FALSE)

    choice.tb = choice.tb[choice.tb$component %in% unique(tb$component), , drop = FALSE]
    choice.tb = merge(choice.tb, tb[, c("component", "keepX", "error.rate")], by = c("component", "keepX"))
    choice.tb$component.label = factor(paste0("comp", choice.tb$component), levels = levels(tb$component.label))


    ### Colors
    component.colors = .splsda.group.colors(group.colors = line.colors,
                                            group.labels = levels(tb$component.label))


    ### Generate the plot
    tuning.plot =
      ggplot(data = tb,
             aes(x = keepX,
                 y = error.rate,
                 color = component.label,
                 fill = component.label))

    if (show.sd == TRUE & !all(is.na(tb$error.rate.sd))) {
      tuning.plot =
        tuning.plot +
        geom_ribbon(aes(ymin = error.rate - error.rate.sd,
                        ymax = error.rate + error.rate.sd),
                    alpha = 0.15,
                    color = NA)
    }

    tuning.plot =
      tuning.plot +
      geom_line(linewidth = 0.6) +
      geom_point(size = 1.5, stroke = NA) +
      geom_point(data = choice.tb,
                 mapping = aes(x = keepX, y = error.rate),
                 shape = 21,
                 size = 3.5,
                 stroke = 1,
                 fill = NA,
                 color = "black",
                 inherit.aes = FALSE) +
      scale_x_log10(breaks = sort(unique(tb$keepX))) +
      scale_color_manual(values = component.colors, name = NULL) +
      scale_fill_manual(values = component.colors, name = NULL) +
      xlab("Number of proteins retained (keepX)") +
      ylab("Classification error rate") +
      ggtitle(label = title,
              subtitle = paste0("*circled: value retained (", DEprot.sPLSDA.object@parameters$dist, ", ",
                                DEprot.sPLSDA.object@parameters$validation, ")*")) +
      theme_classic() +
      theme(axis.text = element_text(color = "black"),
            axis.text.x = element_text(angle = 45, hjust = 1),
            panel.grid.major.y = element_line(color = "gray", linewidth = 0.1),
            plot.title = ggtext::element_markdown(hjust = 0.5),
            plot.subtitle = ggtext::element_markdown(hjust = 0.5, size = 8),
            aspect.ratio = 0.6)

    return(tuning.plot)
  } # END function




# ----------------------------------------------------------------------------------------


#' @title plot.sPLSDA.performance
#'
#' @description Plots the cross-validated classification error of a sPLS-DA as a function of the number of components.
#'
#' @param DEprot.sPLSDA.object An object of class \code{DEprot.sPLSDA}.
#' @param metric String indicating which error to display. One among: 'both', 'overall', 'BER' (balanced error rate). Default: \code{"both"}.
#' @param distance String indicating the prediction distance(s) to display. One among: 'all', 'max.dist', 'centroids.dist', 'mahalanobis.dist'. Default: \code{"all"}.
#' @param line.colors Color-vector used for the distances. Default: \code{NULL} (automatic colors).
#' @param title String indicating the title of the plot (markdown annotation supported). Default: \code{"**Cross-validated classification error**"}.
#'
#' @details
#' The balanced error rate is the average of the error rates of each class, and it is the value to read on an unbalanced design: with 9 samples in one group and 3 in the other, a model that assigns everything to the larger group already reaches an overall error of 25%.
#'
#' The dashed gray line marks the error of a random assignment, that is one minus the frequency of the largest class. A model sitting on that line is not discriminating anything, however clean its scatter plot looks.
#'
#' @return A ggplot object.
#'
#' @seealso \link{perform.sPLSDA}, \link{plot.sPLSDA.tuning}, \link{plot.sPLSDA.auroc}
#'
#' @name plot.sPLSDA.performance
#'
#' @import ggplot2
#' @import ggtext
#'
#' @author Sebastian Gregoricchio
#'
#' @examples
#' \donttest{
#' # the performances are estimated by resampling the samples
#' splsda <- perform.sPLSDA(DEprot.object = DEprot::test.toolbox$dpo.imp,
#'                          group.column = "condition",
#'                          keepX = 5,
#'                          validate = TRUE,
#'                          folds = 3,
#'                          nrepeat = 1)
#'
#' plot.sPLSDA.performance(DEprot.sPLSDA.object = splsda)
#' }
#'
#' @export plot.sPLSDA.performance

plot.sPLSDA.performance =
  function(DEprot.sPLSDA.object,
           metric = "both",
           distance = "all",
           line.colors = NULL,
           title = "**Cross-validated classification error**") {

    ### check object
    if (!("DEprot.sPLSDA" %in% class(DEprot.sPLSDA.object))) {
      stop("The input must be an object of class 'DEprot.sPLSDA'.")
    }

    if (is.null(DEprot.sPLSDA.object@performance)) {
      stop("This object does not contain any performance estimation: re-run `perform.sPLSDA` with 'validate = TRUE'.")
    }

    tb = DEprot.sPLSDA.object@performance$error.rate

    if (is.null(tb)) {
      stop("The error rates are not available in this object.")
    }


    ### Subset the metric
    if (tolower(metric) %in% c("overall")) {
      tb = tb[tb$metric == "Overall error rate", , drop = FALSE]
    } else if (tolower(metric) %in% c("ber", "balanced")) {
      tb = tb[tb$metric == "Balanced error rate", , drop = FALSE]
    } else if (!(tolower(metric) %in% c("both", "all"))) {
      stop("The 'metric' must be one among: 'both', 'overall', 'BER'.")
    }


    ### Subset the distance
    if (!(tolower(distance) %in% c("all", "both"))) {
      if (!(distance %in% unique(tb$distance))) {
        stop("The 'distance' requested is not available.\n",
             "       Available distances: ", paste(unique(tb$distance), collapse = ", "))
      }
      tb = tb[tb$distance == distance, , drop = FALSE]
    }

    tb$metric = factor(tb$metric, levels = c("Overall error rate", "Balanced error rate"))


    ### Error of a random assignment, used as reference
    group.sizes = table(DEprot.sPLSDA.object@groups)
    random.error = 1 - (max(group.sizes) / sum(group.sizes))


    ### Colors
    distance.colors = .splsda.group.colors(group.colors = line.colors,
                                           group.labels = sort(unique(tb$distance)))


    ### Generate the plot
    performance.plot =
      ggplot(data = tb,
             aes(x = component,
                 y = error.rate,
                 color = distance)) +
      geom_hline(yintercept = random.error, color = "gray", linetype = 2) +
      geom_line(linewidth = 0.6) +
      geom_point(size = 2, stroke = NA) +
      facet_wrap(facets = ~metric, nrow = 1) +
      scale_x_continuous(breaks = sort(unique(tb$component))) +
      scale_color_manual(values = distance.colors, name = "Distance") +
      xlab("Number of components") +
      ylab("Error rate") +
      ggtitle(label = title,
              subtitle = paste0("*", DEprot.sPLSDA.object@parameters$validation,
                                ifelse(DEprot.sPLSDA.object@parameters$validation == "Mfold",
                                       yes = paste0(" (", DEprot.sPLSDA.object@parameters$folds, " folds, ",
                                                    DEprot.sPLSDA.object@parameters$nrepeat, " repeats)"),
                                       no = ""),
                                "; dashed gray line: error of a random assignment*")) +
      theme_classic() +
      theme(axis.text = element_text(color = "black"),
            strip.background = element_blank(),
            strip.text = element_text(color = "black", face = "bold"),
            panel.grid.major.y = element_line(color = "gray", linewidth = 0.1),
            plot.title = ggtext::element_markdown(hjust = 0.5),
            plot.subtitle = ggtext::element_markdown(hjust = 0.5, size = 8),
            aspect.ratio = 0.8)

    return(performance.plot)
  } # END function




# ----------------------------------------------------------------------------------------


#' @title plot.sPLSDA.stability
#'
#' @description Plots how often each protein was re-selected across the cross-validation folds of a sPLS-DA.
#'
#' @param DEprot.sPLSDA.object An object of class \code{DEprot.sPLSDA}.
#' @param component Numeric value indicating the component to display. Default: \code{1}.
#' @param n.proteins Numeric value indicating the maximum number of proteins to display. Default: \code{25}.
#' @param bar.color String indicating the color of the bars of the proteins retained in the final model. Default: \code{"steelblue"}.
#' @param other.color String indicating the color of the bars of the proteins that were not retained in the final model. Default: \code{"gray70"}.
#' @param frequency.threshold Numeric value (0-1) drawn as a dashed line, used as a visual reference for a stable selection. Default: \code{0.8}.
#' @param protein.names.pattern String indicating a pattern to be passed to gsub and removed from the protein names. Default: \code{NULL} (no changes).
#' @param axes.text.size Numeric value indicating the font size of the axis text. Default: \code{9}.
#' @param title String indicating the title of the plot (markdown annotation supported). Default: \code{NULL} (automatic title).
#'
#' @details
#' The list of proteins returned by a sparse model is much less stable than it looks: on a small design, resampling the samples is often enough to swap half of it. A protein re-selected in nearly every fold is a marker worth following up; one appearing in a third of them is a property of the particular split, and the number written next to the bars is the only way to tell the two apart.
#'
#' Proteins that were not retained in the final model but were frequently selected during the resampling are shown as well, since they are exactly the candidates that a slightly different dataset would have picked.
#'
#' @return A ggplot object.
#'
#' @seealso \link{perform.sPLSDA}, \link{plot.sPLSDA.loadings}
#'
#' @name plot.sPLSDA.stability
#'
#' @import ggplot2
#' @import ggtext
#'
#' @author Sebastian Gregoricchio
#'
#' @examples
#' \donttest{
#' # the performances are estimated by resampling the samples
#' splsda <- perform.sPLSDA(DEprot.object = DEprot::test.toolbox$dpo.imp,
#'                          group.column = "condition",
#'                          keepX = 5,
#'                          validate = TRUE,
#'                          folds = 3,
#'                          nrepeat = 1)
#'
#' plot.sPLSDA.stability(DEprot.sPLSDA.object = splsda, component = 1)
#' }
#'
#' @export plot.sPLSDA.stability

plot.sPLSDA.stability =
  function(DEprot.sPLSDA.object,
           component = 1,
           n.proteins = 25,
           bar.color = "steelblue",
           other.color = "gray70",
           frequency.threshold = 0.8,
           protein.names.pattern = NULL,
           axes.text.size = 9,
           title = NULL) {

    ### check object
    if (!("DEprot.sPLSDA" %in% class(DEprot.sPLSDA.object))) {
      stop("The input must be an object of class 'DEprot.sPLSDA'.")
    }

    if (is.null(DEprot.sPLSDA.object@performance)) {
      stop("This object does not contain any performance estimation: re-run `perform.sPLSDA` with 'validate = TRUE'.")
    }

    stability = DEprot.sPLSDA.object@performance$stability

    if (is.null(stability)) {
      stop("The selection frequencies are not available in this object.")
    }

    tb = stability[stability$component == component, , drop = FALSE]

    if (nrow(tb) == 0) {
      stop("No selection frequency is available for the component ", component, ".")
    }


    ### Flag the proteins retained in the final model
    retained = DEprot.sPLSDA.object@selected.proteins[[component]]
    tb$retained = ifelse(tb$prot.id %in% retained,
                         yes = "Retained in the final model",
                         no = "Not retained")

    tb = tb[order(-tb$frequency), , drop = FALSE]

    if (!is.null(n.proteins)) {
      tb = utils::head(tb, round(n.proteins, 0))
    }

    if (!is.null(protein.names.pattern)) {
      tb$prot.id = gsub(protein.names.pattern, "", tb$prot.id)
    }

    tb$prot.id = factor(tb$prot.id, levels = rev(unique(tb$prot.id)))

    fill.colors = c("Retained in the final model" = bar.color,
                    "Not retained" = other.color)

    if (is.null(title)) {
      title = paste0("**Selection stability, component ", component, "**")
    }


    ### Generate the plot
    stability.plot =
      ggplot(data = tb,
             aes(x = frequency,
                 y = prot.id,
                 fill = factor(retained, levels = names(fill.colors)))) +
      geom_bar(stat = "identity", width = 0.75) +
      geom_vline(xintercept = frequency.threshold, color = "firebrick", linetype = 2) +
      scale_fill_manual(values = fill.colors, name = NULL, drop = FALSE) +
      scale_x_continuous(limits = c(0, 1), expand = c(0, 0)) +
      xlab("Frequency of selection across the folds") +
      ylab(NULL) +
      ggtitle(label = title,
              subtitle = paste0("*", DEprot.sPLSDA.object@parameters$validation,
                                "; dashed red line: ", frequency.threshold * 100, "% of the folds*")) +
      theme_classic() +
      theme(axis.line.y = element_blank(),
            axis.ticks.y = element_blank(),
            axis.text = element_text(color = "black", size = axes.text.size),
            panel.grid.major.x = element_line(color = "gray", linewidth = 0.1),
            plot.title = ggtext::element_markdown(hjust = 0.5),
            plot.subtitle = ggtext::element_markdown(hjust = 0.5, size = 8))

    return(stability.plot)
  } # END function




# ----------------------------------------------------------------------------------------


#' @title plot.sPLSDA.auroc
#'
#' @description Plots the cross-validated area under the ROC curve (AUC) of each class against all the others, component by component.
#'
#' @param DEprot.sPLSDA.object An object of class \code{DEprot.sPLSDA}.
#' @param component Numeric value (or vector) indicating the component(s) to display. Default: \code{NULL} (all the components).
#' @param point.colors Color-vector used for the components. Default: \code{NULL} (automatic colors).
#' @param show.sd Logical value indicating whether the standard deviation over the repeats should be drawn as an error bar. Default: \code{TRUE}.
#' @param title String indicating the title of the plot (markdown annotation supported). Default: \code{"**Cross-validated AUC**"}.
#'
#' @details
#' This is the AUC computed by \code{mixOmics::perf} over the resampling, and not a ROC curve drawn on the samples used to fit the model: the latter would be optimistic by construction, since a supervised model is fitted precisely to rank those samples correctly. The dashed line at 0.5 is the value of a coin toss.
#'
#' The comparisons are one class against all the others pooled, which is how mixOmics reports them for a multi-class design.
#'
#' @return A ggplot object.
#'
#' @seealso \link{perform.sPLSDA}, \link{plot.sPLSDA.performance}
#'
#' @name plot.sPLSDA.auroc
#'
#' @import ggplot2
#' @import ggtext
#'
#' @author Sebastian Gregoricchio
#'
#' @examples
#' \donttest{
#' # the performances are estimated by resampling the samples
#' splsda <- perform.sPLSDA(DEprot.object = DEprot::test.toolbox$dpo.imp,
#'                          group.column = "condition",
#'                          keepX = 5,
#'                          validate = TRUE,
#'                          folds = 3,
#'                          nrepeat = 1)
#'
#' plot.sPLSDA.auroc(DEprot.sPLSDA.object = splsda)
#' }
#'
#' @export plot.sPLSDA.auroc

plot.sPLSDA.auroc =
  function(DEprot.sPLSDA.object,
           component = NULL,
           point.colors = NULL,
           show.sd = TRUE,
           title = "**Cross-validated AUC**") {

    ### check object
    if (!("DEprot.sPLSDA" %in% class(DEprot.sPLSDA.object))) {
      stop("The input must be an object of class 'DEprot.sPLSDA'.")
    }

    if (is.null(DEprot.sPLSDA.object@performance)) {
      stop("This object does not contain any performance estimation: re-run `perform.sPLSDA` with 'validate = TRUE'.")
    }

    tb = DEprot.sPLSDA.object@performance$auc

    if (is.null(tb)) {
      stop("The AUC values are not available in this object.")
    }

    if (!is.null(component)) {
      missing.components = setdiff(component, unique(tb$component))

      if (length(missing.components) > 0) {
        stop("The component(s) ", paste(missing.components, collapse = ", "), " are not available.")
      }

      tb = tb[tb$component %in% component, , drop = FALSE]
    }

    tb$component.label = factor(paste0("comp", tb$component),
                                levels = paste0("comp", sort(unique(tb$component))))

    component.colors = .splsda.group.colors(group.colors = point.colors,
                                            group.labels = levels(tb$component.label))


    ### Generate the plot
    auroc.plot =
      ggplot(data = tb,
             aes(x = AUC,
                 y = comparison,
                 color = component.label)) +
      geom_vline(xintercept = 0.5, color = "gray", linetype = 2)

    if (show.sd == TRUE & !all(is.na(tb$AUC.sd))) {
      auroc.plot =
        auroc.plot +
        geom_linerange(aes(xmin = AUC - AUC.sd, xmax = AUC + AUC.sd),
                       linewidth = 0.4,
                       position = position_dodge(width = 0.5))
    }

    auroc.plot =
      auroc.plot +
      geom_point(size = 2.5, position = position_dodge(width = 0.5)) +
      scale_x_continuous(limits = c(0, 1)) +
      scale_color_manual(values = component.colors, name = NULL) +
      xlab("Area under the ROC curve") +
      ylab(NULL) +
      ggtitle(label = title,
              subtitle = "*dashed gray line: value of a random ranking*") +
      theme_classic() +
      theme(axis.line.y = element_blank(),
            axis.ticks.y = element_blank(),
            axis.text = element_text(color = "black"),
            panel.grid.major.x = element_line(color = "gray", linewidth = 0.1),
            plot.title = ggtext::element_markdown(hjust = 0.5),
            plot.subtitle = ggtext::element_markdown(hjust = 0.5, size = 8))

    return(auroc.plot)
  } # END function
